### ISSUE TITLE
[问题反馈] [日常] 恶名狩猎无法稳定走到鸣徽选择

### ISSUE THREAD

**Issue by MomentDerek** [DoctorReid/ZenlessZoneZero-OneDragon#103]
### 问题描述

1. 指定艾莲为队长，执行恶名狩猎-双子

### 你的建议

我debug了一下，调了一个更准确的1.2s，因为之前的1.5s的前进是直接顶到了选择鸣徽前的墙，所以够用，但是双子关卡时，顶着墙是够不到选择鸣徽的
另：有开发群么，发一下我的邮箱momincong@foxmail.com？

**Comment by DoctorReid** [comment]
暂时没有开发群，不过欢迎挑点感兴趣的内容开发，可以QQ联系
