### ISSUE TITLE
[问题反馈] [通用] 零号空洞，遇事件卡住

### ISSUE THREAD

**Issue by meiszzz** [DoctorReid/ZenlessZoneZero-OneDragon#105]
### 问题描述

运行：列车内部
配置：以太
在3角色已满情况下，遇事件自动选择加入第4人后卡住

### 游戏截图

![_1724340655568](https://github.com/user-attachments/assets/c47a020c-ddc8-45c6-9040-de19157ef83e)

### 运行日志

[新建 文本文档.txt](https://github.com/user-attachments/files/16714435/default.txt)

### 你的建议

有做自动登录和自动更新功能吗？
还有使用windows任务计划，如何启动一条龙？

**Comment by DoctorReid** [comment]
1. 有计划还没做
2. 可以问问gpt

**Comment by DoctorReid** [comment]
11号的战斗配置好用的话可以分享下在群里哈

**Comment by meiszzz** [comment]
是这样的，windows计划任务它本质上就是，到时间运行命令，来启动程序。
比如在cmd或Power shell里运行：
"D:\example.exe"
python "D:\example.py" autorun
"D:\example.bat"
所以其实我想问的是，启动日常一条龙(体力)的文件位置在哪？
GPT问不到这个

**Comment by DoctorReid** [comment]
目前是没有单独这个入口
