### ISSUE TITLE
未支持打开游戏

### ISSUE THREAD

**Issue by Brady-Busy** [DoctorReid/ZenlessZoneZero-OneDragon#11]
GUI运行正常，但是点开始之后会显示未支持打开游戏。我玩的是国际服所以进程名是ZenlessZoneZero不知道这个有没有影响。想问一下有没有什么能想到的quick fix

**Comment by DoctorReid** [comment]
快速可修改 `zzz_context.py` 中 `line 45` 的 `win_title`

目前看的是窗口名。你的游戏语言是英文吗？

**Comment by Brady-Busy** [comment]
> 快速可修改 `zzz_context.py` 中 `line 45` 的 `win_title`
> 
> 目前看的是窗口名。你的游戏语言是英文吗？

游戏语言是简体中文，只有进程名是英文。

**Comment by Brady-Busy** [comment]
解决啦，只需要修改成 win_title="ZenlessZoneZero" 就可以正常启动了。谢谢
