### ISSUE TITLE
[问题反馈] [通用] 每日委托触发角色信赖事件时，没有处理逻辑

### ISSUE THREAD

**Issue by DevilDmc** [DoctorReid/ZenlessZoneZero-OneDragon#114]
### 问题描述

每日委托触发角色信赖事件时，没有处理逻辑

### 你的建议

考虑到都是对话为主，比较快速的解决方式是默认第一项对话快速过掉，进而再重复对应脚本逻辑？

**Comment by DoctorReid** [comment]
还没有想到识别当前在对话的方案
