### ISSUE TITLE
关于每天自动启动游戏刷体力等等

### ISSUE THREAD

**Issue by ikunjjj** [DoctorReid/ZenlessZoneZero-OneDragon#126]
### 问题描述

建议加个每日自动启动的功能某星铁工具也有这功能，会很方便

### 游戏截图

![屏幕截图 2024-09-01 092824](https://github.com/user-attachments/assets/8817b07c-9ef5-483f-94b2-929d6dadc3e6)
![image](https://github.com/user-attachments/assets/9d2f7b65-8bad-43c1-88f4-97ec63c8b3b9)

**Comment by DoctorReid** [comment]
加入了 one_dragon.bat。可以先自行设置windows定时任务
