### ISSUE TITLE
[问题反馈] [闪避助手] 闪避助手无法正确运行

### ISSUE THREAD

**Issue by smallmj** [DoctorReid/ZenlessZoneZero-OneDragon#127]
### 问题描述

[log.txt](https://github.com/user-attachments/files/16827186/log.txt)
16：9的4k，1080p全屏，窗口化，重新安装都试过了，都无法解决问题。

### 问题副本

自动战斗和闪避助手

**Comment by DoctorReid** [comment]
按键设置里看看是不是错了，很久之前的默认配置是有问题的

**Comment by smallmj** [comment]
按键设置没改过，仔细检查了一下，没有问题啊

**Comment by smallmj** [comment]
[log.txt](https://github.com/user-attachments/files/16831378/log.txt)
直接通过闪避助手启动游戏直接报错

**Comment by smallmj** [comment]
把python3.12卸载了，问题解决了。。。。

**Comment by DoctorReid** [comment]
...
