### ISSUE TITLE
國際服因圖示不同無法使用一條龍

### ISSUE THREAD

**Issue by yulin126** [DoctorReid/ZenlessZoneZero-OneDragon#13]
如題 成功開啟一條龍後一直偵測不到遊戲，找了很久原因，才發現國服和國際服圖示不同
![圖片_2024-07-17_225456238](https://github.com/user-attachments/assets/c3cdb451-9b43-4628-9a8f-64b914d643dd)

**Comment by DoctorReid** [comment]
是的，可以参考 #11  先自行修改，周末我再加一个游戏服的设置。

有空的话，可以帮忙确认以下问题：

1. 国际服的窗口名称是统一的 `ZenlessZoneZero` 吗？

2. 游戏内切换游戏语言会改变窗口名称吗？

**Comment by yulin126** [comment]
國際服窗口名稱統一為ZenlessZoneZero，切換語言不會影響窗口名稱

**Comment by DoctorReid** [comment]
可以试试了
