### ISSUE TITLE
[问题反馈] [零号空洞] 

### ISSUE THREAD

**Issue by smallmj** [DoctorReid/ZenlessZoneZero-OneDragon#131]
### 问题描述

![1725269491180](https://github.com/user-attachments/assets/ad179cb8-e63c-4f88-a9af-e299917b4cbc)
进入交易格子，卡死，报错

### 问题副本

列车前线

**Comment by DoctorReid** [comment]
昨晚跑了两轮，没法重现。开调试模式上传日志
