### ISSUE TITLE
希望脚本可以从游戏中识别到任务的那一步然后进行开始

### ISSUE THREAD

**Issue by 2375399351** [DoctorReid/ZenlessZoneZero-OneDragon#134]
### 问题描述

发现目前脚本任务只要启动就必须从头开始运行，不能在任务中进行识别然后继续进行脚本，比如我在副本战斗中启动，脚本不能识别到战斗中进行战斗操作，反而会一直进行点击退出进入菜单的操作。
因为有时候0号空洞需要更换队伍，我是手动换队后启动脚本，但是这时候脚本就必须退出副本再启动才能正常按照脚本流程进行，希望可以优化一下这种流程

**Comment by DoctorReid** [comment]
目前有两种方案

1. 空洞内，按调试按钮，会继续完成本次空洞
2. 暂离后，按开始按钮，会自动继续上一次的

**Comment by DoctorReid** [comment]
已支持
