### ISSUE TITLE
[问题反馈] [零号空洞] 挑战副本“施工废墟-核心”不执行，直接点击奖励入口

### ISSUE THREAD

**Issue by Misan731** [DoctorReid/ZenlessZoneZero-OneDragon#136]
### 问题描述

挑战副本“施工废墟-核心”不执行，进入空洞选单识别为完成后直接点击奖励入口了

### 问题副本

施工废墟-核心

### 游戏截图

![_1725303051879](https://github.com/user-attachments/assets/d03dabc8-c044-4fdb-b4c8-c27fde5e9c5f)

### 运行日志

[log.txt](https://github.com/user-attachments/files/16840656/log.txt)

**Comment by Misan731** [comment]
在进行这次前 已经进行了一次旧都列车零号空间的挑战，感觉是根据 每周通关次数 的次数设定来判断是否去检查奖励？我把次数由图中的1改成2之后就可以正常进行下一次（施工废墟-核心）了

**Comment by DoctorReid** [comment]
是的

**Comment by DoctorReid** [comment]
https://one-dragon.org/zzz/zh/docs/feat_hollow_zero.html#_1-1-%E5%8A%9F%E8%83%BD%E6%80%A7%E9%85%8D%E7%BD%AE

基本上所有功能都有说明，可以多看
