### ISSUE TITLE
不清楚是哪里搞错掉了

### ISSUE THREAD

**Issue by AboPlus** [DoctorReid/ZenlessZoneZero-OneDragon#14]
![image](https://github.com/user-attachments/assets/428e43c5-e828-4ca9-9e0f-33b76ece8084)

**Comment by ParfoisMeng** [comment]
相同报错+1

**Comment by ParfoisMeng** [comment]
![image](https://github.com/user-attachments/assets/91809fb8-a32c-4994-ba90-31fbe4389f86)

**Comment by DoctorReid** [comment]
python环境问题先自行GPT解决。

周末会放一个简便的安装器出来方便大家使用

**Comment by AboPlus** [comment]
> python环境问题先自行GPT解决。
> 
> 周末会放一个简便的安装器出来方便大家使用

坐等了大佬！真没搞懂哪里出问题了

**Comment by DoctorReid** [comment]
https://github.com/DoctorReid/ZenlessZoneZero-OneDragon/releases/tag/0.0.2

有梯子的话用这个就可以了
