### ISSUE TITLE
[问题反馈] [通用] 如何通过任务计划启动后直接运行一条龙

### ISSUE THREAD

**Issue by imaegoo** [DoctorReid/ZenlessZoneZero-OneDragon#142]
### 问题描述

我希望通过Windows的任务计划功能每天定时自动运行一条龙，运行完成后自动关闭，三月七小助手就可以实现这一点。

![image](https://github.com/user-attachments/assets/b32c0adc-c1a8-4c01-bb18-8b8937e5396c)

目前app.bat只能启动gui，不能立即运行。有没有什么启动参数或命令可以直接运行？

**Comment by imaegoo** [comment]
我尝试了 `python src\zzz_od\application\zzz_one_dragon_app.py` 但不能运行：

```
ModuleNotFoundError: No module named 'email.parser'
```

**Comment by 123hi123** [comment]
有料 給你點贊💕

**Comment by DoctorReid** [comment]
加入了 one_dragon.bat
