### ISSUE TITLE
无法自动执行闪避操作

### ISSUE THREAD

**Issue by yibiya** [DoctorReid/ZenlessZoneZero-OneDragon#15]
是否需要在游戏内修改某些按键？虽然运行成功了但是没有自动执行闪避的效果
![image](https://github.com/user-attachments/assets/d2166f82-06d0-4cb6-97f6-a9f80d094a4c)
运行提示如上图
![image](https://github.com/user-attachments/assets/7036305d-eb7d-4938-be2e-b749a9ff39d3)
运行中如上图

**Comment by yibiya** [comment]
拉取下来没有找到game.yml和zzz_one_dragon.yml

**Comment by yibiya** [comment]
是否需要修改游戏内的按键映射？

**Comment by DabengBa** [comment]
我也时常遇到这个问题. 而且GPU的DML我也从来没有成功启动过.
我最近一次让他work是用pip卸载重装了onnxruntime. 但是今早又不行了.

**Comment by DoctorReid** [comment]
> 是否需要修改游戏内的按键映射？

界面左下角的【设置】-【游戏设置】里可以改按键

**Comment by DoctorReid** [comment]
> 我也时常遇到这个问题. 而且GPU的DML我也从来没有成功启动过. 我最近一次让他work是用pip卸载重装了onnxruntime. 但是今早又不行了. 话说这个面板返回太多东西了.

好像是我的 `requirements-prod.txt` 没有更新，我等会更新一下

**Comment by DoctorReid** [comment]
实际上卸载了 `onnxruntime` 然后安装 `onnxruntime-directml` 应该就没问题，我自己电脑上一直跑着

**Comment by DoctorReid** [comment]
@yibiya 想到另外一点，昨晚更新的模型，只在 `1920*1080` 画面下测试了，不太确定其它分辨率是否ok。可以换这个游戏分辨率试试

**Comment by yibiya** [comment]
请问是否可以修改游戏为窗口化呢？以及更改游戏分辨率

**Comment by yibiya** [comment]
> @yibiya 想到另外一点，昨晚更新的模型，只在 `1920*1080` 画面下测试了，不太确定其它分辨率是否ok。可以换这个游戏分辨率试试

改成1920*1080确实可以了

**Comment by DoctorReid** [comment]
那看来是模型不够鲁棒了，先使用16:9的画面吧

**Comment by DabengBa** [comment]
> @yibiya 想到另外一点，昨晚更新的模型，只在 `1920*1080` 画面下测试了，不太确定其它分辨率是否ok。可以换这个游戏分辨率试试

顺便是不是也要给一下推荐的画面配置, 比如精细度, 抗锯齿这些.

**Comment by DoctorReid** [comment]
> > @yibiya 想到另外一点，昨晚更新的模型，只在 `1920*1080` 画面下测试了，不太确定其它分辨率是否ok。可以换这个游戏分辨率试试
> 
> 顺便是不是也要给一下推荐的画面配置, 比如精细度, 抗锯齿这些.

其它的我估计影响不大，因为画面的宽高比会直接影响形状

**Comment by yibiya** [comment]
> @yibiya 想到另外一点，昨晚更新的模型，只在 `1920*1080` 画面下测试了，不太确定其它分辨率是否ok。可以换这个游戏分辨率试试

 我试着用了一下1280*720 窗口化模式 虽然脚本可以识别到需要闪避 但是实际上并没有操作 应该跟重装onnxruntime后正常的那个老哥情况一样 是否可以给脚本加入一个输出测试功能检测输出闪避按键是否正常？

**Comment by yibiya** [comment]
测试了一下 脚本实际上有按下space 但是在游戏内没有反应

**Comment by DoctorReid** [comment]
试试管理员权限运行。日志方面要看周末有没有时间优化，估计写完自定义指令就没时间了。

**Comment by yibiya** [comment]
> 试试管理员权限运行。日志方面要看周末有没有时间优化，估计写完自定义指令就没时间了。

确实是管理员权限的问题😭解决了

**Comment by yibiya** [comment]
建议老哥给app.bat加上提权https://github.com/yibiya/ZenlessZoneZero-OneDragon/blob/main/app.bat

**Comment by DoctorReid** [comment]
在上班呢，你可以修改一下提个PR哈哈
