### ISSUE TITLE
[问题反馈] [通用] 求拉我进群，申请了半个月没有进去，我QQ：2741941498

### ISSUE THREAD

**Issue by leeeyunlong** [DoctorReid/ZenlessZoneZero-OneDragon#155]
### 问题描述

861603314那个群一直进不去，只能来这里留言了。

**Comment by DoctorReid** [comment]
你的账号被腾讯判断为存在风险，为保证群安全，不予通过

**Comment by leeeyunlong** [comment]
> 你的账号被腾讯判断为存在风险，为保证群安全，不予通过

被胡乱举报才会提示这个啊，那我换个小号能不能进来，QQ：3629667929，
我实在没办法了才来这里留言，我觉得这个软件帮助很大，
想进来交流但为什么怎么都不让进群
