### ISSUE TITLE
[问题反馈] [通用] python_run.bat 启动失败

### ISSUE THREAD

**Issue by DabengBa** [DoctorReid/ZenlessZoneZero-OneDragon#156]
### 问题描述

D:\games\ZenlessZoneZero-OneDragon\.env\venv\scripts\pythonw.exe: can't open file 'D:\\games\\ZenlessZoneZero-OneDragon\\src" ': [Errno 22] Invalid argument

AI说, 这段话里少/多了个双引号

**Comment by smallmj** [comment]
一样的问题，可以通过安装器启动一条龙，但是不管运行app.bat还是python_run.bat都会报错

**Comment by DoctorReid** [comment]
使用app.bat

提供日志

**Comment by Evgracess** [comment]
> 一样的问题，可以通过安装器启动一条龙，但是不管运行app.bat还是python_run.bat都会报错

跟你同样的问题  没办法用app.bat运行

**Comment by DabengBa** [comment]
app.bat是这个报错:
```
已获取管理员权限
'python_run.bat' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by Ocetars** [comment]
+1，log如下
![image](https://github.com/user-attachments/assets/869361c5-4cb2-4c94-88f1-a4a781adce8c)

**Comment by DoctorReid** [comment]
已修复
