### ISSUE TITLE
[问题反馈] [通用] after_done状态无法记忆

### ISSUE THREAD

**Issue by Ocetars** [DoctorReid/ZenlessZoneZero-OneDragon#159]
### 问题描述

一条龙的“结束后”动作，设置为关闭游戏后，在配置文件中可以看到已经由0变成了1，但是再次启动app.bat或onedragon.bat时依然表现为执行动作“无”，需要每次手动修改设置为关闭游戏才能生效，如图

### 游戏截图

![image](https://github.com/user-attachments/assets/60dd7415-b8bf-4269-a153-485bfaa2ae39)
重新启动app.bat依然显示：
![image](https://github.com/user-attachments/assets/807c0382-0813-4152-ba94-af473c65a17a)

**Comment by DoctorReid** [comment]
已修复
