### ISSUE TITLE
[问题反馈] [通用] 体力计划选择自定义模板只会挑战自定义卡组5

### ISSUE THREAD

**Issue by Kakitoritay** [DoctorReid/ZenlessZoneZero-OneDragon#167]
### 问题描述

体力计划设置实战模拟室自定义模板，自定义卡组不论选择哪一个都会打自定义卡组5

**Comment by DoctorReid** [comment]
游戏里改细体字体试试

**Comment by Kakitoritay** [comment]
> 游戏里改细体字体试试

不行，改了细字体还是会点自定义卡组5的位置

https://github.com/user-attachments/assets/9eb2ce83-b7e3-49c9-9e81-f97e94d57c5e

**Comment by DoctorReid** [comment]
你改名了，不支持改名的

**Comment by Kakitoritay** [comment]
原来如此
