### ISSUE TITLE
[问题反馈] [通用] 建议体力计划增加一个循环执行开关

### ISSUE THREAD

**Issue by owwkmidream** [DoctorReid/ZenlessZoneZero-OneDragon#169]
### 问题描述

之前没仔细看说明，发现计划打完后会重复执行，还以为是BUG。
一些场景下，希望完成体力计划后停止执行，留存一些体力另做他用。

希望能改变当前行为，给【体力计划循环】增加一个开关的功能。

**Comment by DoctorReid** [comment]
已加入
