### ISSUE TITLE
[问题反馈] [闪避助手] 

### ISSUE THREAD

**Issue by Ejoe11** [DoctorReid/ZenlessZoneZero-OneDragon#181]
### 问题描述

1.真拿命验收 2.角色等级不高时 不会选择 确定并出战 3.比利走到npc时 角色偏离了 对话不到npc

### 问题副本

。

### 游戏截图

![image](https://github.com/user-attachments/assets/184afa10-a19e-4fec-bcc4-db2c2f708cea)

### 运行日志

。

### 你的建议

。

**Comment by hyqinglan** [comment]
我刚才提交了PR，你试试看最后对话不到NPC的问题解决没有

**Comment by smallmj** [comment]
同样的问题，代理人等级太低导致卡住无法进行到下一步

**Comment by DoctorReid** [comment]
实测帧数30是会吞按键，偏离问题自行看文档调整模拟按键解决
