### ISSUE TITLE
真拿命验收打完箱子换成比利以后跑不到交任务的地点，会卡住

### ISSUE THREAD

**Issue by smallmj** [DoctorReid/ZenlessZoneZero-OneDragon#184]
![Screenshot_20240910_092127_youqu.android.todesk.jpg](https://github.com/user-attachments/assets/7978f5f3-a059-4e64-9752-78ec7dcfa660)

**Comment by smallmj** [comment]
关闭了镜头自动跟随，解决问题了，但是提示代理人等级太低导致卡住的问题没有结局的

**Comment by smallmj** [comment]
![Screenshot_20240910_111310_youqu.android.todesk.jpg](https://github.com/user-attachments/assets/34f63930-8ffe-48b9-b08b-5d21fea9ffeb)

还是有几率跑不到交任务的点，10次里面有三四次都没法完成

**Comment by DoctorReid** [comment]
看[文档](https://one-dragon.org/zzz/zh/docs/feat_one_dragon.html#_3-%E6%97%A5%E5%B8%B8%E8%AF%B4%E6%98%8E)自行调整按键时长
