### ISSUE TITLE
[问题反馈] [零号空洞] 邦布事件-武装升级，不能正确选择离开

### ISSUE THREAD

**Issue by ATKghost** [DoctorReid/ZenlessZoneZero-OneDragon#188]
### 问题描述

邦布事件-武装升级，不能正确选择离开，一直在选择失效的选项

### 问题副本

列车-核心

### 游戏截图

![image](https://github.com/user-attachments/assets/9aa8845b-bbfc-4f1b-b24d-115f30a65914)

**Comment by DoctorReid** [comment]
使用脚本F11截图上传
