### ISSUE TITLE
[问题反馈] [通用] 

### ISSUE THREAD

**Issue by lavender7410** [DoctorReid/ZenlessZoneZero-OneDragon#190]
### 问题描述

戰鬥助手，簡專屬配對  簡 賽斯 麗娜 一直切麗娜出來然後直接開大 導致簡浪費了很多輸出空間

### 运行日志

[log.txt](https://github.com/user-attachments/files/16977085/log.txt)

**Comment by DoctorReid** [comment]
无法重现。自动战斗问题可以打开配置文件，到群里找对应作者反馈。

或者自己参考文档修改

**Comment by lavender7410** [comment]
> Owner

是QQ群嗎? 我沒號了..

**Comment by lavender7410** [comment]
> 无法重现。自动战斗问题可以打开配置文件，到群里找对应作者反馈。
> 
> 或者自己参考文档修改

我錄影給你看看吧 我真看不懂怎麼改 純小白
