### ISSUE TITLE
[问题反馈] [零号空洞] 

### ISSUE THREAD

**Issue by Ejoe11** [DoctorReid/ZenlessZoneZero-OneDragon#191]
### 问题描述

新想法：零号空洞旧都列车-核心 搬砖 A级邦布控件和565丁尼

### 问题副本

零号空洞旧都列车-核心

### 游戏截图

![image](https://github.com/user-attachments/assets/7b5ba96c-e865-4fca-94a1-dea995b8d4b4)
![image](https://github.com/user-attachments/assets/f227e0e0-9556-491e-a663-5a6292d0e540)
![image](https://github.com/user-attachments/assets/ba59c6fa-4231-410c-b3a5-c249ecd13151)

### 你的建议

1.空洞有小怪时 在第一层可以先用炸弹，然后直通到终点打精英。
2.零号空洞旧都列车-核心 搬砖 A级邦布控件和565丁尼。
（打完第一层的精英就可以直接退出了）
（如果不缺邦布控件还能出售控件换丁尼）
（如果想刷业绩用已有的空洞刷业绩的配置，这次建议只单纯刷A级邦布控件和丁尼）
3.所以建议在现有的功能里 加个1层打完就退出。无限刷，桀桀桀

**Comment by Ejoe11** [comment]
所以建议在现有的功能里 加个1层打完就退出。无限刷，桀桀桀

**Comment by gituser8749** [comment]
想太多，这个奖励只能结算总共45个BOSS，并不能无限刷。而收益最高的就是每周通关15次核心难度，这个功能已经有了。
