### ISSUE TITLE
加个蛇对蛇小游戏自动刷成就脚本

### ISSUE THREAD

**Issue by 1035011163** [DoctorReid/ZenlessZoneZero-OneDragon#192]
加个蛇对蛇小游戏自动刷成就脚本吧，左下角一直转就行
【「绝区零」贪吃蛇一键挂机1300W！龟壳神功！】 https://www.bilibili.com/video/BV1kM4m117db/?share_source=copy_web&vd_source=40fc5aa43cf144d231732e681f622e43

**Comment by devil233-ui** [comment]
草
