### ISSUE TITLE
[问题反馈] [通用] 怎么取消一条龙结束后退出登录啊？

### ISSUE THREAD

**Issue by Markjinli** [DoctorReid/ZenlessZoneZero-OneDragon#198]
### 问题描述

怎么取消一条龙结束后退出登录啊？

### 游戏截图

如题

**Comment by DoctorReid** [comment]
只有配置了多账号的情况会退出登录切换账号。

不想一条龙中切换账号就在一条龙里选择只运行当前实例，或者设置实例列表中选择不在一条龙运行
