### ISSUE TITLE
什么时候有空做不需要挂梯子的版本呀？

### ISSUE THREAD

**Issue by QHYSC** [DoctorReid/ZenlessZoneZero-OneDragon#20]
免费机场一直连不上 克隆不了仓库，或者做个手动更新仓库的也好

**Comment by DoctorReid** [comment]
后续可能同步到gitee吧，暂时不打算打包成独立exe了

**Comment by QHYSC** [comment]
那大概多久能做好呀

**Comment by wizardt** [comment]
建议就只在github.道理都懂。

**Comment by DoctorReid** [comment]
可以参考这个搞host

 https://github.com/521xueweihan/GitHub520
