### ISSUE TITLE
[问题反馈] [零号空洞] 在商店不会自动购买鸣徽

### ISSUE THREAD

**Issue by UnknownCjer** [DoctorReid/ZenlessZoneZero-OneDragon#204]
### 问题描述

零号空洞在商店不会自动购买鸣徽，脚本日志显示每次都是返回不需购买（即使有配置了需要购买的鸣徽）

### 问题副本

零号空洞的商店

### 运行日志

指令[ 空洞操作器 ] 节点 画面识别 返回状态 等待
指令[ 呼叫增援！ ] 节点 检测游戏窗口 返回状态 成功
指令[ 呼叫增援！ ] 节点 画面识别 返回状态 事件文本
指令[ 呼叫增援！ ] 执行成功 返回状态 事件文本
指令[ 空洞操作器 ] 节点 画面识别 返回状态 等待
指令[ 呼叫增援！ ] 节点 检测游戏窗口 返回状态 成功
指令[ 呼叫增援！ ] 节点 画面识别 返回状态 接应支援代理人
指令[ 呼叫增援！ ] 节点 接应支援代理人 返回状态 成功
指令[ 呼叫增援！ ] 节点 选择位置 返回状态 2号位
指令[ 呼叫增援！ ] 节点 确认 返回状态 事件文本
指令[ 呼叫增援！ ] 执行成功 返回状态 事件文本
指令[ 空洞操作器 ] 节点 画面识别 返回状态 等待
指令[ 空洞操作器 ] 节点 画面识别 返回状态 未能识别当前画面
识别完毕 得到结果 10个。预处理耗时 0.006s, 推理耗时 0.014s, 后处理耗时 0.001s
指令[ 空洞操作器 ] 节点 画面识别 返回状态 等待
识别完毕 得到结果 7个。预处理耗时 0.011s, 推理耗时 0.016s, 后处理耗时 0.000s
指令[ 空洞操作器 ] 节点 画面识别 返回状态 等待
识别完毕 得到结果 6个。预处理耗时 0.008s, 推理耗时 0.013s, 后处理耗时 0.000s
指令[ 空洞操作器 ] 节点 画面识别 返回状态 等待
指令[ 古怪装置 ] 节点 检测游戏窗口 返回状态 成功
指令[ 古怪装置 ] 节点 画面识别 返回状态 选择1枚诡术鸣徽
指令[ 古怪装置 ] 执行成功 返回状态 选择1枚诡术鸣徽
指令[ 空洞操作器 ] 节点 画面识别 返回状态 等待
指令[ 选择鸣徽 ] 节点 检测游戏窗口 返回状态 成功
指令[ 选择鸣徽 ] 节点 选择 返回状态 优先级无返回
指令[ 选择鸣徽 ] 节点 选择 返回状态 优先级无返回
指令[ 选择鸣徽 ] 节点 选择 返回状态 优先级无返回
指令[ 选择鸣徽 ] 节点 选择 返回状态 优先级无返回
指令[ 选择鸣徽 ] 节点 兜底选择 返回状态 选择
指令[ 选择鸣徽 ] 执行成功 返回状态 选择
指令[ 空洞操作器 ] 节点 画面识别 返回状态 等待
识别完毕 得到结果 4个。预处理耗时 0.006s, 推理耗时 0.008s, 后处理耗时 0.001s
指令[ 空洞操作器 ] 节点 画面识别 返回状态 等待
识别完毕 得到结果 2个。预处理耗时 0.008s, 推理耗时 0.015s, 后处理耗时 0.000s
指令[ 空洞操作器 ] 节点 画面识别 返回状态 等待
指令[ 空洞操作器 ] 节点 画面识别 返回状态 未能识别当前画面
指令[ 空洞操作器 ] 节点 画面识别 返回状态 未能识别当前画面
指令[ 邦布商人 ] 节点 检测游戏窗口 返回状态 成功
指令[ 邦布商人 ] 节点 画面识别 返回状态 外层选择
指令[ 邦布商人 ] 节点 鸣徽交易 返回状态 二级标题-鸣徽交易
指令[ 邦布商人 ] 节点 选择鸣徽 返回状态 不购买
暂停运行
指令[ 邦布商人 ] 节点 返回 返回状态 右上角-返回
指令[ 邦布商人 ] 执行成功 返回状态 右上角-返回
指令[ 空洞操作器 ] 节点 画面识别 返回状态 等待
停止运行

**Comment by DoctorReid** [comment]
1. 需要提供具体截图
2. 需要提供使用配置
3. 可以打开调试模式，重现问题后，上传log
