### ISSUE TITLE
[问题反馈] [通用] 多账户异常

### ISSUE THREAD

**Issue by idk500** [DoctorReid/ZenlessZoneZero-OneDragon#206]
### 问题描述

该问题来自Starlight

SwitchAccount
 src/zzz_od/operation/enter_game/switch_account.py

每个任务完成会调用一个函数返回代表任务完成
切账号理论上来说这个函数会被重置但是不知道什么原因判定为在第一个账号里继续了导致这个函数没被重置
所以这就是为什么多帐号没有正常的原因

**Comment by DoctorReid** [comment]
没看懂具体是什么问题

**Comment by SuperSB** [comment]
我也遇到过，就是一条龙执行多个实例的问题
加入有两个账号，即有两个实例A和B
实例A中一条龙执行的任务有 a、b、c
实例B中一条龙执行的任务有 a、b、c
跑完实例A后，假设完成a、c，剩下b未完成
切换下一个实例B的时候，没有reset任务状态为实例B的，继续用上一个实例A的任务状态
