### ISSUE TITLE
[问题反馈] [通用] 无法自动化运行

### ISSUE THREAD

**Issue by twenty-f** [DoctorReid/ZenlessZoneZero-OneDragon#207]
### 问题描述

过程：手动打开一条龙并运行脚本，可以正常运行，然后关闭脚本并根据教程设置定时任务。第二天发现没有运行，查询log发现卡在打开并登陆游戏这一步，并在重复一段时间后结束。于是手动运行OneDragon Scheduler或者one_dragon.bat，发现均报错如图![7BF109CEB27F356F7F9B8DF67FED09DA](https://github.com/user-attachments/assets/f13bd6cd-d29b-4c0c-b892-fd303445e2b1)

，点击确定后出现第二个报错框
![AE5E3E7C48F42E08DE28254C4F27F566](https://github.com/user-attachments/assets/8ed7d3f4-90d4-4357-aed2-2ca7e87102a7)

，在常见问题排查中没有找到对应情况，请求帮助。【win10系统，log如下】

### 游戏截图

游戏客户端没有运行

### 运行日志

![1F5875A0E001A8CED8C5018ECF8888B6](https://github.com/user-attachments/assets/cd60a008-b797-451c-9bc4-90ac8fe94272)
![3D6264316C1B5C990F59128EADDCF17E](https://github.com/user-attachments/assets/7b6a8ffb-12de-4684-b6e3-3d5821ddaa25)

**Comment by DoctorReid** [comment]
日志看代码版本有点旧，不过这个不影响。

这个问题只能自行解决了，不是脚本的问题。可以在群里问问其他用定时任务的人
