### ISSUE TITLE
[问题反馈] [通用] 账号登录需要优化登录方式

### ISSUE THREAD

**Issue by pared2021** [DoctorReid/ZenlessZoneZero-OneDragon#211]
### 问题描述

尝试登录游戏时，账户登录只在检测到游戏未启动时才会调用账户登录。这导致了一个登录页面的问题：如果游戏已经启动并处于图二（非登录页面）的状态，系统会自动登录，而不区分账号。这可能会导致一个账号的任务被另一个账号错误地完成。

### 游戏截图

![1D72450DB2238892E3520C1A23DFDE99](https://github.com/user-attachments/assets/04c12cb0-df19-4636-8c1e-28802abb73a2)
![48B1D0D14F4C5C729BF63E1A214E14F9](https://github.com/user-attachments/assets/78205edb-6621-47c5-bed1-0868c2da8063)

### 你的建议

需要在手动打开游戏，处在图一画面时也可以调用账号登录功能
处在图二页面时不要直接登录，而是重新输入一遍账号密码，确保再多账号下a账号能够执行a账号任务，b账号执行b账号任务

**Comment by movieuu** [comment]
现在的账户切换无论如何都不太好用 建议直接集成这个工具 用来切换账号
https://github.com/babalae/mihoyo-starter
