### ISSUE TITLE
[问题反馈] [零号空洞] 

### ISSUE THREAD

**Issue by mxxkx2** [DoctorReid/ZenlessZoneZero-OneDragon#213]
### 问题描述

问题1.在零号空洞功能中的挑战配置内，基于预设配置“默认-专属空洞-简”，自行调整了目标配队：1妮可2简3赛斯。但是在游戏内，首发简，如果第一次代理人事件碰到赛斯，会将他配置到2号位，第二次代理人事件碰上妮可，会将他配置到3号位。与我的目标配队不符。
问题2.在零号空洞功能中的挑战配置内，基于预设配置“默认-专属空洞-简”，自行调整了目标配队：1简2妮可3赛斯。但是在游戏内，首发简，如果第一次代理人事件碰到妮可，会将他配置到1号位，第二次代理人事件碰上赛斯，会将他配置到3号位。还是与我的目标配队不符。

### 问题副本

问题1：旧都列车核心
问题2：施工废墟核心

### 游戏截图

![旧都列车核心-预设妮可简赛斯-实际简赛斯妮可](https://github.com/user-attachments/assets/3044aa8c-cac8-4214-b6eb-6786e02f410a)
![旧都列车核心-预设妮可简赛斯-实际简赛斯妮可 (2)](https://github.com/user-attachments/assets/23d2d767-3b2f-479f-9c0b-0b60a9b01192)
![施工废墟核心-预设简赛斯妮可-实际妮可赛斯简 ](https://github.com/user-attachments/assets/ac9b40df-9d69-4c2e-b955-50f51b2d7f1d)
![施工废墟核心-预设简赛斯妮可-实际妮可赛斯简  (2)](https://github.com/user-attachments/assets/20ddc89b-71cb-4493-8521-dfa7935b46ae)

### 运行日志

[log.txt](https://github.com/user-attachments/files/17058939/log.txt)

### 你的建议

可能是工具会自行判断，如果第一次碰上的是妮可，则会将她安排在一号位，赛斯去三号位。如果第一次碰上赛斯，那就将他安排在二号位，将妮可安排在三号位。无论哪种，其实都是符合简赛斯妮可这个顺序的。但是这样，工具就不是完全按照玩家的要求来按顺序配队，只能说算是瑕疵吧，不怎么影响实际体验。

**Comment by DoctorReid** [comment]
在战斗中是没有区别的
