### ISSUE TITLE
[问题反馈] [零号空洞] 

### ISSUE THREAD

**Issue by mxxkx2** [DoctorReid/ZenlessZoneZero-OneDragon#214]
### 问题描述

在施工废墟核心一面关底boss的战斗中，会出现boss的首次黄光攻击不触发角色闪避或是振刀的情况，导致角色受击。

### 问题副本

施工废墟核心第一面关底boss，提丰-重击者型

### 游戏截图

![施工废墟核心-提丰重击者型首次黄光攻击不触发闪避或振刀](https://github.com/user-attachments/assets/fbc0275b-07dc-4ccb-bd75-a1aa5a522ccf)
![施工废墟核心-提丰重击者型首次黄光攻击不触发闪避或振刀2](https://github.com/user-attachments/assets/f754830b-1044-449d-81dc-36f06b20ab78)

### 运行日志

[log.txt](https://github.com/user-attachments/files/17059068/log.txt)

**Comment by DoctorReid** [comment]
刚开场还在识别是否需要移动，这个暂时是没法避免的
