### ISSUE TITLE
[问题反馈] [零号空洞] 

### ISSUE THREAD

**Issue by arestww** [DoctorReid/ZenlessZoneZero-OneDragon#215]
### 问题描述

一直重複動作

### 问题副本

一直跑去找資質考核但我要刷其他副本

### 游戏截图

![未命名](https://github.com/user-attachments/assets/5acedd7c-be0e-4d88-a325-82db6b9c98ed)

**Comment by DoctorReid** [comment]
选资质考核只是为了传送过去，过去了就会选对应的副本。

主要问题是识别不到，字体改细体试试

**Comment by arestww** [comment]
了解 謝謝大神
DoctorReid ***@***.***>於 2024年9月20日 週五，10:32寫道：

**Comment by arestww** [comment]
[image: image.png]
這樣怎麼解QQ

八奈 ***@***.***> 於 2024年9月20日 週五 上午10:33寫道：

**Comment by arestww** [comment]
![Uploading 未命名.png…]()

**Comment by arestww** [comment]
现在有开始跑图了 但是自动战斗方面怪怪的 想请问一下可以从哪里改善
像是红光没闪会吃攻击才有反应

DoctorReid ***@***.***>於 2024年9月20日 週五，11:44寫道：
