### ISSUE TITLE
[问题反馈] [战斗助手] 自动战斗红光束不会闪避

### ISSUE THREAD

**Issue by XYMoYingJun** [DoctorReid/ZenlessZoneZero-OneDragon#220]
### 问题描述

自动战斗红光束不会自动闪避，导致有些关卡无法S评分通关

### 问题副本

例如打重装侵袭者II型时无人机攻击和喷火攻击均没有闪避

**Comment by DoctorReid** [comment]
这些本来就是没有红光的，无法解决
