### ISSUE TITLE
[问题反馈] [零号空洞] 通关一遍后自动停止了

### ISSUE THREAD

**Issue by nano096** [DoctorReid/ZenlessZoneZero-OneDragon#221]
### 问题描述

rt
![0574b5822a564d1e4d0132ad70e821bb](https://github.com/user-attachments/assets/be6e758f-20c9-42d8-801c-3cf72e38cdad)

### 问题副本

旧都列车 核心

### 游戏截图

![_1727052421015](https://github.com/user-attachments/assets/c24a11ef-83a1-4771-b655-bd0fb6c22a30)

### 运行日志

[python_08.07.log](https://github.com/user-attachments/files/17091826/python_08.07.log)

**Comment by zkfpk6** [comment]
咋解决的哥们?一样的问题
