### ISSUE TITLE
[问题反馈] [零号空洞]  完整通关和额外刷取可以分开设置难度吗

### ISSUE THREAD

**Issue by f59375543** [DoctorReid/ZenlessZoneZero-OneDragon#223]
### 问题描述

目前只能选择一个难度，打完两次完整核心区后，剩下的额外刷取也都是在打核心区，能否设置打完两次后就去打前线区，加快刷取速度

### 问题副本

如上

**Comment by DoctorReid** [comment]
前期的确考虑过这个，后来等级高了发现不太需要，后续有空的时候加

**Comment by f59375543** [comment]
> 前期的确考虑过这个，后来等级高了发现不太需要，后续有空的时候加

 对了，请问打完以后自动退出，没有继续刷业绩，请问是怎么回事

![Uploading 20240924000425.png…]()
