### ISSUE TITLE
能否在闪避助手里面加一个识别场上角色的功能

### ISSUE THREAD

**Issue by smallmj** [DoctorReid/ZenlessZoneZero-OneDragon#230]
### 问题描述

比如凯撒站场就用格挡的方案，简站场就用闪避或者闪A切的方案

### 问题副本

闪避助手

**Comment by DoctorReid** [comment]
现在已经支持，自己修改配置文件即可

**Comment by smallmj** [comment]
能不能出个教程啊，不知道怎么修改配置文件，ui里面只能选择一个闪避方式啊

**Comment by DoctorReid** [comment]
可以参考本格挡的文件，国庆有空会重写一份自动战斗的配置教程

**Comment by smallmj** [comment]
我想问的不是自动战斗的角色识别，是闪避助手的，我想玩个半自动的，但是闪避助手只能选择一个配置，没法按照人物选择不同的闪避策略
