### ISSUE TITLE
[问题反馈] [通用] 启动之后无反应

### ISSUE THREAD

**Issue by drelover** [DoctorReid/ZenlessZoneZero-OneDragon#237]
### 问题描述

1、一键安装，正常
2、启动launcher
3、弹窗显示将在5+后启动
4、无ui界面弹出，弹窗消失

### 你的建议

是因为缺乏ui相关的依赖吗

**Comment by DoctorReid** [comment]
使用debug.bat 选6 然后上传日志

**Comment by drelover** [comment]
> 使用debug.bat 选6 然后上传日志

在debug.bat里选择3重新安装gui库之后成功解决问题。
