### ISSUE TITLE
[问题反馈] [战斗助手] 專屬隊伍 簡

### ISSUE THREAD

**Issue by lavender7410** [DoctorReid/ZenlessZoneZero-OneDragon#239]
[log.txt](https://github.com/user-attachments/files/17140262/log.txt)
### 问题描述

先感謝各位大大製作這個好用的東東
小弟對這些代碼啥的真的一竅不通
目前先說一下使用簡配隊自動戰鬥的一狀況做說明
1.根據需求 已經測試過 出戰順序 簡-賽斯-麗娜為正常隊伍 但因腳本上寫著需要 支援 簡 賽斯 這兩者我都使用過
出現的狀況為 麗娜 開場不自然狂閃避抖動  
終於切簡站場 黃光時依然切麗娜
切麗娜後會導致 麗娜往後極限閃避後造成簡需要跑一大段路才能攻擊到敵方
2.賽斯不打強化攻擊 不出盾 這就廢了 要他上場幹嘛? 不就是要他的盾+異常精通嗎？
以及終結技能一滿 場上的人自動放 經常是賽斯和麗娜在的時候就放了 十分無語

我也很想自己改 但我真的不會 望更新優化一下簡自動戰鬥邏輯 感恩

### 问题副本

ALL

### 运行日志

[log.txt](https://github.com/user-attachments/files/17139979/log.txt)

### 你的建议

使用正常簡-賽斯-麗娜上場 正常切換 ，通常都是打連手的時候切換順序問題 邦布通常都被跳過了  這個就看人吧
現在最主要的問題是 賽斯基本上不打完強化攻擊 沒給盾

9:03 把舊資料夾取消全部重裝後好了很多 賽斯會正常出盾 
        會切麗娜使用極限閃避拉開距離的狀況還是偶爾會發生 打了一把拳王素材關重新上傳了LOG

**Comment by lavender7410** [comment]
還有個問題就是 經常場上沒怪了/王進二段 人物一直往前攻擊跑超寄八遠 這在打一些關卡時會造成很腦殘的狀況發生
目前還有一些看起來沒辦法解決的事情就是有些王的攻擊是不閃黃/紅光的 不知如何解決

**Comment by lavender7410** [comment]
順便提一下 更新那個遠程代碼基本上沒成功過..
代碼版本一直獲取失敗

**Comment by pared2021** [comment]
不要放丽娜

**Comment by DoctorReid** [comment]
自动战斗的问题可以到QQ群里找配置文件的对应作者反馈，在这里很难说清楚，上传视频也麻烦。

更新代码失败可以到设置里切换你的代码源

**Comment by lavender7410** [comment]
> 自动战斗的问题可以到QQ群里找配置文件的对应作者反馈，在这里很难说清楚，上传视频也麻烦。
> 
> 更新代码失败可以到设置里切换你的代码源

主要是沒有QQ...

**Comment by DoctorReid** [comment]
@SMY2004-min 看看反馈

**Comment by lavender7410** [comment]
切換代碼源兩個都用了 還是失敗

> 自動戰鬥的問題可以到QQ群組找設定檔的回覆回饋，這裡很難說清楚，上傳影片也很麻煩。
> 
> 更新程式碼失敗可以到設定切換你的程式碼來源

兩個都用了 還是失敗

**Comment by SMY2004-min** [comment]
带丽娜有一个很严重的问题，丽娜是远程，会导致原来是红光的判断变成黄光，这就可能导致 简-闪避变成简-切人格挡，假如这次黄光会切赛斯格挡，但是因为这是误判的黄光(原红光)，就算你选择切下一个赛斯也会导致切出上一个丽娜。而且我写了切人有内置cd的，这次切人格挡的误判会导致赛斯不会10s内都不会切出。所以不建议带丽娜，因为她是远程。

**Comment by lavender7410** [comment]
> 帶麗娜有一個很嚴重的問題，麗娜是遠程的，會導致原來是紅光的選擇變成黃光，這可能導致簡閃避變成簡切人格擋，如果這次黃光會切賽斯格擋，因為但是這是判的黃光（原紅光），就算你選擇切下一個賽斯隨之導致切出上一個麗娜。的判判會導致賽斯不會10秒內都不會切出。

目前問題有狀況是就算不帶麗娜也有因為不識別前台人物 指令表在跳的是前台簡 畫面上的是賽斯 賽斯也不打左鍵長按的攻擊呢
