### ISSUE TITLE
[问题反馈] [通用] 刷拿命验收，找不到副本，需要满足什么条件，才能正确找到副本。

### ISSUE THREAD

**Issue by hiarno** [DoctorReid/ZenlessZoneZero-OneDragon#240]
### 问题描述

[问题反馈] [通用] 刷拿命验收，找不到副本，需要满足什么条件，才能正确找到副本。

2、能不能支持Fairy 自动找宝箱。

**Comment by hyqinglan** [comment]
应该是更新之后ocr模型失效了，等重新炼吧Σ(・Д・」)」

**Comment by hiarno** [comment]
我上个版本的时候，也不行。有什么地方需要我排查的吗？

**Comment by DoctorReid** [comment]
没有描述问题前后脚本在做什么，没有日志，没有截图，没法回复

**Comment by hyqinglan** [comment]
> 我上个版本的时候，也不行。有什么地方需要我排查的吗？

那你和我发的#234不是一个问题，我是1.2才不行的

**Comment by DoctorReid** [comment]
#234 类似这个问题的话，已经修复。

其他问题请按上述要求提供详细说明
