### ISSUE TITLE
新主線造成bug

### ISSUE THREAD

**Issue by 123hi123** [DoctorReid/ZenlessZoneZero-OneDragon#241]
![image-2.png](https://github.com/user-attachments/assets/a20b86a2-e757-4dbb-97cb-ab969a22d52d)

碰到這個地方的時候程序會出錯
不確定什麼原因造成
可以不修也沒關係 我把主線打完看看會不會好

**Comment by 0frostmourne0** [comment]
做了也没用，现在不识别野火镇的图标，传送翻到这就会卡住……

**Comment by 123hi123** [comment]
笑死 那我維持原定計劃 先買手把再來玩賽車
