### ISSUE TITLE
[问题反馈] [战斗助手] 使用艾莲专属模式，结果切出苍角后全程都是苍角在打

### ISSUE THREAD

**Issue by f59375543** [DoctorReid/ZenlessZoneZero-OneDragon#242]
附带战斗日志

[log.txt](https://github.com/user-attachments/files/17142425/log.txt)

**Comment by f59375543** [comment]
啊，不小心失误，把原帖改掉了

那也在这里重发吧


[问题反馈] [零号空洞] 现在花圃闪击模式可以连杀，能否添加在零号空洞的副本选项

问题描述
闪击模式只需要开杀，不用走格子，可以降低卡住的情况

问题副本
新增的花圃闪击

游戏截图
![20240926114715](https://github.com/user-attachments/assets/5d714dbf-8dd1-49cd-9abb-0f7484b350f3)

**Comment by yokuminto** [comment]
关于艾莲专属，请加群联系下巡夜，附上视频

**Comment by f59375543** [comment]
> 关于艾莲专属，请加群联系下巡夜，附上视频

卸载重装后恢复正常，谢谢了
