### ISSUE TITLE
[问题反馈] [通用]在地图传送时 无法识别新地图图标 导致无法传送卡住 

### ISSUE THREAD

**Issue by Lingxa** [DoctorReid/ZenlessZoneZero-OneDragon#245]
### 问题描述

在地图传送时 无法识别新地图图标 导致无法传送卡住

### 游戏截图

![96dff66a-cf1d-44a7-92e0-bfe27a98fc6d](https://github.com/user-attachments/assets/441c4de1-de59-4e2b-b7f4-bdece1923c1c)

**Comment by DoctorReid** [comment]
已修复
