### ISSUE TITLE
[问题反馈] [通用] 地圖切換的時候卡住

### ISSUE THREAD

**Issue by super0624** [DoctorReid/ZenlessZoneZero-OneDragon#247]
### 问题描述

切換地點時，打開地圖後不會按確認

### 游戏截图

![1727365778288](https://github.com/user-attachments/assets/04b56f27-bef5-4d09-be5d-f9da54fcb2f7)

**Comment by DoctorReid** [comment]
请使用简体中文，不支持繁体中文
