### ISSUE TITLE
自动启动游戏功能

### ISSUE THREAD

**Issue by DoctorReid** [DoctorReid/ZenlessZoneZero-OneDragon#25]

**Comment by Spyict** [comment]
start "" "D:\Game pack\miHoYo Launcher\games\ZenlessZoneZero Game\ZenlessZoneZero.exe"
这样就行了，start加“”表示后面是真实路径，否则会误认为空格前是一个窗口标题（既然能自启动，可以加入自动点击进游戏吗，那样我点两下就不用管了）

**Comment by DoctorReid** [comment]
只是没时间搞而已，崩铁那边都搞了
