### ISSUE TITLE
加入开发

### ISSUE THREAD

**Issue by DoctorReid** [DoctorReid/ZenlessZoneZero-OneDragon#26]
[到这里看看准备做啥](https://github.com/DoctorReid/ZenlessZoneZero-OneDragon/wiki/%E5%BC%80%E5%8F%91%E2%80%90%E5%8A%A0%E5%85%A5%E5%BC%80%E5%8F%91)

**Comment by XerxesLee** [comment]
这个界面UI虽然较为朴素，但是很清新清晰好看🤩Python编写的应用前端没有接触过，只在Electron(HTML)前端进行过开发，哈哈哈💪🏻大佬加油

**Comment by idk500** [comment]
链接过期了
