### ISSUE TITLE
[问题反馈] [通用] 一条龙增加清除任务进程功能和重新执行全部任务功能

### ISSUE THREAD

**Issue by zhoupoui** [DoctorReid/ZenlessZoneZero-OneDragon#267]
### 问题描述

可以选择重启一条龙全部任务吗？现在一条龙会不断执行上一次未成功的任务，哪怕关闭重新打开也会。比如清体力中如果人为结束一条龙，再启动只会继续执行该任务而忽视其他任务，希望可以出一个执行全部任务的选项。

### 游戏截图

![image](https://github.com/user-attachments/assets/3710acbb-0df4-4881-8628-d15442159828)

**Comment by DoctorReid** [comment]
为什么已经成功的还需要再运行，多账号功能不能用吗

**Comment by zhoupoui** [comment]
比如咖啡没喝，会继续执行刷任务不断刷本，而我没有办法终止任务进程，只能单独执行喝咖啡。多账号功能新增账号仍可能会记住上个账号的未执行任务继续执行，关闭程序等待一段时间后可解决
