### ISSUE TITLE
[问题反馈] [零号空洞]   零号业绩的S门改版，现在无法识别门而被卡住

### ISSUE THREAD

**Issue by f59375543** [DoctorReid/ZenlessZoneZero-OneDragon#274]
### 问题描述

零号业绩的S门无法打开，撞门几下后就离开了

### 问题副本

零号业绩的S门

### 游戏截图

![20241001211619](https://github.com/user-attachments/assets/afdf5869-d186-4aa5-a7c4-f2da180cc2b8)

### 运行日志

[log.txt](https://github.com/user-attachments/files/17210153/log.txt)

附带bug视频
https://wwsc.lanzouo.com/isLQd2bcawoh

**Comment by f59375543** [comment]
附带bug视频

https://wwsc.lanzouo.com/isLQd2bcawoh

**Comment by DoctorReid** [comment]
应该修复了 更新代码试试
