### ISSUE TITLE
[问题反馈] [战斗助手] 庞培周本无法正常领取铭辉

### ISSUE THREAD

**Issue by kaguyaxue** [DoctorReid/ZenlessZoneZero-OneDragon#276]
### 问题描述

铭辉位置在斜对角，无法领取

### 问题副本

恶名狩猎-庞培

### 游戏截图

![屏幕截图 2024-10-02 222447](https://github.com/user-attachments/assets/3f0e36b3-99fc-44bd-9f97-87f3c8e45d45)

**Comment by DoctorReid** [comment]
修复了 更新代码
