### ISSUE TITLE
[问题反馈] [通用] 考虑试用win32clipboard解决输入账号密码时，中文输入法导致密码错误的问题

### ISSUE THREAD

**Issue by tignioj** [DoctorReid/ZenlessZoneZero-OneDragon#280]
### 问题描述

登陆时，输入密码会因为中文输入法导致密码错误

### 你的建议

    @staticmethod
    def copy_string(text):
        import win32clipboard
        import win32con

        try:
            win32clipboard.OpenClipboard()
            win32clipboard.EmptyClipboard()
            win32clipboard.SetClipboardText(text, win32con.CF_UNICODETEXT)
        finally:
            win32clipboard.CloseClipboard()

    @staticmethod
    def paste_text():
        import win32clipboard, win32con, win32api
        # 打开剪贴板
        win32clipboard.OpenClipboard()

        try:
            # 获取剪贴板中的数据
            data = win32clipboard.GetClipboardData(win32con.CF_UNICODETEXT)
        except:
            # 如果获取失败，返回空字符串
            data = ''
        finally:
            # 关闭剪贴板
            win32clipboard.CloseClipboard()

        # 模拟按下 Ctrl+V
        win32api.keybd_event(0x11, 0, 0, 0)  # Ctrl键按下
        win32api.keybd_event(0x56, 0, 0, 0)  # V键按下
        win32api.keybd_event(0x56, 0, win32con.KEYEVENTF_KEYUP, 0)  # V键释放
        win32api.keybd_event(0x11, 0, win32con.KEYEVENTF_KEYUP, 0)  # Ctrl键释放

        return data

**Comment by Leapiny** [comment]
我是把系统输入法默认设置成英文解决

**Comment by MomentDerek** [comment]
> 我是把系统输入法默认设置成英文解决

如果能有剪贴板的方式会更稳定，因为哪怕只有一次是登录失败了，也会很难受，因为得手动输入，重新登录，再开一条龙
