### ISSUE TITLE
[问题反馈] [战斗助手] 

### ISSUE THREAD

**Issue by jiucao2333** [DoctorReid/ZenlessZoneZero-OneDragon#290]
### 问题描述

最新版本下战斗助手相关功能失效，运行后战斗助手一直在返回等待且不会触发闪避，分辨率是1920*1080，31dbdc5这个commit版本还正常使用，更新到69ca2f6后才出的问题

### 问题副本

全副本

**Comment by DoctorReid** [comment]
暂时先回滚了
