### ISSUE TITLE
[问题反馈] [零号空洞] 进入【盲盒】区域后，某一张地图出不来

### ISSUE THREAD

**Issue by Leapiny** [DoctorReid/ZenlessZoneZero-OneDragon#295]
### 问题描述

其他的盲盒区域没有发现问题，今天遇到了3次，卡在某一个盲盒区域出不来，都是同一个地图。感觉是这个地图的【不宜久留】（就是退出地图的位置），没有自动弹出对话框，或者某些情况导致第一次进入退出位置时没有退出，再进入退出区域，就不弹对话框，导致死循环。

### 问题副本

旧都列车 - 核心  进入 【盲盒】区域

### 游戏截图

https://github.com/user-attachments/assets/1e0273bf-9fdc-4db0-be4c-fee128271ef5

**Comment by DoctorReid** [comment]
还没有遇到过，需要知道第一次进这个格子发生什么情况

**Comment by Leapiny** [comment]
> 还没有遇到过，需要知道第一次进这个格子发生什么情况

明白，后面我再多观察观察。如果能看到第一次进入的样子，再尝试文字描述当时的情况。
