### ISSUE TITLE
[问题反馈] [零号空洞] 商人间来回移动

### ISSUE THREAD

**Issue by DoctorReid** [DoctorReid/ZenlessZoneZero-OneDragon#298]
### 问题描述

出现多个商人时，会在多个商人间来回移动

### 问题副本

列车核心、腹地

**Comment by fysd** [comment]
我也遇到了，一个图有2个商店基本都会出现来回进的问题![mmexport1728443550939.jpg](https://github.com/user-attachments/assets/a7902e5d-bd0e-4d89-a591-9c2235626ddc)

**Comment by gongfuture** [comment]
我也遇到了

https://github.com/user-attachments/assets/9ffc5661-3966-42e9-8b44-6d36c36a69b4

**Comment by 123hi123** [comment]
我也遇到了商人折返跑
![image](https://github.com/user-attachments/assets/19c2f5d0-b78e-491a-b4d2-0115bae3529a)

**Comment by 123hi123** [comment]
> 我也遇到了，一个图有2个商店基本都会出现来回进的问题![mmexport1728443550939.jpg](https://private-user-images.githubusercontent.com/47217334/374790124-a7902e5d-bd0e-4d89-a591-9c2235626ddc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0ODA1ODgsIm5iZiI6MTcyODQ4MDI4OCwicGF0aCI6Ii80NzIxNzMzNC8zNzQ3OTAxMjQtYTc5MDJlNWQtYmQwZS00ZDg5LWE1OTEtOWMyMjM1NjI2ZGRjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDEzMjQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmMGQzYmQ5NWY3YzY3ZmFmNTljMjkzMDIxMmNmM2NkNGU1MWU1YmFkMGFjZWRjNjIwYmNiYWYyMmViMjI5MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8OQZyEqK0UhUSJJX8kbqIsKIbGkiGEBfQVqFmYQCSh0)

老友 這個遠程桌面能不能介紹下 我試試看跟我現在的比怎麼樣

**Comment by DoctorReid** [comment]
刷了一个半小时都没遇到这样的图，明天更新代码后如果还有问题的话再给我反馈。

最好可以暂离，留个账号给我晚上调试

**Comment by 123hi123** [comment]
![image](https://github.com/user-attachments/assets/611edb94-1eea-438b-add6-b20028aecc0a)
這是工廠 內部

**Comment by 123hi123** [comment]
或者我換列車就不會有這問題

**Comment by 123hi123** [comment]
![image](https://github.com/user-attachments/assets/c2cad84f-36eb-4e10-8893-525f643b9351)
第三關也是會折返跑 可能工廠這邊有什麼 bug 吧

**Comment by fysd** [comment]
> > 我也遇到了，一个图有2个商店基本都会出现来回进的问题![mmexport1728443550939.jpg](https://private-user-images.githubusercontent.com/47217334/374790124-a7902e5d-bd0e-4d89-a591-9c2235626ddc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0ODA1ODgsIm5iZiI6MTcyODQ4MDI4OCwicGF0aCI6Ii80NzIxNzMzNC8zNzQ3OTAxMjQtYTc5MDJlNWQtYmQwZS00ZDg5LWE1OTEtOWMyMjM1NjI2ZGRjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDEzMjQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmMGQzYmQ5NWY3YzY3ZmFmNTljMjkzMDIxMmNmM2NkNGU1MWU1YmFkMGFjZWRjNjIwYmNiYWYyMmViMjI5MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8OQZyEqK0UhUSJJX8kbqIsKIbGkiGEBfQVqFmYQCSh0)
> 
> 老友 這個遠程桌面能不能介紹下 我試試看跟我現在的比怎麼樣

gameviewer

**Comment by 123hi123** [comment]
> > > 我也遇到了，一个图有2个商店基本都会出现来回进的问题![mmexport1728443550939.jpg](https://private-user-images.githubusercontent.com/47217334/374790124-a7902e5d-bd0e-4d89-a591-9c2235626ddc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0ODA1ODgsIm5iZiI6MTcyODQ4MDI4OCwicGF0aCI6Ii80NzIxNzMzNC8zNzQ3OTAxMjQtYTc5MDJlNWQtYmQwZS00ZDg5LWE1OTEtOWMyMjM1NjI2ZGRjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDEzMjQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmMGQzYmQ5NWY3YzY3ZmFmNTljMjkzMDIxMmNmM2NkNGU1MWU1YmFkMGFjZWRjNjIwYmNiYWYyMmViMjI5MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8OQZyEqK0UhUSJJX8kbqIsKIbGkiGEBfQVqFmYQCSh0)
> > 
> > 老友 這個遠程桌面能不能介紹下 我試試看跟我現在的比怎麼樣
> 
> gameviewer

https://gv.163.com/
好像有聽過 不過這款好像是模擬器不是遠端桌面
