### ISSUE TITLE
[问题反馈] [通用] 

### ISSUE THREAD

**Issue by 2364846661** [DoctorReid/ZenlessZoneZero-OneDragon#306]
### 问题描述

1.运行软件成功
2.软件其他操作成功
3.进入战斗时软件闪退

### 游戏截图

https://github.com/user-attachments/assets/518239cf-8834-4af9-b43f-67bb5dd55f06

### 运行日志

![20241012-224248](https://github.com/user-attachments/assets/b905b3ab-b38d-491d-a559-2cd48f69129a)

**Comment by DoctorReid** [comment]
在群里找管理远程看看
