### ISSUE TITLE
影像店营业bug

### ISSUE THREAD

**Issue by smallmj** [DoctorReid/ZenlessZoneZero-OneDragon#307]
影像店选的简和11号来营业，进入选人界面后不停的往下拉，然后找不到人，退出
https://github.com/user-attachments/assets/f04600eb-b2d3-4972-b457-8b981bfb59c6

**Comment by movieuu** [comment]
应该是11号识别的问题 某一个版本之后就识别不到11号了 把11号换下去就好了

**Comment by DoctorReid** [comment]
这里比较难保证所有代理人都能识别到，遇到识别不到就换一个吧，暂时没有解决方案
