### ISSUE TITLE
[问题反馈] [通用] 

### ISSUE THREAD

**Issue by Qnx1996** [DoctorReid/ZenlessZoneZero-OneDragon#335]
### 问题描述

1.刷<真 拿命验收>的时候会点到该副本页面的第一个副本中<[恶战]指引：零号空洞的扰动>
![_1729340319694](https://github.com/user-attachments/assets/1bbc7e43-066b-4cb0-9b43-ba156f096c9a)

### 游戏截图

![_1729340141251](https://github.com/user-attachments/assets/3aedc421-6bd9-4fdb-820b-112075d0c9cd)
![_1729340319694](https://github.com/user-attachments/assets/e5150e86-6648-43e1-b74a-377dc54dd7df)

### 运行日志

[log.txt](https://github.com/user-attachments/files/17445141/log.txt)

**Comment by DoctorReid** [comment]
我这边重现不了，可以试试是否还有问题
