### ISSUE TITLE
[enhancement] [零号空洞] 是否可以添加一个“GPU运算”的开关？

### ISSUE THREAD

**Issue by XDMrSmile** [DoctorReid/ZenlessZoneZero-OneDragon#345]
### 问题描述

少部分特殊GPU无法正确识别走格子画面，希望添加一个“GPU运算”的开关，像自动战斗版块一样。

### 问题副本

走格子画面，应该很难复现，因为是很冷门的GPU，用其他GPU是可以正常识别的，如图所示。自动战斗板块只要关闭“GPU运算”就正常了，所以希望零号空洞板块也能添加这个功能。

### 游戏截图

![pes_20241022_203743](https://github.com/user-attachments/assets/69cb750f-f4b3-473b-bc00-ee1634781b1c)
![pes_20241022_204025](https://github.com/user-attachments/assets/69234432-7871-4cc2-bf1a-3efb18ccdb95)
![_1729601271259](https://github.com/user-attachments/assets/a7619302-22d1-452f-a535-655a822c6b9a)

**Comment by XDMrSmile** [comment]
应该是enhancement，我觉得不算bug。

**Comment by XDMrSmile** [comment]
![屏幕截图 2024-10-23 021805](https://github.com/user-attachments/assets/c6b53cfb-1e6a-41b2-b248-c94888bec41f)
把这个改成CPU了也正常的。

**Comment by DoctorReid** [comment]
这么神奇，后续统一加上
