### ISSUE TITLE
[问题反馈] [通用] 希望每次体力计划后可以重置运行次数，或者加入一个选项重置运行次数

### ISSUE THREAD

**Issue by Xiao-Ma-cookiemx** [DoctorReid/ZenlessZoneZero-OneDragon#347]
### 问题描述

在体力计划完成之后，运行次数会被记录，第二日再运行时，前一日已经达到运行次数的计划会被跳过。

### 你的建议

 希望每次体力计划后可以重置运行次数，或者加入一个选项允许使用者重置运行次数

**Comment by DoctorReid** [comment]
为什么需要重置？不想刷剩下的副本的话，为什么还要加到计划里？

**Comment by Xiao-Ma-cookiemx** [comment]
啊，因为想省事，比如这次活动要刷驱动盘的话，就可以放一个计划在里面，调整好配队，平时调整一下顺序就好了。

不过这个也不是什么必要的需求，只是提个建议而已。
