### ISSUE TITLE
[问题反馈] [通用] 希望可以手动多加一个额外的咖啡后清体力

### ISSUE THREAD

**Issue by morlegion** [DoctorReid/ZenlessZoneZero-OneDragon#348]
### 问题描述

先买咖啡再体力刷本的的话体力容易略微溢出，虽然不多，但心理上心疼。
将清体力放在买咖啡之前的话，丽都城募会概率无法一次性做完，而丽都城募每天只执行一次，导致漏掉。

**Comment by DoctorReid** [comment]
体力 -> 咖啡 -> 大月卡

这个顺序会有什么问题？

**Comment by morlegion** [comment]
> 体力 -> 咖啡 -> 大月卡
> 
> 这个顺序会有什么问题？


应该说是绝区零本身的体力上限和丽都城募的问题。
当清体力时体力超过160，就需要用体力-咖啡-大月卡顺序来避免溢出（因为习惯问题，很多时候不会刻意去看体力，而是直接用这种顺序来保险防溢出）。
体力刷取最常见的模式是一次100体力（hia）和一次60体力（驱动盘），丽都城募每日任务要求是160。
喝咖啡之前体力少于200，刷hia材料，就会只消耗100体；体力少于180，刷驱动盘，就会只消耗120体。
消耗结束后喝咖啡，然后丽都城募每日任务就会无法全部完成。
因为丽都城募每天只启动一次，即便每天上线的第二次消耗了体力，也不会再去点击并完成丽都城募了。
实际操作下来就是，假如按照设计初衷（完全放置游戏），每天运行两次（防溢出），有可能会少一个丽都城募任务。

**Comment by DoctorReid** [comment]
明白了，后续会将大月卡调整成每次都运行

**Comment by morlegion** [comment]
> 明白了，后续会将大月卡调整成每次都运行

这样也行~不过如果可以的话还是希望能弄一个选项，选中在咖啡后面多加一个战斗啦（挠头），毕竟咖啡之后直接结束程序，极端情况（打100体副本）的话，会直接变成最高179体力，这样最低6小时内就必须再刷一次，要不然就得运行完这一次再手动重新开一次程序，也挺麻烦的。
