### ISSUE TITLE
闪避助手加入声音识别

### ISSUE THREAD

**Issue by DoctorReid** [DoctorReid/ZenlessZoneZero-OneDragon#35]
有待研究 https://github.com/ImLaoBJie/ZZZSoundTrigger

**Comment by Markjinli** [comment]
非常好正准备来提呢~如果大佬需要无光攻击的素材可以滴滴我帮你采集一下~

**Comment by DoctorReid** [comment]
@Markjinli 如有有空的话，的确可以帮忙试试，看声音可以覆盖哪些没有光的场景，哪些又是覆盖不了的。

视频我周末有空再看看
