### ISSUE TITLE
[问题反馈] [通用]第一次安装启动一条龙时系统报错

### ISSUE THREAD

**Issue by Marxism6** [DoctorReid/ZenlessZoneZero-OneDragon#354]
### 问题描述

正如标题和图片所示

### 游戏截图

![image](https://github.com/user-attachments/assets/59fcfc1a-896f-4c2c-88e5-b93991f442aa)

### 运行日志

[log.txt](https://github.com/user-attachments/files/17529068/log.txt)

**Comment by Marxism6** [comment]
补一个图
![image](https://github.com/user-attachments/assets/6495a0d6-91f5-4bc4-b5a7-8441d9d3c33b)

**Comment by DoctorReid** [comment]
环境问题自行gpt
