### ISSUE TITLE
[问题反馈] [通用] 更新后出现“This application failed to start because no Qt platform plugin could be initialized.”

### ISSUE THREAD

**Issue by junyahuang** [DoctorReid/ZenlessZoneZero-OneDragon#356]
### 问题描述

更新之后打不开助手了，一直弹出这个。也试图重装了，好像没什么作用![image](https://github.com/user-attachments/assets/59ed9e2d-85de-4bea-bb5b-384a55739046)

**Comment by junyahuang** [comment]
直接在文件夹里运行OneDragon Launcher.exe就进去了，算解决了（？）但是从安装器进去还是不行，有点奇怪

**Comment by movieuu** [comment]
同样的问题,下午刚更新完/安装依赖后可以正常启动,然后系统24h2更新了个KB5044384 重启后就遇到这个问题了

**Comment by movieuu** [comment]
下载最新release里的update 覆盖后正常了

**Comment by DoctorReid** [comment]
如果还有问题，可以参考 [这个](https://www.bilibili.com/video/BV1Vq4y1X73o?vd_source=01e344680ce2fb5a0bf15b318e702481) 解决
