### ISSUE TITLE
[问题反馈] [零号空洞] 进入商店后，不断循环“打开商店”→“买完东西”→“关闭商店”→“打开商店”，无法离开商店

### ISSUE THREAD

**Issue by f59375543** [DoctorReid/ZenlessZoneZero-OneDragon#362]
### 问题描述

进入商店后，不断循环“打开商店”→“买完东西”→“关闭商店”→“打开商店”，无法离开商店，已附带log

### 问题副本

旧都列车第三难度

### 运行日志

[log.txt](https://github.com/user-attachments/files/17536263/log.txt)

**Comment by DoctorReid** [comment]
录个屏看看

**Comment by f59375543** [comment]
> 录个屏看看

抱歉，我挂机一个中午后只复现了一次，按F9暂停打开录屏软件，再按F9重启后就自动离开商店走人了，接下来挂着也没有复现

**Comment by q450492742** [comment]
我也是， 卡在商店那， 不断在商店进出。

**Comment by XDMrSmile** [comment]
> 录个屏看看

![_1729622453642](https://github.com/user-attachments/assets/6a10960c-51fb-4df1-a4f3-7b5130075498)

https://github.com/user-attachments/assets/5a8f0581-4cdb-4a76-9eca-facbaa745216

[02:42:46.668] [hollow_context.py 161] [INFO]: 优先级 [终点]
[02:42:46.668] [hollow_runner.py 156] [INFO]: 前往目标 [未知]
[02:42:47.831] [operation.py 306] [INFO]: 指令[ 空洞操作器 ] 节点 画面识别 返回状态 等待
[02:42:48.157] [operation.py 306] [INFO]: 指令[ 邦布商人 ] 节点 检测游戏窗口 返回状态 成功

**Comment by DoctorReid** [comment]
日志看就不是最新版本，先更新代码再试试
