### ISSUE TITLE
[问题反馈] [零号空洞] 不点选项只点选项前面的“2”

### ISSUE THREAD

**Issue by Justice-ocr** [DoctorReid/ZenlessZoneZero-OneDragon#365]
### 问题描述

施工废墟，进入下一层和催债人对话结束会出现

### 问题副本

施工废墟

### 游戏截图

https://github.com/user-attachments/assets/ef78630b-d6ec-45ee-a262-3abdeee35d85

### 你的建议

把对话由识别之后鼠标点击改成点按数字键

**Comment by Justice-ocr** [comment]
字体是细体，分辨率1600：900

**Comment by DoctorReid** [comment]
1. 目前低于 1920*1080 有问题提供不了修复，后续会对低分辨率统一做一个优化，但也保证不了
2. 不会采用按键，因为后续会兼容模拟器
