### ISSUE TITLE
[问题反馈] [通用] [Bug]: 10.27日更新代码版本和运行依赖后，启动提示qt平台插件缺失

### ISSUE THREAD

**Issue by yume-git** [DoctorReid/ZenlessZoneZero-OneDragon#367]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### bug情况描述

10.26日正常使用。10.27日更新代码版本和运行依赖后，点击运行，提示qt平台插件缺失。如图弹窗提示。

### 上传截图

![ba17f0d148e4464568960e8cea6fc818](https://github.com/user-attachments/assets/6aed99ae-3533-4312-817b-6d5551453c6f)

**Comment by DoctorReid** [comment]
两种方案试试

1. 参考 [这个](https://www.bilibili.com/video/BV1Vq4y1X73o?vd_source=01e344680ce2fb5a0bf15b318e702481) 解决
2. 删除 .env 里的所有文件夹，仅保留 __非文件夹__ 的内容，然后重新安装一次

**Comment by DoctorReid** [comment]
有问题再群里反馈吧

**Comment by yume-git** [comment]
方案二成功解决问题


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年10月29日 10:09 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [DoctorReid/ZenlessZoneZero-OneDragon] [问题反馈] [通用] [Bug]: 10.27日更新代码版本和运行依赖后，启动提示qt平台插件缺失 (Issue #367) |

两种方案试试

参考 这个 解决
删除 .env文件夹 里面的所有文件夹，仅保留 非文件夹 的内容，然后重新安装一次
