### ISSUE TITLE
[问题反馈] [通用] 体力刷本陷入死循环

### ISSUE THREAD

**Issue by KZXE-wx** [DoctorReid/ZenlessZoneZero-OneDragon#369]
### 问题描述

1.体力刷本，进去副本之后就会自动打开ESC界面，如图一所示。之后就会在点击“退出战斗”，然后又点击“取消”在图一和图二之间来回跳转卡住。

### 游戏截图

![c24440a6-30df-4934-b794-81ec3eff28ab](https://github.com/user-attachments/assets/920339bc-b250-4693-8f93-e352197d8e01)
![30c6d744-8810-4363-8e0f-7c5f602fae1d](https://github.com/user-attachments/assets/32226594-87c2-4a72-bcbc-6cb1465d4fc0)

### 运行日志
指令[ 体力刷本 ] 节点 实战模拟室 返回状态 未找到 下一步
指令[ 体力刷本 ] 执行失败 返回状态 未找到 下一步
指令[ 一条龙 ] 节点 运行任务 返回状态 下一个
正在加载OCR模型
请先结束其他运行中的功能 再启动
指令[ 活跃度奖励 ] 节点 检测游戏窗口 返回状态 成功
指令[ 打开快捷手册 ] 节点 检测游戏窗口 返回状态 成功
指令[ 打开菜单 ] 节点 检测游戏窗口 返回状态 成功
指令[ 打开菜单 ] 节点 画面识别 返回状态 失败
指令[ 返回大世界 ] 节点 检测游戏窗口 返回状态 成功
指令[ 返回大世界 ] 节点 画面识别 返回状态 重试
指令[ 返回大世界 ] 节点 画面识别 返回状态 重试
指令[ 返回大世界 ] 节点 画面识别 返回状态 重试
指令[ 返回大世界 ] 节点 画面识别 返回状态 重试
指令[ 返回大世界 ] 节点 画面识别 返回状态 重试
指令[ 返回大世界 ] 节点 画面识别 返回状态 重试
指令[ 返回大世界 ] 节点 画面识别 返回状态 重试
指令[ 返回大世界 ] 节点 画面识别 返回状态 重试
指令[ 返回大世界 ] 节点 画面识别 返回状态 重试
指令[ 返回大世界 ] 节点 画面识别 返回状态 重试
指令[ 返回大世界 ] 节点 画面识别 返回状态 重试
指令[ 返回大世界 ] 节点 画面识别 返回状态 重试
指令[ 返回大世界 ] 节点 画面识别 返回状态 重试
指令[ 返回大世界 ] 节点 画面识别 返回状态 等待
指令[ 返回大世界 ] 节点 画面识别 返回状态 重试
指令[ 返回大世界 ] 节点 画面识别 返回状态 等待
指令[ 返回大世界 ] 节点 画面识别 返回状态 重试
指令[ 返回大世界 ] 节点 画面识别 返回状态 等待
指令[ 返回大世界 ] 节点 画面识别 返回状态 重试
指令[ 返回大世界 ] 节点 画面识别 返回状态 等待
指令[ 返回大世界 ] 节点 画面识别 返回状态 重试

[log.txt](https://github.com/user-attachments/files/17560186/log.txt)

_No response_

**Comment by KZXE-wx** [comment]
![Uploading 30c6d744-8810-4363-8e0f-7c5f602fae1d.png…]()

**Comment by Leapiny** [comment]
与我这边配置队伍与战斗模组不对时的现象有点像。建议重新配置一下编队、自动战斗模板，确认保存好，再重新运行试试。因为恶名狩猎现在保存不了编队设置，我就遇到一直反复取消的情况。

**Comment by DoctorReid** [comment]
日志看不出来为什么，需要录个视频看看

**Comment by cvbvbbv** [comment]
发生这种情况的话关闭脚本，看看编队那边掉没掉

**Comment by cvbvbbv** [comment]
不知道为什么，每次打开脚本的时候设置的编队都会消失

**Comment by KZXE-wx** [comment]
> 日志看不出来为什么，需要录个视频看看
你好，就如视频里的情况一样。

https://github.com/user-attachments/assets/befbefdf-522d-4ac6-8226-d36e2547cea8

**Comment by DoctorReid** [comment]
@KZXE-wx 日志再上传一下

**Comment by xiaobgyhgukjhyutytydr** [comment]
所以怎么解决这个问题

**Comment by xiaobgyhgukjhyutytydr** [comment]
指令[ 打开菜单 ] 节点 画面识别 返回状态 信息
指令[ 打开菜单 ] 节点 点击菜单 返回状态 成功
指令[ 打开菜单 ] 节点 画面识别 返回状态 成功
指令[ 打开菜单 ] 执行成功 返回状态 成功
指令[ 打开快捷手册 ] 节点 打开菜单 返回状态 成功
指令[ 打开快捷手册 ] 节点 点击更多 返回状态 快捷手册
指令[ 打开快捷手册 ] 执行成功 返回状态 快捷手册
指令[ 传送 快捷手册 训练-定期清剿-高塔与巨炮 ] 节点 快捷手册 返回状态 快捷手册
指令[ 快捷手册 选择Tab 训练 ] 节点 检测游戏窗口 返回状态 成功
指令[ 快捷手册 选择Tab 训练 ] 节点 选择TAB 返回状态 成功
指令[ 快捷手册 选择Tab 训练 ] 执行成功 返回状态 成功
指令[ 传送 快捷手册 训练-定期清剿-高塔与巨炮 ] 节点 选择TAB 返回状态 成功
指令[ 快捷手册 选择分类 定期清剿 ] 节点 检测游戏窗口 返回状态 成功
指令[ 快捷手册 选择分类 定期清剿 ] 节点 选择分类 返回状态 成功
指令[ 快捷手册 选择分类 定期清剿 ] 执行成功 返回状态 成功
指令[ 传送 快捷手册 训练-定期清剿-高塔与巨炮 ] 节点 选择分类 返回状态 成功
指令[ 快捷手册 选择副本类型 高塔与巨炮 ] 节点 检测游戏窗口 返回状态 成功
指令[ 快捷手册 选择副本类型 高塔与巨炮 ] 节点 选择副本 返回状态 找不到 高塔与巨炮
指令[ 快捷手册 选择副本类型 高塔与巨炮 ] 节点 选择副本 返回状态 成功
指令[ 快捷手册 选择副本类型 高塔与巨炮 ] 节点 确认 返回状态 传送确认
指令[ 快捷手册 选择副本类型 高塔与巨炮 ] 执行成功 返回状态 传送确认
指令[ 传送 快捷手册 训练-定期清剿-高塔与巨炮 ] 节点 选择副本分类 返回状态 传送确认
指令[ 传送 快捷手册 训练-定期清剿-高塔与巨炮 ] 执行成功 返回状态 传送确认
指令[ 体力刷本 ] 节点 传送 返回状态 传送确认
指令[ 体力刷本 ] 节点 识别副本分类 返回状态 定期清剿
指令[ 定期清剿 高塔与巨炮 ] 节点 检测游戏窗口 返回状态 成功
指令[ 定期清剿 高塔与巨炮 ] 节点 等待入口加载 返回状态 挑战等级
指令[ 定期清剿 高塔与巨炮 ] 节点 识别电量 返回状态 电量不足
指令[ 定期清剿 高塔与巨炮 ] 执行成功 返回状态 电量不足
指令[ 体力刷本 ] 节点 定期清剿 返回状态 电量不足
指令[ 返回大世界 ] 节点 检测游戏窗口 返回状态 成功
指令[ 返回大世界 ] 节点 画面识别 返回状态 重试

**Comment by xiaobgyhgukjhyutytydr** [comment]
我打开脚本刷，它会显示电量不足，直接退出

**Comment by KZXE-wx** [comment]
> @KZXE-wx 日志再上传一下

[log.txt](https://github.com/user-attachments/files/17598203/log.txt)

**Comment by DoctorReid** [comment]
大概猜到一个原因，今晚试试修复

**Comment by DoctorReid** [comment]
应该修复了 试试
