### ISSUE TITLE
[问题反馈] [通用] 式舆防卫战点击运行无反应

### ISSUE THREAD

**Issue by ttezy** [DoctorReid/ZenlessZoneZero-OneDragon#375]
### 问题描述

队伍配置好了，但是点击运行没反应。看了一下log好像也没有东西。
![image](https://github.com/user-attachments/assets/7dff6171-61a8-456f-b2e5-514eba494aef)
![image](https://github.com/user-attachments/assets/cb0d92e1-95d2-403d-beaa-05f37f1afa9b)

**Comment by DeeJay0921** [comment]
+1 同样出现该问题

**Comment by DoctorReid** [comment]
修复了
