### ISSUE TITLE
[问题反馈] [通用] 

### ISSUE THREAD

**Issue by xiaobgyhgukjhyutytydr** [DoctorReid/ZenlessZoneZero-OneDragon#377]
### 问题描述

体力刷本直接退出，刷的时候点进去，就直接退了，日志上说是电量（体力不足），可是我体力明明够

### 游戏截图

Uploading Video_1730474158617.mp4…

### 运行日志

[日志.log](https://github.com/user-attachments/files/17601072/default.log)

**Comment by DoctorReid** [comment]
F11截图上传

字体选细体

**Comment by xiaobgyhgukjhyutytydr** [comment]
https://github.com/user-attachments/assets/ff93c785-137c-461a-b6f0-2a6532df584b

[log.txt](https://github.com/user-attachments/files/17605709/log.txt)
@DoctorReid 还是不行这是日志和视频

**Comment by DoctorReid** [comment]
1000体力太多了

F11上传截图我再修复

**Comment by xiaobgyhgukjhyutytydr** [comment]
![Image_1730558660125](https://github.com/user-attachments/assets/c43e6351-ad1d-455a-b551-000275bea5ba)
@DoctorReid

**Comment by DoctorReid** [comment]
脚本F11截图后上传
