### ISSUE TITLE
[开发咨询] [通用] 代码中启动指定操作

### ISSUE THREAD

**Issue by MomentDerek** [DoctorReid/ZenlessZoneZero-OneDragon#378]
### 问题描述

大佬好，想问问怎么直接启动一个操作？比如在这里点击后走登出+登入的操作

好像没看到对应的例子和文档

![20e03831e86f4944d558a6a2d8f40062](https://github.com/user-attachments/assets/331df699-d620-43fd-946d-78447b68eda2)
![b93ea046f4d8735dcbb6897b8c7c004a](https://github.com/user-attachments/assets/54eecf5d-6953-44b9-94bf-3deb8ace9423)

**Comment by yokuminto** [comment]
应该也是用节点操作的。你可以查阅下节点操作相关内容，我在主页写了一个简单的启动游戏节点。

**Comment by DoctorReid** [comment]
SwitchAccount 这个指令直接包含了
