### ISSUE TITLE
[问题反馈] [零号空洞] 重复进入商店，疑似可能和促销交易/风险交易有关，已附带视频

### ISSUE THREAD

**Issue by f59375543** [DoctorReid/ZenlessZoneZero-OneDragon#382]
### 问题描述

不断重复进入商店

### 问题副本

旧都列车第三难度

### 游戏截图/录屏

BUG录屏

https://wwsc.lanzouo.com/itNa72e6v6di

### 运行日志

[log.txt](https://github.com/user-attachments/files/17612853/log.txt)

**Comment by yokuminto** [comment]
同步仓库后再试试，前天有个相关修复
如果还是有问题，可以附上新的视频

**Comment by f59375543** [comment]
> 同步仓库后再试试，前天有个相关修复 如果还是有问题，可以附上新的视频


昨天已经同步过了

![20241104104230](https://github.com/user-attachments/assets/9f79fb0c-e374-4352-9c64-4b36780c7771)

**Comment by XDMrSmile** [comment]
> 同步仓库后再试试，前天有个相关修复 如果还是有问题，可以附上新的视频

我看日志的话，主要是卡在“随机一步”上，应该已经更新了包含 #373 的代码，不过我这更新后并没有复现他的情况。

[04:53:57.321] [hollow_context.py 175] [INFO]: 优先级 [随机一步]
[04:53:57.321] [hollow_runner.py 162] [INFO]: 前往目标: [空白已通行] 当前移动: [未知]
[04:53:58.445] [operation.py 306] [INFO]: 指令[ 空洞操作器 ] 节点 画面识别 返回状态 等待
[04:53:58.734] [hollow_runner.py 134] [INFO]: 匹配特殊事件 [欢迎本店欢迎]
[04:53:58.734] [operation.py 306] [INFO]: 指令[ 邦布商人 ] 节点 检测游戏窗口 返回状态 成功

**Comment by f59375543** [comment]
> > 同步仓库后再试试，前天有个相关修复 如果还是有问题，可以附上新的视频
> 
> 我看日志的话，主要是卡在“随机一步”上，应该已经更新了包含 #373 的代码，不过我这更新后并没有复现他的情况。
> 
> [04:53:57.321] [hollow_context.py 175] [INFO]: 优先级 [随机一步] [04:53:57.321] [hollow_runner.py 162] [INFO]: 前往目标: [空白已通行] 当前移动: [未知] [04:53:58.445] [operation.py 306] [INFO]: 指令[ 空洞操作器 ] 节点 画面识别 返回状态 等待 [04:53:58.734] [hollow_runner.py 134] [INFO]: 匹配特殊事件 [欢迎本店欢迎] [04:53:58.734] [operation.py 306] [INFO]: 指令[ 邦布商人 ] 节点 检测游戏窗口 返回状态 成功-----------谷歌翻译-----------[04:53:57.321] [hollow_context.py 175] [INFO]: 优先级 [随机一步][04:53:57.321] [hollow_runner.py 162] [INFO]: 前往目标: [空白已通行] 当前移动: [未知][04:53:58.445] [operation.py 306] [INFO]: 指令[ 空洞操作器 ] 节点 画面识别 返回状态 等待[04:53:58.734] [hollow_runner.py 134] [INFO]: 匹配特殊事件 [欢迎本店欢迎][04:53:58.734] [operation.py 306] [INFO]: 指令[ 邦布商人 ] 节点 检测游戏窗口 返回状态 成功


我重新复现出了一个更奇葩的情况，那就是由于随机点击移动，然而右侧有怪，不直接点到怪就不会触发战斗，导致无限撞墙

已附带视频

https://wwsc.lanzouo.com/ieku22ebbkih

**Comment by XDMrSmile** [comment]
> > > 同步仓库后再试试，前天有个相关修复 如果还是有问题，可以附上新的视频
> > 
> > 
> > 我看日志的话，主要是卡在“随机一步”上，应该已经更新了包含 #373 的代码，不过我这更新后并没有复现他的情况。
> > [04:53:57.321] [hollow_context.py 175] [INFO]: 优先级 [随机一步] [04:53:57.321] [hollow_runner.py 162] [INFO]: 前往目标: [空白已通行] 当前移动: [未知] [04:53:58.445] [operation.py 306] [INFO]: 指令[ 空洞操作器 ] 节点 画面识别 返回状态 等待 [04:53:58.734] [hollow_runner.py 134] [INFO]: 匹配特殊事件 [欢迎本店欢迎] [04:53:58.734] [operation.py 306] [INFO]: 指令[ 邦布商人 ] 节点 检测游戏窗口 返回状态 成功-----------谷歌翻译-----------[04:53:57.321] [hollow_context.py 175] [INFO]: 优先级 [随机一步][04:53:57.321] [hollow_runner.py 162] [INFO]: 前往目标: [空白已通行] 当前移动: [未知][04:53:58.445] [operation.py 306] [INFO]: 指令[ 空洞操作器 ] 节点 画面识别 返回状态 等待[04:53:58.734] [hollow_runner.py 134] [INFO]: 匹配特殊事件 [欢迎本店欢迎][04:53:58.734] [operation.py 306] [INFO]: 指令[ 邦布商人 ] 节点 检测游戏窗口 返回状态 成功
> 
> 我重新复现出了一个更奇葩的情况，那就是由于随机点击移动，然而右侧有怪，不直接点到怪就不会触发战斗，导致无限撞墙
> 
> 已附带视频
> 
> https://wwsc.lanzouo.com/ieku22ebbkih
> 
> 日志log
> 
> [log.txt](https://github.com/user-attachments/files/17627006/log.txt)

这个我倒是也碰到了，还没录屏，不过你能不能上传视频丢网盘的时候不搞成压缩包？

**Comment by f59375543** [comment]
> > > > 同步仓库后再试试，前天有个相关修复 如果还是有问题，可以附上新的视频
> > > 
> > > 
> > > 我看日志的话，主要是卡在“随机一步”上，应该已经更新了包含 #373 的代码，不过我这更新后并没有复现他的情况。
> > > [04:53:57.321] [hollow_context.py 175] [INFO]: 优先级 [随机一步] [04:53:57.321] [hollow_runner.py 162] [INFO]: 前往目标: [空白已通行] 当前移动: [未知] [04:53:58.445] [operation.py 306] [INFO]: 指令[ 空洞操作器 ] 节点 画面识别 返回状态 等待 [04:53:58.734] [hollow_runner.py 134] [INFO]: 匹配特殊事件 [欢迎本店欢迎] [04:53:58.734] [operation.py 306] [INFO]: 指令[ 邦布商人 ] 节点 检测游戏窗口 返回状态 成功-----------谷歌翻译-----------[04:53:57.321] [hollow_context.py 175] [INFO]: 优先级 [随机一步][04:53:57.321] [hollow_runner.py 162] [INFO]: 前往目标: [空白已通行] 当前移动: [未知][04:53:58.445] [operation.py 306] [INFO]: 指令[ 空洞操作器 ] 节点 画面识别 返回状态 等待[04:53:58.734] [hollow_runner.py 134] [INFO]: 匹配特殊事件 [欢迎本店欢迎][04:53:58.734] [operation.py 306] [INFO]: 指令[ 邦布商人 ] 节点 检测游戏窗口 返回状态 成功
> > 
> > 
> > 我重新复现出了一个更奇葩的情况，那就是由于随机点击移动，然而右侧有怪，不直接点到怪就不会触发战斗，导致无限撞墙
> > 已附带视频
> > https://wwsc.lanzouo.com/ieku22ebbkih
> > 日志log
> > [log.txt](https://github.com/user-attachments/files/17627006/log.txt)
> 
> 这个我倒是也碰到了，还没录屏，不过你能不能上传视频丢网盘的时候不搞成压缩包？

 非常抱歉，蓝奏云只能上传压缩包，无法直接上传视频

**Comment by XDMrSmile** [comment]
其他网盘，我都是压制直接传github，像 #373 的视频一样

**Comment by f59375543** [comment]
> 其他网盘，我都是压制直接传github，像 #373 的视频一样

好，我以后压缩视频

**Comment by XDMrSmile** [comment]
问题描述：#373 修复重复进入商店后小概率出现的事件，一样的地图。

问题副本：零号空洞-旧都列车·内部

游戏截图/录屏：

录屏：https://github.com/user-attachments/assets/a16838bf-f315-4f08-8c88-08a6e6586638

![_1730788355742](https://github.com/user-attachments/assets/7054a9e9-0008-41bf-b8d8-3f1fd92626fb)

运行日志：

[14:28:03.123] [hollow_context.py 161] [INFO]: 优先级 [终点]
[14:28:03.123] [hollow_runner.py 171] [INFO]: 前往目标: [守门人] 当前移动: [侵蚀]
[14:28:04.256] [operation.py 306] [INFO]: 指令[ 空洞操作器 ] 节点 画面识别 返回状态 等待
[14:28:07.696] [hollow_context.py 122] [INFO]: 优先级 [一步]
[14:28:07.696] [hollow_runner.py 171] [INFO]: 前往目标: [扭蛋机] 当前移动: [扭蛋机]
[14:28:08.815] [operation.py 306] [INFO]: 指令[ 空洞操作器 ] 节点 画面识别 返回状态 等待
[14:28:09.234] [hollow_context.py 161] [INFO]: 优先级 [终点]
[14:28:09.234] [hollow_runner.py 171] [INFO]: 前往目标: [守门人] 当前移动: [扭蛋机]
[14:28:10.348] [operation.py 306] [INFO]: 指令[ 空洞操作器 ] 节点 画面识别 返回状态 等待
……

你的建议：尝试识别循环并脱困，可以再次随机一步，像视频末尾突然出现的弹框，重新随机一步后恢复正常运行了。

**Comment by f59375543** [comment]
> 问题描述：#373 修复重复进入商店后小概率出现的事件，一样的地图。
> 
> 问题副本：零号空洞-旧都列车·内部
> 
> 游戏截图/录屏：
> 
> 录屏：https://github.com/user-attachments/assets/a16838bf-f315-4f08-8c88-08a6e6586638
> 
> ![_1730788355742](https://private-user-images.githubusercontent.com/103902265/383159229-7054a9e9-0008-41bf-b8d8-3f1fd92626fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MTQ0MzUsIm5iZiI6MTczMDgxNDEzNSwicGF0aCI6Ii8xMDM5MDIyNjUvMzgzMTU5MjI5LTcwNTRhOWU5LTAwMDgtNDFiZi1iOGQ4LTNmMWZkOTI2MjZmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQxMzQyMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMWYwODAwYmJhZTFjODgzYWRjNjBkNWE2MzhiMjMyNjRkZTVhZWU3ZWJiYTU1OWE4ZmFhM2YzYzE0ZWQzZWU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GaNE2Alj7aIDQyOa50bdhigwqoRgnr50_YgDZFYUayQ)
> 
> 运行日志：
> 
> [14:28:03.123] [hollow_context.py 161] [INFO]: 优先级 [终点] [14:28:03.123] [hollow_runner.py 171] [INFO]: 前往目标: [守门人] 当前移动: [侵蚀] [14:28:04.256] [operation.py 306] [INFO]: 指令[ 空洞操作器 ] 节点 画面识别 返回状态 等待 [14:28:07.696] [hollow_context.py 122] [INFO]: 优先级 [一步] [14:28:07.696] [hollow_runner.py 171] [INFO]: 前往目标: [扭蛋机] 当前移动: [扭蛋机] [14:28:08.815] [operation.py 306] [INFO]: 指令[ 空洞操作器 ] 节点 画面识别 返回状态 等待 [14:28:09.234] [hollow_context.py 161] [INFO]: 优先级 [终点] [14:28:09.234] [hollow_runner.py 171] [INFO]: 前往目标: [守门人] 当前移动: [扭蛋机] [14:28:10.348] [operation.py 306] [INFO]: 指令[ 空洞操作器 ] 节点 画面识别 返回状态 等待 ……-----------谷歌翻译-----------[14:28:03.123] [hollow_context.py 161] [INFO]: 优先级 [终点][14:28:03.123] [hollow_runner.py 171] [INFO]: 前往目标: [守门人] 当前移动: [侵蚀][14:28:04.256] [operation.py 306] [INFO]: 指令[ 空洞操作器 ] 节点 画面识别 返回状态 等待[14:28:07.696] [hollow_context.py 122] [INFO]: 优先级 [一步][14:28:07.696] [hollow_runner.py 171] [INFO]: 前往目标: [扭蛋机] 当前移动: [扭蛋机][14:28:08.815] [operation.py 306] [INFO]: 指令[ 空洞操作器 ] 节点 画面识别 返回状态 等待[14:28:09.234] [hollow_context.py 161] [INFO]: 优先级 [终点][14:28:09.234] [hollow_runner.py 171] [INFO]: 前往目标: [守门人] 当前移动: [扭蛋机][14:28:10.348] [operation.py 306] [INFO]: 指令[ 空洞操作器 ] 节点 画面识别 返回状态 等待……
> 
> 你的建议：尝试识别循环并脱困，可以再次随机一步，像视频末尾突然出现的弹框，重新随机一步后恢复正常运行了。

好的，我再试试

**Comment by XDMrSmile** [comment]
这个是给作者写的，重复的问题我就写在这里了。不过你也可以尝试写代码修（狗头）@f59375543

**Comment by DoctorReid** [comment]
已修复
