### ISSUE TITLE
[问题反馈] [零号空洞] 

### ISSUE THREAD

**Issue by jirlya** [DoctorReid/ZenlessZoneZero-OneDragon#383]
### 问题描述

零号空洞不运行，该设置的都有设置，重置之后也是一样。

### 问题副本

零号空洞门口

### 游戏截图/录屏

![27968ABF9A594969A0FFDB3600F3671E](https://github.com/user-attachments/assets/a006dd55-1cb8-4e74-9ffc-4a1ba60420d8)
![CE0CD818B471F27DD020A34E68958F3F](https://github.com/user-attachments/assets/0d562b3d-42f1-4814-94af-5270ca475b15)

### 你的建议

指令[ 零号空洞 ] 节点 初始画面识别 返回状态 未找到 信息
指令[ 零号空洞 ] 节点 初始画面识别 返回状态 信息
指令[ 传送 快捷手册 挑战-零号空洞-资质考核 ] 节点 检测游戏窗口 返回状态 成功
指令[ 打开快捷手册 ] 节点 检测游戏窗口 返回状态 成功
指令[ 打开菜单 ] 节点 检测游戏窗口 返回状态 成功
指令[ 打开菜单 ] 节点 画面识别 返回状态 信息
指令[ 打开菜单 ] 节点 点击菜单 返回状态 成功
指令[ 打开菜单 ] 节点 画面识别 返回状态 成功
指令[ 打开菜单 ] 执行成功 返回状态 成功
指令[ 打开快捷手册 ] 节点 打开菜单 返回状态 成功
指令[ 打开快捷手册 ] 节点 点击更多 返回状态 快捷手册
指令[ 打开快捷手册 ] 执行成功 返回状态 快捷手册
指令[ 传送 快捷手册 挑战-零号空洞-资质考核 ] 节点 快捷手册 返回状态 快捷手册
指令[ 快捷手册 选择Tab 挑战 ] 节点 检测游戏窗口 返回状态 成功
指令[ 快捷手册 选择Tab 挑战 ] 节点 选择TAB 返回状态 成功
指令[ 快捷手册 选择Tab 挑战 ] 执行成功 返回状态 成功
指令[ 传送 快捷手册 挑战-零号空洞-资质考核 ] 节点 选择TAB 返回状态 成功
指令[ 快捷手册 选择分类 零号空洞 ] 节点 检测游戏窗口 返回状态 成功
指令[ 快捷手册 选择分类 零号空洞 ] 节点 选择分类 返回状态 成功
指令[ 快捷手册 选择分类 零号空洞 ] 执行成功 返回状态 成功
指令[ 传送 快捷手册 挑战-零号空洞-资质考核 ] 节点 选择分类 返回状态 成功
指令[ 快捷手册 选择副本类型 资质考核 ] 节点 检测游戏窗口 返回状态 成功
指令[ 快捷手册 选择副本类型 资质考核 ] 节点 选择副本 返回状态 成功
指令[ 快捷手册 选择副本类型 资质考核 ] 节点 确认 返回状态 传送确认
指令[ 快捷手册 选择副本类型 资质考核 ] 执行成功 返回状态 传送确认
指令[ 传送 快捷手册 挑战-零号空洞-资质考核 ] 节点 选择副本分类 返回状态 传送确认
指令[ 传送 快捷手册 挑战-零号空洞-资质考核 ] 执行成功 返回状态 传送确认
指令[ 零号空洞 ] 节点 传送 返回状态 传送确认
指令[ 零号空洞 ] 节点 等待入口加载 返回状态 街区
指令[ 零号空洞 ] 节点 选择副本类型 返回状态 已完成基本次数
指令[ 零号空洞 ] 节点 完成后等待加载 返回状态 街区
指令[ 零号空洞 ] 节点 点击奖励入口 返回状态 奖励入口
指令[ 零号空洞 ] 节点 悬赏委托 返回状态 悬赏委托
指令[ 零号空洞 ] 节点 领取奖励 返回状态 全部领取
指令[ 返回大世界 ] 节点 检测游戏窗口 返回状态 成功
指令[ 返回大世界 ] 节点 画面识别 返回状态 重试

**Comment by yokuminto** [comment]
改成每周基础2，每天35，再试试

**Comment by jirlya** [comment]
> 改成每周基础2，每天35，再试试

可以了，能正常运行了

**Comment by DoctorReid** [comment]
每天次数不能是0，这是基础的
