### ISSUE TITLE
[问题反馈] [通用] 

### ISSUE THREAD

**Issue by 17623011046** [DoctorReid/ZenlessZoneZero-OneDragon#384]
### 问题描述

虚拟手柄第一次安装的时候弹出的驱动安装页面当时给关闭了，后面安装不弹了，安装成功了也不能使用，自动闪避选了xbox手柄运行没反应（选无手柄可以正常使用），删了整个一条龙文件夹重新安装也无效，不弹驱动安装页面，这种怎么解决？

**Comment by DoctorReid** [comment]
试试下载安装 [这个](https://github.com/nefarius/ViGEmBus/releases/download/v1.22.0/ViGEmBus_1.22.0_x64_x86_arm64.exe)
