### ISSUE TITLE
[问题反馈] [通用] 

### ISSUE THREAD

**Issue by tangqing2004** [DoctorReid/ZenlessZoneZero-OneDragon#386]
### 问题描述

游戏的反作弊无法运行。发生在windows计划任务执行启动one_dragon.bat 或者 OneDragon Scheduler.exe后，无法启动，且导致截图所展示问题。重启后可以启动游戏，也可以直接通过one_dragon.bat 或者 OneDragon Scheduler.exe启动，但无法通过windows计划任务启动，尝试后又会造成报错。

### 游戏截图

![5fda225dad11cd0ae33c0aeca8a295fd](https://github.com/user-attachments/assets/9e351084-adf7-4c69-8b2f-bdc945299525)
![c0ecd19b472dc8e8bdc15e2cd749f6a8](https://github.com/user-attachments/assets/136c4a14-2f15-407b-bd22-ac16ecd84fa8)

### 运行日志

[log.txt](https://github.com/user-attachments/files/17615377/log.txt)

**Comment by DoctorReid** [comment]
脚本不会干涉游戏怎么运行的，只要平时能用脚本唤起游戏exe，那就是没问题的。

我猜测是你计划任务的运行权限比较低导致加载dll失败，你可以尝试使用计划任务打开游戏，应该也打开不了
