### ISSUE TITLE
安装出问题，说是找不到文件，详情如图

### ISSUE THREAD

**Issue by Eternal-Winner** [DoctorReid/ZenlessZoneZero-OneDragon#388]
### 问题描述

一键安装很多次都这样，看运行的报错吧，底下

### 运行日志

检测当前代码分支
获取依赖文件的最后修改时间
C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\venv\scripts\python.exe -c import sys; print(getattr(sys, 'base_prefix', sys.prefix) != sys.prefix)
C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\PortableGit\cmd\git.exe branch --show-current
检测当前git版本
C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\PortableGit\cmd\git.exe log -1 --pretty=format:"%ai -- requirements-prod.txt
C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\PortableGit\cmd\git.exe --version
True
检测当前python版本
C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\venv\scripts\python.exe --version
git version 2.45.2.windows.1
main
2024-10-26 14:20:14 +0800
获取远程代码
C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\PortableGit\cmd\git.exe fetch origin main
Python 3.11.9
From https://gitee.com/doctorreid/ZenlessZoneZero-OneDragon
* branch main -> FETCH_HEAD
获取远程代码成功
检测当前代码是否最新
C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\PortableGit\cmd\git.exe diff --name-only HEAD origin/main
一键安装 开始
开始安装 git
检测当前git版本
C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\PortableGit\cmd\git.exe --version
git version 2.45.2.windows.1
已经安装了git
一键安装 开始下一个
.git目录 C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.git
C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\PortableGit\cmd\git.exe config --global --add safe.directory C:/D/Game/ZZZ/ZenlessZoneZero-OneDragon
检测当前git版本
C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\PortableGit\cmd\git.exe --version
git version 2.45.2.windows.1
核对当前仓库
C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\PortableGit\cmd\git.exe config --get remote.origin.url
https://gitee.com/doctorreid/ZenlessZoneZero-OneDragon.git
获取远程代码
获取远程代码
C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\PortableGit\cmd\git.exe fetch origin main
From https://gitee.com/doctorreid/ZenlessZoneZero-OneDragon
* branch main -> FETCH_HEAD
获取远程代码成功
检测当前代码是否有修改
C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\PortableGit\cmd\git.exe status
On branch main
Your branch is up to date with 'origin/main'.
nothing to commit, working tree clean
检测当前代码分支
C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\PortableGit\cmd\git.exe branch --show-current
main
C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\PortableGit\cmd\git.exe pull --rebase
Already up to date.
一键安装 开始下一个
获取依赖文件的最后修改时间
C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\PortableGit\cmd\git.exe log -1 --pretty=format:"%ai -- requirements-prod.txt
检测当前代码分支
C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\PortableGit\cmd\git.exe branch --show-current
main
获取远程代码
C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\PortableGit\cmd\git.exe fetch origin main
2024-10-26 14:20:14 +0800
From https://gitee.com/doctorreid/ZenlessZoneZero-OneDragon
* branch main -> FETCH_HEAD
获取远程代码成功
检测当前代码是否最新
C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\PortableGit\cmd\git.exe diff --name-only HEAD origin/main
检测当前python版本
开始安装 python
开始解压 python-3.11.9-embed-amd64.zip
解压成功
检测当前pip版本
C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\python\python.exe -m pip --version
C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\python\python.exe: No module named pip
开始安装 pip
C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\python\python.exe C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\get-pip.py --index-url https://pypi.tuna.tsinghua.edu.cn/simple
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting pip
Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ef/7d/500c9ad20238fcfcb4cb9243eede163594d7020ce87bd9610c9e02771876/pip-24.3.1-py3-none-any.whl (1.8 MB)
Collecting setuptools
Using cached https://pypi.tuna.tsinghua.edu.cn/packages/90/12/282ee9bce8b58130cb762fbc9beabd531549952cac11fc56add11dcb7ea0/setuptools-75.3.0-py3-none-any.whl (1.3 MB)
Collecting wheel
Using cached https://pypi.tuna.tsinghua.edu.cn/packages/1b/d1/9babe2ccaecff775992753d8686970b1e2755d21c8a63be73aba7a4e7d77/wheel-0.44.0-py3-none-any.whl (67 kB)
Installing collected packages: wheel, setuptools, pip
WARNING: The script wheel.exe is installed in 'C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\python\Scripts' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
WARNING: The scripts pip.exe, pip3.11.exe and pip3.exe are installed in 'C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\python\Scripts' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-24.3.1 setuptools-75.3.0 wheel-0.44.0
安装pip成功
C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\python\python.exe -m pip install virtualenv --index-url https://pypi.tuna.tsinghua.edu.cn/simple
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting virtualenv
Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ae/92/78324ff89391e00c8f4cf6b8526c41c6ef36b4ea2d2c132250b1a6fc2b8d/virtualenv-20.27.1-py3-none-any.whl (3.1 MB)
Collecting distlib=0.3.7 (from virtualenv)
Using cached https://pypi.tuna.tsinghua.edu.cn/packages/91/a1/cf2472db20f7ce4a6be1253a81cfdf85ad9c7885ffbed7047fb72c24cf87/distlib-0.3.9-py2.py3-none-any.whl (468 kB)
Collecting filelock=3.12.2 (from virtualenv)
Using cached https://pypi.tuna.tsinghua.edu.cn/packages/b9/f8/feced7779d755758a52d1f6635d990b8d98dc0a29fa568bbe0625f18fdf3/filelock-3.16.1-py3-none-any.whl (16 kB)
Collecting platformdirs=3.9.1 (from virtualenv)
Using cached https://pypi.tuna.tsinghua.edu.cn/packages/3c/a6/bc1012356d8ece4d66dd75c4b9fc6c1f6650ddd5991e421177d9f8f671be/platformdirs-4.3.6-py3-none-any.whl (18 kB)
Installing collected packages: distlib, platformdirs, filelock, virtualenv
WARNING: The script virtualenv.exe is installed in 'C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\python\Scripts' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed distlib-0.3.9 filelock-3.16.1 platformdirs-4.3.6 virtualenv-20.27.1
安装virtualenv成功
C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\python\python.exe -m virtualenv C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\venv --always-copy
created virtual environment CPython3.11.9.final.0-64 in 2471ms
creator CPython3Windows(dest=C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\venv, clear=False, no_vcs_ignore=False, global=False)
seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\Ada\AppData\Local\pypa\virtualenv)
added seed packages: pip==24.3.1, setuptools==75.2.0, wheel==0.44.0
activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
创建虚拟环境成功
一键安装 开始下一个
C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\venv\scripts\python.exe -m pip install --upgrade pip --index-url https://pypi.tuna.tsinghua.edu.cn/simple
C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\venv\scripts\python.exe -c import sys; print(getattr(sys, 'base_prefix', sys.prefix) != sys.prefix)
True
检测当前python版本
C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\venv\scripts\python.exe --version
Python 3.11.9
Traceback (most recent call last):
File "", line 198, in _run_module_as_main
File "", line 88, in _run_code
File "C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\pip\__main__.py", line 24, in 
sys.exit(_main())
^^^^^^^
File "C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\pip\_internal\cli\main.py", line 65, in main
cmd_name, cmd_args = parse_command(args)
^^^^^^^^^^^^^^^^^^^
File "C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\pip\_internal\cli\main_parser.py", line 79, in parse_command
general_options, args_else = parser.parse_args(args)
^^^^^^^^^^^^^^^^^^^^^^^
File "optparse.py", line 1371, in parse_args
values = self.get_default_values()
^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\pip\_internal\cli\parser.py", line 279, in get_default_values
self.config.load()
File "C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\pip\_internal\configuration.py", line 124, in load
self._load_config_files()
File "C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\pip\_internal\configuration.py", line 246, in _load_config_files
config_files = dict(self.iter_config_files())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\pip\_internal\configuration.py", line 339, in iter_config_files
config_files = get_configuration_files()
^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\pip\_internal\configuration.py", line 70, in get_configuration_files
os.path.join(path, CONFIG_BASENAME) for path in appdirs.site_config_dirs("pip")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\pip\_internal\utils\appdirs.py", line 47, in site_config_dirs
dirval = _appdirs.site_config_dir(appname, appauthor=False, multipath=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 142, in site_config_dir
).site_config_dir
^^^^^^^^^^^^^^^
File "C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\pip\_vendor\platformdirs\windows.py", line 67, in site_config_dir
return self.site_data_dir
^^^^^^^^^^^^^^^^^^
File "C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\pip\_vendor\platformdirs\windows.py", line 56, in site_data_dir
path = os.path.normpath(get_win_folder("CSIDL_COMMON_APPDATA"))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\D\Game\ZZZ\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\pip\_vendor\platformdirs\windows.py", line 209, in get_win_folder_from_registry
directory, _ = winreg.QueryValueEx(key, shell_folder_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] ϵͳҲָļ

**Comment by Konyouth** [comment]
2024-11-07 22:32:07,832 | ERROR | 出现未处理的异常：[WinError 2] 系统找不到指定的文件。

**Comment by shui9527** [comment]
> 2024-11-07 22:32:07,832 | ERROR | 出现未处理的异常：[WinError 2] 系统找不到指定的文件。

一样一样

**Comment by yokuminto** [comment]
安装了conda的请按安装指南安装

**Comment by Espir-Fac** [comment]
+1,一键安装同样的问题

**Comment by DoctorReid** [comment]
参考 [安装运行常见问题](https://one-dragon.org/other/zh/common_qa.html)  1.2

解决方案: (2选1)

- 到windows系统设置的应用中，将旧的python都删掉，然后再安装。
- 参考安装指南，使用自己的anaconda创建环境安装
