### ISSUE TITLE
[问题反馈] [通用] 确认按钮点错位置了

### ISSUE THREAD

**Issue by nano096** [DoctorReid/ZenlessZoneZero-OneDragon#389]
### 问题描述

确认按钮点错位置了

### 游戏截图

![d2f05a3ebbc7eb91376da9f69e03d9d7](https://github.com/user-attachments/assets/42686da0-1bd6-4954-82e3-d7c8d3d1c9c2)

**Comment by nano096** [comment]
目前点的是取消 不是确认

**Comment by DoctorReid** [comment]
不支持在副本内开始脚本
