### ISSUE TITLE
[问题反馈] [通用] 

### ISSUE THREAD

**Issue by moonyue14** [DoctorReid/ZenlessZoneZero-OneDragon#391]
### 问题描述

运行每周行程或活跃奖励时鼠标停在左上角，代码已同步

### 游戏截图

![image](https://github.com/user-attachments/assets/02cb8a76-6480-4bd7-9bc2-cbb5f27cb429)
![image](https://github.com/user-attachments/assets/9ac26a23-9f28-4f3c-b9ff-e4ff019e7f9d)
![image](https://github.com/user-attachments/assets/577f0b40-56e5-42bc-aa8f-1159e133d2a5)

### 你的建议

疑似是1.3版本改变F2界面布局后无法识别

**Comment by DoctorReid** [comment]
同 #398  晚些修复
