### ISSUE TITLE
[问题反馈] [通用] 

### ISSUE THREAD

**Issue by 979475910** [DoctorReid/ZenlessZoneZero-OneDragon#393]
### 问题描述

不会自动领取活跃度奖励

### 游戏截图

![8b8b1b04-3796-4bb0-b927-f404bc77a2a8](https://github.com/user-attachments/assets/ed205a9a-eb72-4902-a3fa-f49bb76366ac)

**Comment by Qinolion** [comment]
指令[ 返回大世界 ] 节点 画面识别 返回状态 重试
指令[ 返回大世界 ] 节点 画面识别 返回状态 重试
指令[ 返回大世界 ] 节点 画面识别 返回状态 重试

**Comment by Qinolion** [comment]
我也有这个问题

**Comment by DoctorReid** [comment]
同 #398 晚些修复
