### ISSUE TITLE
[问题反馈] [通用] 专业挑战室滑动问题+每日任务奖励不领取

### ISSUE THREAD

**Issue by SuperSB** [DoctorReid/ZenlessZoneZero-OneDragon#395]
### 问题描述

看视频
1. 专业挑战室，寻找指定挑战，滑动问题
2. 每日任务奖励没有领取

https://github.com/user-attachments/assets/37343561-3e0f-436b-8c33-edcd819fccad

### 运行日志

[log.txt](https://github.com/user-attachments/files/17663548/log.txt)

**Comment by SuperSB** [comment]
还有恶民狩猎也是一样的问题

**Comment by Leapiny** [comment]
同样的问题，体力用完以后，会卡在领取日常奖励的页面，日志报错和上面一样：
[09:12:48.759] [onnx_ocr_matcher.py 25] [INFO]: 正在加载OCR模型
[09:12:48.759] [one_dragon_context.py 95] [ERROR]: 请先结束其他运行中的功能 再启动

**Comment by DoctorReid** [comment]
已修复
