### ISSUE TITLE
[问题反馈] [零号空洞] 1.3版本以后不能正常进入空洞

### ISSUE THREAD

**Issue by 1476498244** [DoctorReid/ZenlessZoneZero-OneDragon#397]
### 问题描述

游戏更新到1.3以后无法正常进入空洞

### 问题副本

游戏更新到1.3以后无法正常进入空洞

### 游戏截图/录屏

https://github.com/user-attachments/assets/08100ce3-3565-4b58-a682-f674638e81bd

**Comment by DoctorReid** [comment]
日志
