### ISSUE TITLE
[问题反馈] [战斗助手] [低优先级] 简配队的攻击欲望很低

### ISSUE THREAD

**Issue by SuperSB** [DoctorReid/ZenlessZoneZero-OneDragon#400]
### 使用配置

https://github.com/user-attachments/assets/257536b9-4552-4fd6-80e7-fe1ca65f6c56

### 问题描述

简配队战斗意愿低

### 问题副本

无

### 游戏截图

无

### 运行日志

无

### 你的建议

低优先级吧，我可以换其他配队

**Comment by SuperSB** [comment]
是不是应该多加些普攻的动作

**Comment by DoctorReid** [comment]
群里找战斗配置的作者解决

**Comment by lavender7410** [comment]
> 群里找战斗配置的作者解决

請問為何不用Discord呢 哥們
