### ISSUE TITLE
[问题反馈] [通用] 

### ISSUE THREAD

**Issue by XJFN** [DoctorReid/ZenlessZoneZero-OneDragon#401]
### 问题描述

一条龙中体力刷本无法进行，一直卡在退出战斗页面反复点击。进入战斗页面直接点击左上角暂停。

### 游戏截图

https://github.com/user-attachments/assets/1d3b6448-dd5c-41a0-a3f6-37541ac2560f

**Comment by DoctorReid** [comment]
不能在副本战斗画面开始脚本
