### ISSUE TITLE
[问题反馈] [零号空洞] 出现了新的卡商店情况

### ISSUE THREAD

**Issue by f59375543** [DoctorReid/ZenlessZoneZero-OneDragon#406]
### 问题描述

现在对付卡商店的策略是自动前往右下角的格子，但是假如右下角也是商店，又会死循环卡住

### 问题副本

旧都列车-内部

### 游戏截图/录屏

![1](https://github.com/user-attachments/assets/ca56b35a-e5cc-4d57-a006-ed866c9ba87c)
![2](https://github.com/user-attachments/assets/9bb05f09-fa0f-4cdf-8659-0990e1a7a779)

### 运行日志

[log.txt](https://github.com/user-attachments/files/17694120/log.txt)

### 你的建议

旧都列车疑似每个格子都可能刷出商店

**Comment by DoctorReid** [comment]
视频

**Comment by DoctorReid** [comment]
已修复
