### ISSUE TITLE
[问题反馈] [零号空洞] 老問題

### ISSUE THREAD

**Issue by lavender7410** [DoctorReid/ZenlessZoneZero-OneDragon#409]
### 问题描述

腳本使用艾蓮隊伍 蒼角又變成自動選取1號位
自動戰鬥反應遲鈍 一直吃傷害

### 问题副本

舊都列車核心

**Comment by DoctorReid** [comment]
1. 1号苍角 2号艾莲 这是没有问题的，自己想想为什么
2. 自动战斗配置问题在群里找对应作者
