### ISSUE TITLE
[问题反馈] [零号空洞] 

### ISSUE THREAD

**Issue by Hazard804** [DoctorReid/ZenlessZoneZero-OneDragon#410]
### 问题描述

问题描述：零号空洞加载动画化结束进入后即报错，脚本结束

### 问题副本

副本：旧都列车内部，施工废墟内部

### 运行日志

指令[ 零号空洞 ] 节点 检测游戏窗口 返回状态 成功
指令[ 零号空洞 ] 节点 初始画面识别 返回状态 未找到 信息
指令[ 零号空洞 ] 节点 初始画面识别 返回状态 未找到 信息
指令[ 零号空洞 ] 节点 初始画面识别 返回状态 未找到 信息
指令[ 零号空洞 ] 节点 初始画面识别 返回状态 未找到 信息
指令[ 传送 快捷手册 挑战-零号空洞-旧都列车 ] 节点 检测游戏窗口 返回状态 成功
指令[ 打开快捷手册 ] 节点 检测游戏窗口 返回状态 成功
指令[ 打开菜单 ] 节点 检测游戏窗口 返回状态 成功
指令[ 打开菜单 ] 节点 画面识别 返回状态 失败
指令[ 返回大世界 ] 节点 检测游戏窗口 返回状态 成功
指令[ 返回大世界 ] 节点 画面识别 返回状态 重试
指令[ 返回大世界 ] 节点 画面识别 返回状态 重试
指令[ 返回大世界 ] 节点 画面识别 返回状态 成功
指令[ 返回大世界 ] 执行成功 返回状态 成功
指令[ 打开菜单 ] 节点 返回大世界 返回状态 成功
指令[ 打开菜单 ] 节点 点击菜单 返回状态 成功
指令[ 打开菜单 ] 节点 画面识别 返回状态 成功
指令[ 打开菜单 ] 执行成功 返回状态 成功
指令[ 打开快捷手册 ] 节点 打开菜单 返回状态 成功
指令[ 打开快捷手册 ] 节点 点击更多 返回状态 快捷手册
指令[ 打开快捷手册 ] 执行成功 返回状态 快捷手册
指令[ 传送 快捷手册 挑战-零号空洞-旧都列车 ] 节点 快捷手册 返回状态 快捷手册
指令[ 快捷手册 选择Tab 挑战 ] 节点 检测游戏窗口 返回状态 成功
指令[ 快捷手册 选择Tab 挑战 ] 节点 选择TAB 返回状态 成功
指令[ 快捷手册 选择Tab 挑战 ] 执行成功 返回状态 成功
指令[ 传送 快捷手册 挑战-零号空洞-旧都列车 ] 节点 选择TAB 返回状态 成功
指令[ 快捷手册 选择分类 零号空洞 ] 节点 检测游戏窗口 返回状态 成功
指令[ 快捷手册 选择分类 零号空洞 ] 节点 选择分类 返回状态 成功
指令[ 快捷手册 选择分类 零号空洞 ] 执行成功 返回状态 成功
指令[ 传送 快捷手册 挑战-零号空洞-旧都列车 ] 节点 选择分类 返回状态 成功
指令[ 快捷手册 选择副本类型 旧都列车 ] 节点 检测游戏窗口 返回状态 成功
指令[ 快捷手册 选择副本类型 旧都列车 ] 节点 选择副本 返回状态 找不到 前往
指令[ 快捷手册 选择副本类型 旧都列车 ] 节点 选择副本 返回状态 成功
指令[ 快捷手册 选择副本类型 旧都列车 ] 节点 确认 返回状态 传送确认
指令[ 快捷手册 选择副本类型 旧都列车 ] 执行成功 返回状态 传送确认
指令[ 传送 快捷手册 挑战-零号空洞-旧都列车 ] 节点 选择副本分类 返回状态 传送确认
指令[ 传送 快捷手册 挑战-零号空洞-旧都列车 ] 执行成功 返回状态 传送确认
指令[ 零号空洞 ] 节点 传送 返回状态 传送确认
指令[ 零号空洞 ] 节点 等待入口加载 返回状态 街区
指令[ 零号空洞 ] 节点 选择副本类型 返回状态 下一步
指令[ 零号空洞 ] 节点 选择副本 返回状态 旧都列车-内部
指令[ 零号空洞 ] 节点 下一步 返回状态 出战
指令[ 出战 ] 节点 检测游戏窗口 返回状态 成功
指令[ 出战 ] 节点 出战 返回状态 出战
指令[ 出战 ] 节点 识别低等级 返回状态 未找到 确定并出战
指令[ 出战 ] 节点 识别低等级 返回状态 未找到 确定并出战
指令[ 出战 ] 节点 识别低等级 返回状态 未找到 确定并出战
指令[ 出战 ] 节点 识别低等级 返回状态 未找到 确定并出战
指令[ 出战 ] 节点 进入成功 返回状态 成功
指令[ 出战 ] 执行成功 返回状态 成功
指令[ 零号空洞 ] 节点 出战 返回状态 成功
指令[ 零号空洞 ] 执行出错 相关截图保存至 HollowZeroApp_1731299632912 Traceback (most recent call last): File "E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 295, in execute round_result: OperationRoundResult = self._execute_one_round() ^^^^^^^^^^^^^^^^^^^^^^^^^ File "E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 367, in _execute_one_round current_round_result: OperationRoundResult = self._current_node.op_method(self) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\src\zzz_od\application\hollow_zero\hollow_zero_app.py", line 151, in auto_run self.ctx.hollow.init_before_hollow_start(self.mission_type_name, self.mission_name, self.level, self.phase) File "E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\src\zzz_od\context\hollow_context.py", line 444, in init_before_hollow_start self.ctx.hollow.init_event_yolo(self.ctx.yolo_config.hollow_zero_event_gpu) File "E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\src\zzz_od\context\hollow_context.py", line 64, in init_event_yolo self._event_model = HollowEventDetector( ^^^^^^^^^^^^^^^^^^^^ File "E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\src\zzz_od\yolo\hollow_event_detector.py", line 25, in __init__ Yolov8Detector.__init__( File "E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\src\one_dragon\yolo\yolov8_onnx_det.py", line 35, in __init__ OnnxModelLoader.__init__( File "E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\src\one_dragon\yolo\onnx_model_loader.py", line 39, in __init__ self.load_model() File "E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\src\one_dragon\yolo\onnx_model_loader.py", line 126, in load_model self.session = ort.InferenceSession( ^^^^^^^^^^^^^^^^^^^^^ File "E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__ self._create_inference_session(providers, provider_options, disabled_optimizers) File "E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 472, in _create_inference_session sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\assets\models\hollow_zero_event\yolov8s-736-hollow-zero-event-1109\model.onnx failed:Load model E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\assets\models\hollow_zero_event\yolov8s-736-hollow-zero-event-1109\model.onnx failed. File doesn't exist
指令[ 零号空洞 ] 执行出错 相关截图保存至 HollowZeroApp_1731299637923 Traceback (most recent call last): File "E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 295, in execute round_result: OperationRoundResult = self._execute_one_round() ^^^^^^^^^^^^^^^^^^^^^^^^^ File "E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 367, in _execute_one_round current_round_result: OperationRoundResult = self._current_node.op_method(self) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\src\zzz_od\application\hollow_zero\hollow_zero_app.py", line 151, in auto_run self.ctx.hollow.init_before_hollow_start(self.mission_type_name, self.mission_name, self.level, self.phase) File "E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\src\zzz_od\context\hollow_context.py", line 444, in init_before_hollow_start self.ctx.hollow.init_event_yolo(self.ctx.yolo_config.hollow_zero_event_gpu) File "E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\src\zzz_od\context\hollow_context.py", line 64, in init_event_yolo self._event_model = HollowEventDetector( ^^^^^^^^^^^^^^^^^^^^ File "E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\src\zzz_od\yolo\hollow_event_detector.py", line 25, in __init__ Yolov8Detector.__init__( File "E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\src\one_dragon\yolo\yolov8_onnx_det.py", line 35, in __init__ OnnxModelLoader.__init__( File "E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\src\one_dragon\yolo\onnx_model_loader.py", line 39, in __init__ self.load_model() File "E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\src\one_dragon\yolo\onnx_model_loader.py", line 126, in load_model self.session = ort.InferenceSession( ^^^^^^^^^^^^^^^^^^^^^ File "E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__ self._create_inference_session(providers, provider_options, disabled_optimizers) File "E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 472, in _create_inference_session sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\assets\models\hollow_zero_event\yolov8s-736-hollow-zero-event-1109\model.onnx failed:Load model E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\assets\models\hollow_zero_event\yolov8s-736-hollow-zero-event-1109\model.onnx failed. File doesn't exist
指令[ 零号空洞 ] 执行出错 相关截图保存至 HollowZeroApp_1731299640074 Traceback (most recent call last): File "E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 295, in execute round_result: OperationRoundResult = self._execute_one_round() ^^^^^^^^^^^^^^^^^^^^^^^^^ File "E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 367, in _execute_one_round current_round_result: OperationRoundResult = self._current_node.op_method(self) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\src\zzz_od\application\hollow_zero\hollow_zero_app.py", line 151, in auto_run self.ctx.hollow.init_before_hollow_start(self.mission_type_name, self.mission_name, self.level, self.phase) File "E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\src\zzz_od\context\hollow_context.py", line 444, in init_before_hollow_start self.ctx.hollow.init_event_yolo(self.ctx.yolo_config.hollow_zero_event_gpu) File "E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\src\zzz_od\context\hollow_context.py", line 64, in init_event_yolo self._event_model = HollowEventDetector( ^^^^^^^^^^^^^^^^^^^^ File "E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\src\zzz_od\yolo\hollow_event_detector.py", line 25, in __init__ Yolov8Detector.__init__( File "E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\src\one_dragon\yolo\yolov8_onnx_det.py", line 35, in __init__ OnnxModelLoader.__init__( File "E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\src\one_dragon\yolo\onnx_model_loader.py", line 39, in __init__ self.load_model() File "E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\src\one_dragon\yolo\onnx_model_loader.py", line 126, in load_model self.session = ort.InferenceSession( ^^^^^^^^^^^^^^^^^^^^^ File "E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__ self._create_inference_session(providers, provider_options, disabled_optimizers) File "E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 472, in _create_inference_session sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\assets\models\hollow_zero_event\yolov8s-736-hollow-zero-event-1109\model.onnx failed:Load model E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\assets\models\hollow_zero_event\yolov8s-736-hollow-zero-event-1109\model.onnx failed. File doesn't exist

**Comment by DoctorReid** [comment]
E:\Game\ZZZAuto\ZenlessZoneZero-OneDragon\assets\models\hollow_zero_event\yolov8s-736-hollow-zero-event-1109

这个文件夹删掉，重新下载模型
