### ISSUE TITLE
[问题反馈] [零号空洞] 必经之路上不打怪。一直撞墙无法前进

### ISSUE THREAD

**Issue by pyf1835** [DoctorReid/ZenlessZoneZero-OneDragon#414]
### 问题描述

前往目标: [守门人] 当前移动: [门扉禁闭-侵蚀]
指令[ 空洞操作器 ] 节点 画面识别 返回状态 等待
优先级 [终点]
前往目标: [守门人] 当前移动: [门扉禁闭-侵蚀]
指令[ 空洞操作器 ] 节点 画面识别 返回状态 等待
优先级 [终点]

一直就这么循环

### 问题副本

旧都列车-内部

### 寻路方式

速通方式

### 游戏截图/录屏

https://github.com/user-attachments/assets/115c3580-9b0c-488f-82f9-b814c9ad06ed

### 运行日志

[log.txt](https://github.com/user-attachments/files/17701601/log.txt)

### 你的建议

应该是优化判定吧

**Comment by DoctorReid** [comment]
应该是没更新代码，新版本重现不了
