### ISSUE TITLE
[问题反馈] [通用] 咖啡计划开启后，中途会关游戏

### ISSUE THREAD

**Issue by SuperSB** [DoctorReid/ZenlessZoneZero-OneDragon#416]
### 问题描述

咖啡计划开启后，中途会关游戏

### 游戏截图

https://github.com/user-attachments/assets/40730f5c-77ab-491a-b130-9958ddc1bd04

### 运行日志

[log2.txt](https://github.com/user-attachments/files/17709177/log2.txt)

**Comment by SuperSB** [comment]
<img width="794" alt="8053308bfef17ac5eba5d74bd2b65f3" src="https://github.com/user-attachments/assets/6bd5a3fb-bee3-42f2-8f4b-4ff74ae7e5c9">
日志到这里就关游戏了

**Comment by SuperSB** [comment]
![image](https://github.com/user-attachments/assets/a69c8d75-2156-47de-b8e3-ba420995889e)
ka
咖啡计划我是这么设置的

**Comment by DoctorReid** [comment]
看日志，应该是你自己按F10了吧

**Comment by SuperSB** [comment]
> 看日志，应该是你自己按F10了吧

截图里红框的时候，就已经退出了，可以看视频里面退出后对应的log。
后面我f9想继续，突然想起要提一个issue，就f10退出了

**Comment by SuperSB** [comment]
> 看日志，应该是你自己按F10了吧

我拿着手机录像，确定是没按键盘😂

**Comment by SuperSB** [comment]
[log.txt](https://github.com/user-attachments/files/17724158/log.txt)
我大号，喝完咖啡有300体力的，做完每日体力计划，刚好0体力，能继续
到小号，没有300体力，体力计划遇到不足后，就退出了
![image](https://github.com/user-attachments/assets/98f2f851-1ddb-4276-a85f-70daba2fecf0)

**Comment by DoctorReid** [comment]
理解了，等待今晚修复

**Comment by SuperSB** [comment]
![image](https://github.com/user-attachments/assets/70f91c18-acc9-47e5-8dd6-0e5abcefb1a8)
这是终端运行里面的log截图，连300体力的也会退，我根本没有操作，嗨-_-
[log.txt](https://github.com/user-attachments/files/17740660/log.txt)

**Comment by SuperSB** [comment]
good job
