### ISSUE TITLE
Bug:一条龙体力计划选择编队有误

### ISSUE THREAD

**Issue by smallmj** [DoctorReid/ZenlessZoneZero-OneDragon#421]
在一条龙体力计划设置的是用编队3刷，但是进游戏以后选择的是编队6，导致柳使用简的配置，无法攻击![Screenshot_20241114_082225_com.netease.uuremote.jpg](https://github.com/user-attachments/assets/4d7c2c52-60d8-454e-ba3e-77f43efce624)

https://github.com/user-attachments/assets/9e2ac500-d902-44e3-b340-da611b23650e

**Comment by DoctorReid** [comment]
因为编队名字都接近，如果出现选错，可以更改一下配队名字

**Comment by smallmj** [comment]
啊？不是按照队伍编号来选的？编队还能起名字？
