### ISSUE TITLE
[问题反馈] [通用] 启动报错

### ISSUE THREAD

**Issue by LNGS-Horse** [DoctorReid/ZenlessZoneZero-OneDragon#428]
### 代码版本

6bea467

### 问题描述

使用新版ui后，下载器无法正常执行”启动一条龙”，点击后会弹窗报错如下截图
![image](https://github.com/user-attachments/assets/d9c90734-0e8e-419c-acc5-948ae8e620f5)

**Comment by johnson50313** [comment]
+1

**Comment by DoctorReid** [comment]
参考 #367
