### ISSUE TITLE
[问题反馈] [通用] 

### ISSUE THREAD

**Issue by kawayiYokami** [DoctorReid/ZenlessZoneZero-OneDragon#429]
### 代码版本

6bea467

### 问题描述

1、启用的不是第一实例的情况下，后面的实例都会被跳过
![image](https://github.com/user-attachments/assets/8abb6128-8c6f-4e7e-b5fc-da303704336b)

2、启动的是第一实例的情况下，一条龙默认只运行第一实例
![image](https://github.com/user-attachments/assets/db3f305c-e586-4828-99c4-5ba509b17fe2)

**Comment by DoctorReid** [comment]
一条龙里选择全部实例
