### ISSUE TITLE
[问题反馈] [通用] 式與防卫战

### ISSUE THREAD

**Issue by pepexqc** [DoctorReid/ZenlessZoneZero-OneDragon#431]
### 代码版本

6bea467

### 问题描述

1，运行一条龙时，到式與防卫战项目后无反应
2，单独运行式與防卫战，打开防卫战后不进入战斗，直接打开奖励页面然后范围，显示为式與防卫战已经全部通关，但是其实一关没打。

### 游戏截图

![33522af7d4e3637e60e409691f88d3f8](https://github.com/user-attachments/assets/8dcab817-c02d-4a4d-9b3c-94a81f2b62a8)

**Comment by kaileung** [comment]
同，
