### ISSUE TITLE
[问题反馈] [通用] 空洞卡住

### ISSUE THREAD

**Issue by SuperSB** [DoctorReid/ZenlessZoneZero-OneDragon#433]
### 代码版本

我是昨晚直接下载最新的zip（看截图）

### 问题描述

1.版本截图
![image](https://github.com/user-attachments/assets/4e0f96b4-ab41-4f78-a4c1-ebb1d2a52fcd)
2.相关问题看视频

### 游戏截图

https://github.com/user-attachments/assets/e304f8c6-7ee0-4ae1-94f5-da6ae5308dda

### 运行日志

[log.txt](https://github.com/user-attachments/files/17792834/log.txt)

### 你的建议

还得是一步一步地走

**Comment by SuperSB** [comment]
[log.txt](https://github.com/user-attachments/files/17801202/log.txt)

https://github.com/user-attachments/assets/eeb5c107-d650-4a72-96e2-08045e705718

哈哈哈哈哈哈，颤抖吧，又一个死循环，进入全是商店奖励的地方

**Comment by kawasakana** [comment]
> [log.txt](https://github.com/user-attachments/files/17801202/log.txt)
> bd66e97d14635d15ca2bbd9827153d6d.mp4
> 
> 哈哈哈哈哈哈，颤抖吧，又一个死循环，进入全是商店奖励的地方

可能得加个记录已走过的格子，理论上这个功能是走格子的基础。

**Comment by DoctorReid** [comment]
应该修复了

**Comment by SuperSB** [comment]
[log.txt](https://github.com/user-attachments/files/17979757/log.txt)
挂了一天，一直卡在这里，版本是今早更新的

https://github.com/user-attachments/assets/f2ec30f7-94ce-4bb5-bb3c-e93d821f7009
