### ISSUE TITLE
[问题反馈] [零号空洞] 休息层出现商店会导致循环卡住

### ISSUE THREAD

**Issue by f59375543** [DoctorReid/ZenlessZoneZero-OneDragon#434]
### 代码版本

e730e48

### 问题描述

休息层出现商店会导致循环卡住

### 问题副本

施工废墟-内部

### 寻路方式

默认

### 游戏截图

https://github.com/user-attachments/assets/580e5e3c-f087-4957-a55a-ed0c762c4860

### 运行日志

[log.txt](https://github.com/user-attachments/files/17793429/log.txt)

**Comment by smallmj** [comment]
同样的问题https://github.com/user-attachments/assets/4a6de8ae-1c34-4538-8d2d-343dd5cdc925

**Comment by snowly233** [comment]
一样有这个问题，两个商店反复跑
