### ISSUE TITLE
[问题反馈] [零号空洞] 零号空洞时会时不时卡死电脑被迫重启。

### ISSUE THREAD

**Issue by ProvidenceP** [DoctorReid/ZenlessZoneZero-OneDragon#438]
### 代码版本

5bdb49c

### 问题描述

挂空洞刷业绩，在借钱哥给机制鸣徽/第一层首战前半路/第一层打完小怪后半路，随机时点整个游戏卡住死机，连电脑都不能操作，只能重启电脑。
试过在第一桌面上开窗口化1080p，也试过在远程桌面开全屏1080，但只要游戏卡死，整个电脑都得重启才能使用。
而在做日活一条龙，刷周常boss等时候没有出现问题。

### 问题副本

施工废墟内部

### 运行日志

[log.txt](https://github.com/user-attachments/files/17806345/log.txt)
最后一次测试是从北京时间05：05开始，一直到卡死重启

### 你的建议

不知道是我电脑的问题还是其他的设置问题。毕竟我18号才开始用这个脚本，存在是我设置没弄好的可能。配置5800H+3070laptop

**Comment by DoctorReid** [comment]
游戏卡住基本与脚本无关
