### ISSUE TITLE
[问题反馈] [通用]  功能改进建议

### ISSUE THREAD

**Issue by MoonofBridge24** [DoctorReid/ZenlessZoneZero-OneDragon#443]
### 代码版本

5bdb49c

### 问题描述

每日咖啡录像店和刮刮乐可以从快捷手册直接进，有效避免比利遮挡报刊亭等问题的影响。快捷手册可以F2直接进，现在的逻辑是进菜单之后模拟点击多识别一步。刷技能升级材料的时候也可以从快捷手册直接跳转到冰系。

**Comment by DoctorReid** [comment]
同 #482 

1.4版本之后再考虑
