### ISSUE TITLE
[问题反馈] [通用] 刷体力闪退

### ISSUE THREAD

**Issue by nosizeclzf** [DoctorReid/ZenlessZoneZero-OneDragon#445]
### 代码版本

5bdb49c

### 问题描述

运行刷体力功能（定期剿灭），闪退

### 游戏截图

![刷体力闪退](https://github.com/user-attachments/assets/4c3546cf-8576-4a57-81ce-31d202948294)

### 运行日志

[python_17.00.log](https://github.com/user-attachments/files/17843108/python_17.00.log)
[python_17.02.log](https://github.com/user-attachments/files/17843109/python_17.02.log)

### 你的建议

修复bug

**Comment by DoctorReid** [comment]
因为你选择了关闭游戏
