### ISSUE TITLE
[问题反馈] [通用] 无法安装，显示pip安装失败

### ISSUE THREAD

**Issue by JIXA18** [DoctorReid/ZenlessZoneZero-OneDragon#449]
### 代码版本

5bdb49c67693242c2e9cc5c6bee73fc4d047a1ba

### 问题描述

使用OneDragon Installer安装过程中，在Python虚拟环境安装环节显示pip失败，多次尝试删除文件夹，解压重装仍无法解决问题

### 游戏截图

![1](https://github.com/user-attachments/assets/6c4a05c0-b564-4c46-ba61-66cd10b6e6a6)

### 运行日志

[log.txt](https://github.com/user-attachments/files/17879466/log.txt)

**Comment by DoctorReid** [comment]
设置-脚本环境-pip源 换一个

**Comment by JIXA18** [comment]
感谢大佬，已经顺利解决！
