### ISSUE TITLE
[问题反馈] [通用] 大月卡领取后无法返回

### ISSUE THREAD

**Issue by TakeHerBack** [DoctorReid/ZenlessZoneZero-OneDragon#451]
### 代码版本

3031fdc

### 问题描述

到大月卡界面领取之后会卡住，无法返回大世界
并且只有第一个号会出现此情况（本机器共添加4个实例帐号）
已更新3031fdc

### 游戏截图

![0D773623431C85C4B73ED8EDCB4BC91D](https://github.com/user-attachments/assets/1c0d96fb-04b7-4884-a1cd-d0aabb01292a)
![103FB8AD5A0F1536BA7D6A30FCDC43D8](https://github.com/user-attachments/assets/2aadbc93-58e9-46b5-abf6-ce4c42c5336b)
![F3B4CBDF30F58AA69DE043E46001E108](https://github.com/user-attachments/assets/548e09b7-e0a1-4d25-961a-fa61ba83d7c2)

### 运行日志

[20241124log .txt](https://github.com/user-attachments/files/17893889/20241124log.txt)

**Comment by DoctorReid** [comment]
不知道为啥，尝试更新代码之后，再上传一份日志

**Comment by TakeHerBack** [comment]
[20241128log.txt](https://github.com/user-attachments/files/17943546/20241128log.txt)
重新上传了日志，今天看了下一条龙运行，还发现第一个帐号还会出现不领取周记的情况，点都没点进去，但是后续帐号没问题

**Comment by TakeHerBack** [comment]
> 不知道为啥，尝试更新代码之后，再上传一份日志

重新传了

**Comment by DoctorReid** [comment]
修复了

**Comment by TakeHerBack** [comment]
666好高的效率
