### ISSUE TITLE
[问题反馈] [通用] 

### ISSUE THREAD

**Issue by Tachanka02** [DoctorReid/ZenlessZoneZero-OneDragon#458]
### 代码版本

1a8fd9e

### 问题描述

指令[ 出战 ] 节点 出战 返回状态 未找到 出战
经常遇到这个问题，包括体力刷本，恶名狩猎和零号空洞。以前是可以使用的，但是版本更新以后好像就一直不能识别

### 游戏截图

![_1733055685602](https://github.com/user-attachments/assets/bb8c1bd8-d8a6-4416-a325-82a1818477fe)

### 运行日志

[20241201.zip](https://github.com/user-attachments/files/17968891/20241201.zip)

### 你的建议

希望能针对出站按钮进行优化

**Comment by Tachanka02** [comment]
好像还是无法识别

**Comment by DoctorReid** [comment]
你上传的截图我试了是可以的。

可以看看是不是自己开了什么滤镜导致的
