### ISSUE TITLE
[问题反馈] [通用] 影像店营业，找不到青衣

### ISSUE THREAD

**Issue by HaneRo** [DoctorReid/ZenlessZoneZero-OneDragon#460]
### 代码版本

3bb5904

### 问题描述

无法在影像店营业中找到青衣，角色在第一行第四个
![{9D147D88-7B09-4B00-A428-CD5DE03511A2}](https://github.com/user-attachments/assets/817e2ba9-edde-459d-a6f6-a32c366b4380)

### 游戏截图

![{6D4BF7E8-896D-4E2E-A0D6-5DCA6A80070D}](https://github.com/user-attachments/assets/a7bd03a3-68c7-444f-99e0-114b0ef7fb08)

### 运行日志

[Uploading log.txt…]()

**Comment by HaneRo** [comment]
[log.txt](https://github.com/user-attachments/files/17976478/log.txt)

**Comment by DoctorReid** [comment]
尝试修复了下，不行的话换其他电属性角色
