### ISSUE TITLE
空洞卡住没解决

### ISSUE THREAD

**Issue by SuperSB** [DoctorReid/ZenlessZoneZero-OneDragon#461]
[log.txt](https://github.com/user-attachments/files/17979757/log.txt)
挂了一天，一直卡在这里，版本是今早更新的

https://github.com/user-attachments/assets/f2ec30f7-94ce-4bb5-bb3c-e93d821f7009

_Originally posted by @SuperSB in https://github.com/DoctorReid/ZenlessZoneZero-OneDragon/issues/433#issuecomment-2511783593_

**Comment by DoctorReid** [comment]
1. 版本号
2. 通关方式
3. F11截图
