### ISSUE TITLE
[功能建议] 建议增加自动对话功能

### ISSUE THREAD

**Issue by nosizeclzf** [DoctorReid/ZenlessZoneZero-OneDragon#468]
### 代码版本

d2f8bfb

### 问题描述

建议增加自动对话功能，快速过对话

**Comment by Paper-white** [comment]
游戏助手的委托助手功能。。。不就有自动点对话吗
![image](https://github.com/user-attachments/assets/6c595faa-0557-4252-8c49-46f9abcf1988)
