### ISSUE TITLE
[问题反馈] [通用]每日体力识别问题，以及卡顿

### ISSUE THREAD

**Issue by 08158** [DoctorReid/ZenlessZoneZero-OneDragon#471]
### 代码版本

0364e62

### 问题描述

体力计划进入战斗时，在加载界面中，未等战斗开始就判定运行失败，貌似是节点识别错误所导致
卡顿挺严重的，打开程序鼠标都掉帧，游戏反而不卡，战斗脚本点半天都不运行

### 游戏截图

![image](https://github.com/user-attachments/assets/99353f27-1a4e-475f-8e21-46238006bb37)

**Comment by DoctorReid** [comment]
录个屏 + 上传日志看看
