### ISSUE TITLE
[问题反馈] [战斗助手] 

### ISSUE THREAD

**Issue by 08158** [DoctorReid/ZenlessZoneZero-OneDragon#472]
### 代码版本

0364e62

### 使用配置

[全限解]专属配队-艾莲      作者：小巡夜
抱歉在这里说，因为进群要等审核，我也不常玩，可以的话转告一下谢谢

### 问题描述

自动战斗无法运行脚本，无论怎么按f9或是直接点按钮都无反应，一直显示开始，但是会选中游戏窗口
貌似是兼容问题，因为更新代码前使用正常，现在别的脚本也可以正常运行
但不清楚是否有别的脚本无法使用

### 问题副本

在人物背景页面

**Comment by 08158** [comment]
![image](https://github.com/user-attachments/assets/fc05ba58-855e-4ddd-94e4-7a07fbc07ca4)

**Comment by Paper-white** [comment]
小巡夜退坑了，这个脚本我进行了临时修复发进了群里
最近的更新包含了以下三点需要改脚本的地方

月城柳 → 柳
按键-快速支援   这个删了
切换角色 → 按键-切换角色

涉及到这三点的脚本都失效了，替换一下脚本内对应的按键和名称就行

**Comment by owwkmidream** [comment]
> Uploading [全限制解除]专属配队-艾莲 新增莱特 脚本临时修复版.zip… 小巡夜退坑了，这个脚本我进行了临时修复发进了群里 最近的更新包含了以下三点需要改脚本的地方
> 
> 月城柳 → 柳 按键-快速支援 这个删了 切换角色 → 按键-切换角色
> 
> 涉及到这三点的脚本都失效了，替换一下脚本内对应的按键和名称就行

文件链接有误

**Comment by Paper-white** [comment]
> > Uploading [全限制解除]专属配队-艾莲 新增莱特 脚本临时修复版.zip… 小巡夜退坑了，这个脚本我进行了临时修复发进了群里 最近的更新包含了以下三点需要改脚本的地方
> > 月城柳 → 柳 按键-快速支援 这个删了 切换角色 → 按键-切换角色
> > 涉及到这三点的脚本都失效了，替换一下脚本内对应的按键和名称就行
> 
> 文件链接有误

主群下载最新的或者等同步到脚本共享吧，我只是进行了临时的修复，主群有其他佬在进行不断的改进
