### ISSUE TITLE
[问题反馈] [通用] 

### ISSUE THREAD

**Issue by moyudeyuwang** [DoctorReid/ZenlessZoneZero-OneDragon#473]
### 代码版本

0364e62

### 问题描述

安装pip失败

### 游戏截图

![安装pip失败](https://github.com/user-attachments/assets/224b115e-c602-4cc9-b51c-13f26fb27d09)

### 运行日志

[log.txt](https://github.com/user-attachments/files/18045929/log.txt)

**Comment by DoctorReid** [comment]
设置 - 脚本环境 - Pip源 换一个
