### ISSUE TITLE
[问题反馈] [零号空洞] 模型加载缓慢以及空洞操作器报错

### ISSUE THREAD

**Issue by JYcdt** [DoctorReid/ZenlessZoneZero-OneDragon#474]
### 代码版本

0364e62

### 问题描述

1、战斗声音模型加载卡顿，第一次进入战斗后约30+秒加载完成
2、长时间运行后空洞操作器报错导致整个程序停止

### 问题副本

零号空洞-施工废墟-核心

### 寻路方式

默认

### 游戏截图

![HollowRunner_1733578600144](https://github.com/user-attachments/assets/e1fe0675-4b48-47cd-8fbe-8e280256ea31)

### 运行日志

[log.txt](https://github.com/user-attachments/files/18048610/log.txt)

**Comment by DoctorReid** [comment]
尝试切换GPU开关 机器硬件问题  与脚本无关
