### ISSUE TITLE
[问题反馈] [通用] 式與防卫战

### ISSUE THREAD

**Issue by Anime** [DoctorReid/ZenlessZoneZero-OneDragon#475]
### 代码版本

 0364e62

### 问题描述

式與防卫战计算配队正确(编队1+编队3), 但是自动选择配队出现错误(编队1+编队4)

### 游戏截图

![QQ截图20241208110821](https://github.com/user-attachments/assets/066ce8a4-505b-485c-a626-21169ec7be6f)
![QQ截图20241208121121](https://github.com/user-attachments/assets/e9b363b1-0990-4492-9f78-c6d93c1efda0)
![QQ截图20241208121316](https://github.com/user-attachments/assets/de8c45b4-0094-42dc-a316-fcf728a4aa85)

### 运行日志

[log.txt](https://github.com/user-attachments/files/18050693/log.txt)

**Comment by DoctorReid** [comment]
默认编队名称选错的话，自己改个名字就行
