### ISSUE TITLE
[建议] [等待增加随机值] 

### ISSUE THREAD

**Issue by h2562961224** [DoctorReid/ZenlessZoneZero-OneDragon#48]
### 问题描述

等待秒数 操作 中data增加随机值参数（是否随机，随机范围，分布函数等），减少被识别的特征

比较好的实践，
触发后，在判定范围内等待随机时间，闪避之后，持续数秒的按键间隔期望为0.2s的连续普通攻击（模拟狂按）

**Comment by DoctorReid** [comment]
意义不大，战斗过程的闪光打断已经足够让你的按键不那么机械了
