### ISSUE TITLE
[问题反馈] [零号空洞] 建议追加一个判断队友位置选项

### ISSUE THREAD

**Issue by accelerator148** [DoctorReid/ZenlessZoneZero-OneDragon#484]
### 代码版本

9bcd45c

### 问题描述

前台角色错误导致自动战斗失效

### 问题副本

前台角色错误导致自动战斗失效，我柳变成2号位后自动战斗就卡了

### 运行日志

建议追加一个判断队友位置选项

**Comment by Paper-white** [comment]
大多数战斗脚本会写死是 切换上一位角色或下一位角色，而不是判断123号位的角色来选择
切人之后脚本卡住一般是你的配队不符合战斗脚本要求
请根据战斗脚本调整你的配队
点击 `战斗助手-配置编辑` 选择你的战斗脚本，可以查看当前适用的角色配队，配队顺序需要和脚本一致

**Comment by accelerator148** [comment]
自动战斗初始化失败 共享配队文件请在群内提醒对应作者修复 Traceback (most recent call last): File "F:\mihoyo\ZenlessZoneZero-OneDragon\src\zzz_od\auto_battle\auto_battle_operator.py", line 69, in init_before_running success, msg = self._init_operator() ^^^^^^^^^^^^^^^^^^^^^ File "F:\mihoyo\ZenlessZoneZero-OneDragon\src\zzz_od\auto_battle\auto_battle_operator.py", line 138, in _init_operator ConditionalOperator.init( File "F:\mihoyo\ZenlessZoneZero-OneDragon\src\one_dragon\base\conditional_operation\conditional_operator.py", line 67, in init handler = construct_scene_handler(scene_data, self.get_state_recorder, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\mihoyo\ZenlessZoneZero-OneDragon\src\one_dragon\base\conditional_operation\utils.py", line 22, in construct_scene_handler state_handlers = _get_state_handlers( ^^^^^^^^^^^^^^^^^^^^ File "F:\mihoyo\ZenlessZoneZero-OneDragon\src\one_dragon\base\conditional_operation\utils.py", line 83, in _get_state_handlers state_handlers.append(construct_state_handler( ^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\mihoyo\ZenlessZoneZero-OneDragon\src\one_dragon\base\conditional_operation\utils.py", line 112, in construct_state_handler state_cal_tree = construct_state_cal_tree(states_expr, state_getter) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\mihoyo\ZenlessZoneZero-OneDragon\src\one_dragon\base\conditional_operation\state_cal_tree.py", line 209, in construct_state_cal_tree raise ValueError('位置 %d 的左中括号 后方状态不合法 %s' % (display_idx, state_name)) ValueError: 位置 1 的左中括号 后方状态不合法 前台-月城柳
![屏幕截图 2024-12-10 193819](https://github.com/user-attachments/assets/3f518aca-e173-4075-b8c6-ba5f443b6543)

**Comment by Paper-white** [comment]
> 自动战斗初始化失败 共享配队文件请在群内提醒对应作者修复 Traceback (most recent call last): File "F:\mihoyo\ZenlessZoneZero-OneDragon\src\zzz_od\auto_battle\auto_battle_operator.py", line 69, in init_before_running success, msg = self._init_operator() ^^^^^^^^^^^^^^^^^^^^^ File "F:\mihoyo\ZenlessZoneZero-OneDragon\src\zzz_od\auto_battle\auto_battle_operator.py", line 138, in _init_operator ConditionalOperator.init( File "F:\mihoyo\ZenlessZoneZero-OneDragon\src\one_dragon\base\conditional_operation\conditional_operator.py", line 67, in init handler = construct_scene_handler(scene_data, self.get_state_recorder, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\mihoyo\ZenlessZoneZero-OneDragon\src\one_dragon\base\conditional_operation\utils.py", line 22, in construct_scene_handler state_handlers = _get_state_handlers( ^^^^^^^^^^^^^^^^^^^^ File "F:\mihoyo\ZenlessZoneZero-OneDragon\src\one_dragon\base\conditional_operation\utils.py", line 83, in _get_state_handlers state_handlers.append(construct_state_handler( ^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\mihoyo\ZenlessZoneZero-OneDragon\src\one_dragon\base\conditional_operation\utils.py", line 112, in construct_state_handler state_cal_tree = construct_state_cal_tree(states_expr, state_getter) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\mihoyo\ZenlessZoneZero-OneDragon\src\one_dragon\base\conditional_operation\state_cal_tree.py", line 209, in construct_state_cal_tree raise ValueError('位置 %d 的左中括号 后方状态不合法 %s' % (display_idx, state_name)) ValueError: 位置 1 的左中括号 后方状态不合法 前台-月城柳 ![屏幕截图 2024-12-10 193819](https://private-user-images.githubusercontent.com/85104158/394256059-3f518aca-e173-4075-b8c6-ba5f443b6543.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MzU1OTUsIm5iZiI6MTczMzgzNTI5NSwicGF0aCI6Ii84NTEwNDE1OC8zOTQyNTYwNTktM2Y1MThhY2EtZTE3My00MDc1LWI4YzYtYmE1ZjQ0M2I2NTQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDEyNTQ1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyNWU2NDIyNzg1MGU2ZDNlZDU5MmIyMjljYjUzZjRkOTRiMzBkYjczOTI3ZTJjMzg5MGYxZWFkZmVjOThhNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PnbeUvxv09tn7dVcGYd1H8DDyT_RjWGmrUVhtQk3waY)

#472
