### ISSUE TITLE
[建议] [通用] 日志输出内容增加

### ISSUE THREAD

**Issue by Paper-white** [DoctorReid/ZenlessZoneZero-OneDragon#486]
### 代码版本

114514

### 问题描述

建议能在日志里输出额外内容,以方便通过日志更详细的判断问题和使用环境
1. 当前代码版本
3. 自动战斗（包括空洞，防卫战等）开始时所使用的战斗脚本
4. 自动战斗使用的角色配队
5. 非自动战斗功能时的自动战斗（空洞，防卫战等）可选是否开启详细日志（输出触发器，条件集等）

**Comment by DoctorReid** [comment]
白纸姐姐你可以自己加一下前三个

最后一个必要不大，写战斗配置的可以自己开调试模式，就有日志输出了

**Comment by Paper-white** [comment]
> 白纸姐姐你可以自己加一下前三个
> 
> 最后一个必要不大，写战斗配置的可以自己开调试模式，就有日志输出了

我不会写（理直气壮）
