### ISSUE TITLE
[问题反馈] [零号空洞] 

### ISSUE THREAD

**Issue by shijianxuanlv** [DoctorReid/ZenlessZoneZero-OneDragon#487]
### 代码版本

63c7673

### 问题描述

卡住不动了[]
![Uploading 屏幕截图 2024-12-11 143818.png…]()
(url)

### 问题副本

施工废墟核心

### 运行日志

[Uploading log.txt…]()

**Comment by Paper-white** [comment]
没一个链接是有效的）

**Comment by DoctorReid** [comment]
请携带有效证件再来一次
