### ISSUE TITLE
[问题反馈] [战斗助手] 自动战斗不攻击只挨打

### ISSUE THREAD

**Issue by Dyachi** [DoctorReid/ZenlessZoneZero-OneDragon#497]
### 代码版本

982cb9f

### 使用配置

专属配队-艾莲

### 问题描述

1. 运行自动战斗
2. 角色不攻击只挨打

### 问题副本

火属性芯片刷的关卡（其实哪一个关卡都是这样 一律没反应）

### 游戏截图

![image](https://github.com/user-attachments/assets/aeeda70d-a638-4974-8770-447d89676c0f)
![_1734344080595](https://github.com/user-attachments/assets/65b0085b-0c65-49dd-a3b0-3ccc4c0ff3c7)

**Comment by smallmj** [comment]
> ![4c8282229512e0ce3811682078f1d0c4](https://private-user-images.githubusercontent.com/69088493/396102233-d9a67745-11ca-42f6-918a-35700c9cd93b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzOTc1MDIsIm5iZiI6MTczNDM5NzIwMiwicGF0aCI6Ii82OTA4ODQ5My8zOTYxMDIyMzMtZDlhNjc3NDUtMTFjYS00MmY2LTkxOGEtMzU3MDBjOWNkOTNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDAxMDAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhMjU1Y2Y1YzVmZGZlYTRmZTY1NWQ5Zjk2YjQxYzM4NzVhOGY4OWU5MDBjNzUyYWVmNTcwZDA1YzM3YjFiNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7t39_TI6hurkOKAUxjUHrhgd3m4Pi0hCJvRY8j3nyGc) 更多问题请优先参考问题手册 https://www.kdocs.cn/l/cbSJUUNotJ3Z

能不能每次更新脚本的时候自动把新的模型下载下来啊？设定好的按照规定时间执行脚本，结果早上起来发现无法自动战斗，查了半天原因发现是模型没下载，为啥不能在更新脚本的时候直接下载新的模型呢？

**Comment by DoctorReid** [comment]
模型比较大，不适合在代码更新里

**Comment by Leapiny** [comment]
1215版本模型，点击下载，只一瞬间变成下载中，然后马上就变成下载按钮。日志显示【下载模型失败】，有办法手工下载码？

**Comment by Dyachi** [comment]
> ![4c8282229512e0ce3811682078f1d0c4](https://private-user-images.githubusercontent.com/69088493/396102233-d9a67745-11ca-42f6-918a-35700c9cd93b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MTIzODcsIm5iZiI6MTczNDQxMjA4NywicGF0aCI6Ii82OTA4ODQ5My8zOTYxMDIyMzMtZDlhNjc3NDUtMTFjYS00MmY2LTkxOGEtMzU3MDBjOWNkOTNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA1MDgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwZDVhMzBiZWM5ZDMxN2FiMWEzZTI2NGU5YWM0ODllNjY3MTM3NzUyNWYwMmRmOTU1NGNkODBhMGViNjk3NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XxLGn6gYszFYlL_Fvw4xmd2XfpdFmIpE1rtbncZFDa0) 更多问题请优先参考问题手册 https://www.kdocs.cn/l/cbSJUUNotJ3Z

谢谢提醒！打扰了不好意思 新模型下载不下来，请问有推荐的代理软件吗，我不太懂这方面的
