### ISSUE TITLE
[问题反馈] [通用] 影像"推荐上架"

### ISSUE THREAD

**Issue by DabengBa** [DoctorReid/ZenlessZoneZero-OneDragon#50]
### 问题描述

40级&通关第一章后跟赫蒂对话升级录像店.

之后会出现"推荐上架"按钮, 不用一个一个选了.

![image](https://github.com/user-attachments/assets/91411f35-3d8e-4016-bb83-dd3680439a05)

**Comment by DoctorReid** [comment]
我居然不知道有这个东西
