### ISSUE TITLE
[问题反馈] [通用] [建议] 更新时不要覆盖玩家本地配置文件

### ISSUE THREAD

**Issue by Paper-white** [DoctorReid/ZenlessZoneZero-OneDragon#500]
### 代码版本

all

### 问题描述

更新的时候如果直接覆盖了玩家原本的配置文件
就会导致大量原本可能正常使用的脚本突然无法使用
就比如这次模型更新
更合理的情况应该是老用户遵循配置文件依旧使用老模型，新用户默认切换新的模型

### 你的建议

对用户的配置文件进行增量而非覆盖
配置文件内玩家自己修改过的东西保留
新配置进行增量写入
或者
使用全局配置文件和个人配置文件两个文件
用户修改过的内容写入个人配置文件
运行时优先检查个人配置文件并使用，其次使用全局配置文件

**Comment by DoctorReid** [comment]
现在的逻辑，是用户没有设置过的，就按默认值自动更新，设置过的不会覆盖。
