### ISSUE TITLE
[问题反馈] [通用] 选择编队3出战，但是却自动选择了编队6

### ISSUE THREAD

**Issue by f59375543** [DoctorReid/ZenlessZoneZero-OneDragon#520]
### 代码版本

b974f86

### 问题描述

运行一条龙的体力刷本，队伍选择错误

### 游戏截图

https://github.com/user-attachments/assets/c4b0dbf6-1de1-40f9-8327-d1fe24fd4988

**Comment by Paper-white** [comment]
OCR识别出错
使用细体字提高识别率
或修改各个队伍名为差异更大的字符
