### ISSUE TITLE
[问题反馈] [零号空洞] 空洞无法正常通过对话，会一直点击左下角

### ISSUE THREAD

**Issue by zcuu1** [DoctorReid/ZenlessZoneZero-OneDragon#521]
### 代码版本

b974f86

### 问题描述

空洞无法正常通过对话，会一直点击左下角，然后卡死在对话

### 问题副本

施工废墟-内部

### 游戏截图

![_1734761668194](https://github.com/user-attachments/assets/38a3c9b6-cc61-4477-977f-37112f5b9d4a)

**Comment by DoctorReid** [comment]
试了这截图应该是没问题的，提供日志看看

**Comment by zcuu1** [comment]
你好，非常感谢你的回复，我一开始是2k全屏，后面换成了1080窗口之后就正常了，我感觉应该是我的一条龙出了点小bug，目前正常啦，再次感谢您的回复！！&nbsp;


早川U
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年12月25日(星期三) 晚上10:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DoctorReid/ZenlessZoneZero-OneDragon] [问题反馈] [零号空洞] 空洞无法正常通过对话，会一直点击左下角 (Issue #521)














 
试了这截图应该是没问题的，提供日志看看
