### ISSUE TITLE
[问题反馈] [战斗助手] 前台角色头像被复活次数遮挡无法识别

### ISSUE THREAD

**Issue by imx123** [DoctorReid/ZenlessZoneZero-OneDragon#523]
### 代码版本

b974f86

### 使用配置

专属配队-艾莲

### 问题描述

1 运行恶名狩猎去打牲鬼-布林格
2 进入战斗之后，击破角色e，苍角普攻一下之后就站在原地不动
3 在角色被击飞弹出快速支援的时候会自动支援，但是之后又站在原地不动
4 如果我手动进入牲鬼的战斗之后再直接使用战斗助手也可以复现这个问题
5 在其他副本中自动战斗都运行良好，没有以上问题

### 问题副本

牲鬼-布林格

### 运行日志

[log1.txt](https://github.com/user-attachments/files/18218377/log1.txt)

**Comment by Paper-white** [comment]
可以提供一下自动战斗启动时一条龙页的截图或录屏吗？
另，牲鬼部分情况下无法被自动索敌锁定，并且满图乱飞，经常超出索敌攻击范围，有的脚本在无法锁定敌人时会停止攻击

**Comment by imx123** [comment]
https://github.com/user-attachments/assets/c9e62908-b63e-4b53-bf62-cc27f9abc843


https://github.com/user-attachments/assets/f27c3f54-3e20-420f-b69f-ded765955539
这两个视频是直接使用恶名狩猎的状况，由于有大小限制我就分了两个上传


![Snipaste_2024-12-24_22-14-34](https://github.com/user-attachments/assets/2a973b4d-700e-4d92-b10b-9e5625d969c5)
![Snipaste_2024-12-24_22-14-48](https://github.com/user-attachments/assets/76f0fac6-8c1d-4f0b-b28c-5fe0cdc5258e)
这两张图片是自动战斗时一条龙界面的截图

**Comment by DoctorReid** [comment]
可以先提高游戏画质，后续会有修复 #519
