### ISSUE TITLE
[问题反馈] [战斗助手] 每日刷本时的自动战斗加载脚本不是选择的脚本

### ISSUE THREAD

**Issue by qgu444** [DoctorReid/ZenlessZoneZero-OneDragon#524]
### 代码版本

b974f86

### 使用配置

专属配队-朱鸢

### 问题描述

每日刷本时的自动战斗加载脚本不是选择的脚本，选朱鸢的脚本但加载的是艾莲，但单独用自动战斗就还是可以。
（用了站场击破的脚本，加载时还是用的艾莲的。）

### 问题副本

代理人技能-火

### 游戏截图

![图片1](https://github.com/user-attachments/assets/91872498-fd30-49fa-974e-1623d69a23a3)
![图片2](https://github.com/user-attachments/assets/2b9b7221-4087-4ebb-9f6a-035402626624)

### 运行日志

[log.txt](https://github.com/user-attachments/files/18220888/log.txt)

**Comment by Paper-white** [comment]
自动战斗和一条龙是独立的两个功能，配置文件互不影响
一条龙功能的战斗脚本应该是在 `咖啡计划` 页面里选择的，而不是自动战斗页面

**Comment by qgu444** [comment]
我尝试了一下，咖啡计划里用朱鸢的脚本还是加载的艾连的

**Comment by qgu444** [comment]
好了，谢谢，解决了。是预备编队中选成艾连的了。
