### ISSUE TITLE
[问题反馈] [通用] 领取活跃度之后无法自动退出

### ISSUE THREAD

**Issue by Paper-white** [DoctorReid/ZenlessZoneZero-OneDragon#525]
### 代码版本

最新

## 多次收到来自群内玩家的反馈

> 领取完每日活跃奖励后无法自动退出，（不识别右边的退出键而是不停点左上角退出）你们有过这样的情况吗

### 游戏截图

![faef5bc0bcd658f6c844ef14c7adf157_720](https://github.com/user-attachments/assets/72bff416-45e5-414b-9c9e-97bbf0ed5a74)
![d561193efceb7882c05cb165add24c5f_720](https://github.com/user-attachments/assets/5b392545-0ee1-4812-9eff-1cd06758a3a9)

**Comment by DoctorReid** [comment]
新版逻辑已经解决这个了
