### ISSUE TITLE
[问题反馈] [战斗助手] 艾莲自动战斗更新zip失败

### ISSUE THREAD

**Issue by pwzdly** [DoctorReid/ZenlessZoneZero-OneDragon#526]
### 代码版本

b974f86

### 使用配置

专属配队-艾莲

### 问题描述

松开所有按键
开始下载 yolov8n-640-flash-1215 https://ghp.ci/https://github.com/DoctorReid/OneDragon-YOLO/releases/download/zzz_model/yolov8n-640-flash-1215.zip
下载失败模型失败 Traceback (most recent call last): File "urllib\request.py", line 1348, in do_open File "http\client.py", line 1303, in request File "http\client.py", line 1349, in _send_request File "http\client.py", line 1298, in endheaders File "http\client.py", line 1058, in _send_output File "http\client.py", line 996, in send File "http\client.py", line 1475, in connect File "ssl.py", line 517, in wrap_socket File "ssl.py", line 1104, in _create File "ssl.py", line 1382, in do_handshake ssl.SSLEOFError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "C:\english\ZenlessZoneZero-OneDragon-1.2.1\ZenlessZoneZero-OneDragon\src\one_dragon\yolo\onnx_model_loader.py", line 96, in download_model _, _ = urllib.request.urlretrieve(download_url, zip_file_path, log_download_progress) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "urllib\request.py", line 241, in urlretrieve File "urllib\request.py", line 216, in urlopen File "urllib\request.py", line 519, in open File "urllib\request.py", line 536, in _open File "urllib\request.py", line 496, in _call_chain File "urllib\request.py", line 1391, in https_open File "urllib\request.py", line 1351, in do_open urllib.error.URLError: 
模型 yolov8n-640-flash-1215 未下载成功 尝试使用备用模型 yolov8n-640-flash-0718
加载模型 C:\english\ZenlessZoneZero-OneDragon-1.2.1\ZenlessZoneZero-OneDragon\assets\models\flash_classifier\yolov8n-640-flash-0718\model.onnx
自动战斗配置加载成功 专属配队-艾莲
加载声音模板中
指令[ 自动战斗 ] 节点 加载自动战斗指令 返回状态 成功
加载声音模板完成
指令[ 自动战斗 ] 执行出错 相关截图保存至 AutoBattleApp_1734888972604 Traceback (most recent call last): File "C:\english\ZenlessZoneZero-OneDragon-1.2.1\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 295, in execute round_result: OperationRoundResult = self._execute_one_round() ^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\english\ZenlessZoneZero-OneDragon-1.2.1\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 367, in _execute_one_round current_round_result: OperationRoundResult = self._current_node.op_method(self) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\english\ZenlessZoneZero-OneDragon-1.2.1\ZenlessZoneZero-OneDragon\src\zzz_od\application\battle_assistant\auto_battle_app.py", line 90, in check_screen screen = self.screenshot() ^^^^^^^^^^^^^^^^^ File "C:\english\ZenlessZoneZero-OneDragon-1.2.1\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 468, in screenshot screen = self.ctx.controller.screenshot() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\english\ZenlessZoneZero-OneDragon-1.2.1\ZenlessZoneZero-OneDragon\src\one_dragon\base\controller\controller_base.py", line 59, in screenshot screen = self.get_screenshot(independent) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\english\ZenlessZoneZero-OneDragon-1.2.1\ZenlessZoneZero-OneDragon\src\one_dragon\base\controller\pc_controller_base.py", line 142, in get_screenshot screenshot = cv2.cvtColor(np.array(self.sct.grab(monitor)), cv2.COLOR_BGRA2RGB) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cv2.error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor' 
指令[ 自动战斗 ] 执行出错 相关截图保存至 AutoBattleApp_1734888972749 Traceback (most recent call last): File "C:\english\ZenlessZoneZero-OneDragon-1.2.1\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 295, in execute round_result: OperationRoundResult = self._execute_one_round() ^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\english\ZenlessZoneZero-OneDragon-1.2.1\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 367, in _execute_one_round current_round_result: OperationRoundResult = self._current_node.op_method(self) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\english\ZenlessZoneZero-OneDragon-1.2.1\ZenlessZoneZero-OneDragon\src\zzz_od\application\battle_assistant\auto_battle_app.py", line 90, in check_screen screen = self.screenshot() ^^^^^^^^^^^^^^^^^ File "C:\english\ZenlessZoneZero-OneDragon-1.2.1\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 468, in screenshot screen = self.ctx.controller.screenshot() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\english\ZenlessZoneZero-OneDragon-1.2.1\ZenlessZoneZero-OneDragon\src\one_dragon\base\controller\controller_base.py", line 59, in screenshot screen = self.get_screenshot(independent) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\english\ZenlessZoneZero-OneDragon-1.2.1\ZenlessZoneZero-OneDragon\src\one_dragon\base\controller\pc_controller_base.py", line 142, in get_screenshot screenshot = cv2.cvtColor(np.array(self.sct.grab(monitor)), cv2.COLOR_BGRA2RGB) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cv2.error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor' 
指令[ 自动战斗 ] 执行出错 相关截图保存至 AutoBattleApp_1734888972829 Traceback (most recent call last): File "C:\english\ZenlessZoneZero-OneDragon-1.2.1\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 295, in execute round_result: OperationRoundResult = self._execute_one_round() ^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\english\ZenlessZoneZero-OneDragon-1.2.1\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 367, in _execute_one_round current_round_result: OperationRoundResult = self._current_node.op_method(self) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\english\ZenlessZoneZero-OneDragon-1.2.1\ZenlessZoneZero-OneDragon\src\zzz_od\application\battle_assistant\auto_battle_app.py", line 90, in check_screen screen = self.screenshot() ^^^^^^^^^^^^^^^^^ File "C:\english\ZenlessZoneZero-OneDragon-1.2.1\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 468, in screenshot screen = self.ctx.controller.screenshot() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\english\ZenlessZoneZero-OneDragon-1.2.1\ZenlessZoneZero-OneDragon\src\one_dragon\base\controller\controller_base.py", line 59, in screenshot screen = self.get_screenshot(independent) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\english\ZenlessZoneZero-OneDragon-1.2.1\ZenlessZoneZero-OneDragon\src\one_dragon\base\controller\pc_controller_base.py", line 142, in get_screenshot screenshot = cv2.cvtColor(np.array(self.sct.grab(monitor)), cv2.COLOR_BGRA2RGB) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cv2.error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor' 
指令[ 自动战斗 ] 执行出错 相关截图保存至 AutoBattleApp_1734888972904 Traceback (most recent call last): File "C:\english\ZenlessZoneZero-OneDragon-1.2.1\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 295, in execute round_result: OperationRoundResult = self._execute_one_round() ^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\english\ZenlessZoneZero-OneDragon-1.2.1\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 367, in _execute_one_round current_round_result: OperationRoundResult = self._current_node.op_method(self) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\english\ZenlessZoneZero-OneDragon-1.2.1\ZenlessZoneZero-OneDragon\src\zzz_od\application\battle_assistant\auto_battle_app.py", line 90, in check_screen screen = self.screenshot() ^^^^^^^^^^^^^^^^^ File "C:\english\ZenlessZoneZero-OneDragon-1.2.1\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 468, in screenshot screen = self.ctx.controller.screenshot() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\english\ZenlessZoneZero-OneDragon-1.2.1\ZenlessZoneZero-OneDragon\src\one_dragon\base\controller\controller_base.py", line 59, in screenshot screen = self.get_screenshot(independent) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\english\ZenlessZoneZero-OneDragon-1.2.1\ZenlessZoneZero-OneDragon\src\one_dragon\base\controller\pc_controller_base.py", line 142, in get_screenshot screenshot = cv2.cvtColor(np.array(self.sct.grab(monitor)), cv2.COLOR_BGRA2RGB) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cv2.error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor' 
指令[ 自动战斗 ] 执行失败 返回状态 异常
暂停运行
停止运行
松开所有按键

### 问题副本

第三章开拓新道路一

**Comment by DoctorReid** [comment]
QQ群里下载模型吧

**Comment by pwzdly** [comment]
> QQ群里下载模型吧
已申请进入qq群,求同意

**Comment by pwzdly** [comment]
> QQ群里下载模型吧

已申请进入qq群,求同意
