### ISSUE TITLE
[问题反馈] [通用] 录像店经营

### ISSUE THREAD

**Issue by ReFenter** [DoctorReid/ZenlessZoneZero-OneDragon#530]
### 代码版本

15039be

### 问题描述

录像店经营选不到朱鸢，别的人物没试过

### 游戏截图

![4fec8792ec69f6de9b1173223f8987c1](https://github.com/user-attachments/assets/dc74f10e-229e-4d5c-b59c-8cae03fbdf2e)
![23d45f525ec9bc868f3a702f7a9ac002](https://github.com/user-attachments/assets/ad56154d-edf9-4ac2-9cb3-83ae17dcdb64)

### 运行日志

[log.txt](https://github.com/user-attachments/files/18234798/log.txt)

**Comment by DoctorReid** [comment]
选不到就换妮可
