### ISSUE TITLE
[问题反馈] [通用] 

### ISSUE THREAD

**Issue by slr7792301** [DoctorReid/ZenlessZoneZero-OneDragon#541]
### 代码版本

bcb2e26

### 问题描述

近期频发体力计划卡在选择配队画面，画面下滑疑似未能找到配队就停住了。（其他日常功能正常，咖啡店超时传送已有看到修正更新）
字体选项 - 原先是推荐方案，正常运行数周，近期出现问题后已有尝试过更改为细体，无改善。
图像大小 - 原先是1280x720正常运行，前段时间出现问题修改为1600x900，没有改善（仍会偶尔出现该问题），今天第一次出现“点击非游戏窗口区域”提示（期间完全无移动鼠标），并且自动体力计划一定失败，不会成功，尝试改为1920x1080，无改善。

### 游戏截图

![_1735144708600](https://github.com/user-attachments/assets/8a400674-f8bc-4ce3-8b4b-a3f89f333d69)

### 运行日志

[log.txt](https://github.com/user-attachments/files/18246685/log.txt)

### 你的建议

暂时没有想法，已尝试过修改编队名称，没有改善，原先是预设的编队 1/2/3/4，出现问题后改名为雅露柏&艾狼苍&... / 一&二&三&四 / 1&2&3&4 等试图简化匹配难度都没有效果。
![111](https://github.com/user-attachments/assets/e0c0dd59-738d-4987-8e57-e08e16299dd0)

**Comment by DoctorReid** [comment]
`点击非游戏窗口区域` 是因为识别到队伍名右边的数字了，可以忽略。

试了你的截图没有问题，1920 + 细体 + 改名，肯定能解决的，看看哪里搞错了

**Comment by slr7792301** [comment]
好的，感谢测试，我再检查看看设置然后观察情况，谢谢。
