### ISSUE TITLE
[问题反馈] [通用] 式舆防卫战

### ISSUE THREAD

**Issue by FredNone** [DoctorReid/ZenlessZoneZero-OneDragon#547]
### 代码版本

48072ae

### 问题描述

在运行式舆防卫战时会遇到无法正确切换的问题。
一条龙提示如图一
页面停留状态如图2

### 游戏截图

![图片](https://github.com/user-attachments/assets/93624ac0-e4e1-4749-b08f-567a9f03a91d)
![图片](https://github.com/user-attachments/assets/eb133157-020a-4f8d-98ad-5e8349caa96c)

### 运行日志

[log.txt](https://github.com/user-attachments/files/18257224/log.txt)

### 你的建议

可能是游戏版本更新导致切换打开关卡集成中心的界面与原来不同，可能需要修改一部分CV检测逻辑。

**Comment by FredNone** [comment]
目前零号空洞的快捷手册检测也存在异常。
![图片](https://github.com/user-attachments/assets/86a3918c-4e66-4f53-b5a5-2f3e55d6fc7b)
[
![_1735272096872](https://github.com/user-attachments/assets/6074f28e-6ba3-4add-8332-0a0d1188226f)
](url)

**Comment by Paper-white** [comment]
问题已复现，已确定原因
#546 同样问题

这个按钮在之前版本是 “挑战” 现在改为了 “作战”

![image](https://github.com/user-attachments/assets/bbb6d6e4-2074-470b-af61-794e5da83b92)

**Comment by FredNone** [comment]
感谢。Thanks
