### ISSUE TITLE
[问题反馈] [建议] 用的鸣潮的一个脚本可以后台点击，不知道给一条龙参考一下

### ISSUE THREAD

**Issue by deYangar** [DoctorReid/ZenlessZoneZero-OneDragon#549]
### 代码版本

48072ae

### 问题描述
这是鸣潮的脚本
https://github.com/ok-oldking/ok-wuthering-waves
他的后台点击参考的是这个项目
https://github.com/lazydog28/mc_auto_boss

**Comment by 2375399351** [comment]
这个问题好像最早作者就解释过了，好像是没办法这么操作的，不知道有没有记错
