### ISSUE TITLE
[问题反馈] [通用] python第三方包路径异常

### ISSUE THREAD

**Issue by mianb** [DoctorReid/ZenlessZoneZero-OneDragon#550]
### 代码版本

1.21

### 问题描述

安装requirement的时候路径异常

### 运行日志

WARNING: Building wheel for pymsgbox failed: [WinError 123] ļĿ¼﷨ȷ: 'd:\\zenlesszonezero-onedragon\\d:'
WARNING: Building wheel for pyperclip failed: [WinError 123] ļĿ¼﷨ȷ: 'd:\\zenlesszonezero-onedragon\\d:'
WARNING: Building wheel for pyrect failed: [WinError 123] ļĿ¼﷨ȷ: 'd:\\zenlesszonezero-onedragon\\d:'
WARNING: Building wheel for pyscreeze failed: [WinError 123] ļĿ¼﷨ȷ: 'd:\\zenlesszonezero-onedragon\\d:'
WARNING: Building wheel for pytweening failed: [WinError 123] ļĿ¼﷨ȷ: 'd:\\zenlesszonezero-onedragon\\d:'
Failed to build mouseinfo pyautogui pygetwindow pymsgbox pyperclip pyrect pyscreeze pytweening
WARNING: There was an error checking the latest version of pip.
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (mouseinfo, pyautogui, pygetwindow, pymsgbox, pyperclip, pyrect, pyscreeze, pytweening)

**Comment by DoctorReid** [comment]
自行gpt解决
