### ISSUE TITLE
[问题反馈] [零号空洞] 

### ISSUE THREAD

**Issue by FengYuanWanyeY** [DoctorReid/ZenlessZoneZero-OneDragon#553]
### 代码版本

48072ae

### 问题描述

指令[ 零号空洞 ] 节点 初始画面识别 返回状态 信息
指令[ 传送 快捷手册 挑战-零号空洞-枯萎之都 ] 节点 检测游戏窗口 返回状态 成功
指令[ 打开快捷手册 ] 节点 检测游戏窗口 返回状态 成功
指令[ 打开菜单 ] 节点 检测游戏窗口 返回状态 成功
指令[ 打开菜单 ] 节点 画面识别 返回状态 信息
指令[ 打开菜单 ] 节点 点击菜单 返回状态 成功
指令[ 打开菜单 ] 节点 画面识别 返回状态 成功
指令[ 打开菜单 ] 执行成功 返回状态 成功
指令[ 打开快捷手册 ] 节点 打开菜单 返回状态 成功
指令[ 打开快捷手册 ] 节点 点击更多 返回状态 快捷手册
指令[ 打开快捷手册 ] 执行成功 返回状态 快捷手册
指令[ 传送 快捷手册 挑战-零号空洞-枯萎之都 ] 节点 快捷手册 返回状态 快捷手册
指令[ 传送 快捷手册 挑战-零号空洞-枯萎之都 ] 节点 选择TAB 返回状态 无法从 快捷手册-训练 前往 快捷手册-挑战
指令[ 传送 快捷手册 挑战-零号空洞-枯萎之都 ] 执行失败 返回状态 无法从 快捷手册-训练 前往 快捷手册-挑战
指令[ 零号空洞 ] 节点 传送 返回状态 无法从 快捷手册-训练 前往 快捷手册-挑战
指令[ 零号空洞 ] 执行失败 返回状态 无法从 快捷手册-训练 前往 快捷手册-挑战
暂停运行
停止运行

### 问题副本

零号空洞

**Comment by DoctorReid** [comment]
更新代码
