### ISSUE TITLE
[问题反馈] [通用]  一条龙体力刷本失败

### ISSUE THREAD

**Issue by KENT525107** [DoctorReid/ZenlessZoneZero-OneDragon#554]
### 代码版本

ca08f04

### 问题描述

每日一条龙运行时，进入体力刷本环节，无法正常进行

### 游戏截图

![2024128](https://github.com/user-attachments/assets/7ee03e0b-89ca-4565-b53c-fb39c1e382ba)
![20241228](https://github.com/user-attachments/assets/7481b210-394e-436a-a0a2-a48521a5010b)
运行脚本时会在这俩个界面反复横跳

### 运行日志

[Uploading python_10.05.log…]()

**Comment by DoctorReid** [comment]
更新代码试试
