### ISSUE TITLE
[问题反馈] [通用] [群员反馈] 手册"挑战"改"作战" 更新代码后依旧无法识别

### ISSUE THREAD

**Issue by Paper-white** [DoctorReid/ZenlessZoneZero-OneDragon#555]
### 代码版本

e6ce1fe

### 问题描述

问题来源：群友反馈，未成功复现

脚本更新后日志依旧会去寻找“挑战”而非“作战”
已检查本地文件，查看本地文件成功同步最新代码

### 游戏截图

![image](https://github.com/user-attachments/assets/d227ef64-ec9b-4a7c-a778-61b0037eab67)
![0152699c432ca3bc071afa5be95ce7fa](https://github.com/user-attachments/assets/d0ffd86f-1d86-4db6-9ba9-3426c17fb560)
![4c87b89c5a32186d023a4f8c87a3ad29](https://github.com/user-attachments/assets/7e22d768-bf5b-4ec5-8e60-72e579f2033f)

图片来自于群聊文件

### 你的建议

已测试以下方案：
重启脚本即电脑 未解决
启用强制更新 未解决
回滚后手动修改本地文件 解决?（部分用户解决，部分用户未解决）

完全删除代码后重新安装 成功解决

**Comment by DoctorReid** [comment]
config文件夹下，搜索删除 notorious_hunt.yml

例如 config/01/notorious_hunt.yml
