### ISSUE TITLE
[问题反馈] [零号空洞] 

### ISSUE THREAD

**Issue by zghliang** [DoctorReid/ZenlessZoneZero-OneDragon#557]
### 代码版本

1.2.1

### 问题描述

刷零号业绩无法进入副本

### 问题副本

零号空洞-旧都列车-前线

### 游戏截图

![_1735456881260](https://github.com/user-attachments/assets/1a907bc1-156b-4b0c-b506-8d7590ef4d42)

### 运行日志

指令[ 传送 快捷手册 挑战-零号空洞-旧都列车 ] 节点 选择TAB 返回状态 成功
指令[ 快捷手册 选择分类 零号空洞 ] 节点 检测游戏窗口 返回状态 成功
指令[ 快捷手册 选择分类 零号空洞 ] 节点 选择分类 返回状态 成功
指令[ 快捷手册 选择分类 零号空洞 ] 执行成功 返回状态 成功
指令[ 传送 快捷手册 挑战-零号空洞-旧都列车 ] 节点 选择分类 返回状态 成功
指令[ 快捷手册 选择副本类型 旧都列车 ] 节点 检测游戏窗口 返回状态 成功
指令[ 快捷手册 选择副本类型 旧都列车 ] 节点 选择副本 返回状态 找不到 旧都列车
指令[ 快捷手册 选择副本类型 旧都列车 ] 节点 选择副本 返回状态 找不到 旧都列车
指令[ 快捷手册 选择副本类型 旧都列车 ] 节点 选择副本 返回状态 找不到 旧都列车
指令[ 快捷手册 选择副本类型 旧都列车 ] 节点 选择副本 返回状态 找不到 旧都列车
指令[ 快捷手册 选择副本类型 旧都列车 ] 节点 选择副本 返回状态 找不到 旧都列车

**Comment by Paper-white** [comment]
1.2.1是什么鬼代码版本

请确保你使用的新版本代码
