### ISSUE TITLE
[问题反馈] [零号空洞] 

### ISSUE THREAD

**Issue by LittleDarkZero** [DoctorReid/ZenlessZoneZero-OneDragon#563]
### 代码版本

ea19489

### 问题描述

1.无法识别战斗结束，直到画面中出现xxxx-入口
2.限时、无伤关卡会有一个通知交互页面，没有设定相应的反应会卡住
3.进入下层后无法识别障碍物，只能走直线，且过程中只要交互按钮亮了就会按下去，可能会和角色反复对话。

### 问题副本

迷失之地(测试)-战线肃清

### 游戏截图

忘记截图了

### 运行日志

[log.txt](https://github.com/user-attachments/files/18270598/log.txt)

### 你的建议

1.战斗结束后右上角fairy会说话，以这个作为战斗结束的信号
2.增加一个判定，点击确定
3.可以先执行一个固定路线，与主c对话-移动绕过障碍物-奥菲莉亚对话；能交互图标才会变大，其他情况图标大小不变，图标的大小作为有没有到达指定地点的依据并增加一个判定，防止在移动过程中和角色发生对话卡死。

**Comment by LittleDarkZero** [comment]
![image](https://github.com/user-attachments/assets/d828e93e-4472-4a6d-b8ac-2a4944418444)
fairy说话图片

**Comment by LittleDarkZero** [comment]
![image](https://github.com/user-attachments/assets/fb98d455-16c1-4ba4-acc1-9c1e401da20a)

**Comment by LittleDarkZero** [comment]
![image](https://github.com/user-attachments/assets/94ca2801-1320-44cc-83f0-61fec4f1e7f2)
![image](https://github.com/user-attachments/assets/3a8aa7e4-632f-45e4-a8d3-c012f12540d8)
![image](https://github.com/user-attachments/assets/c69a669e-db80-4898-b73b-4fb80a7d9ae8)
图标大小与距离无关，仅当交互按钮亮了才会变大

**Comment by LittleDarkZero** [comment]
https://github.com/user-attachments/assets/55a2eea6-ffdd-4a2e-8931-21a260b4cc83

可以以这个路径去走

**Comment by DoctorReid** [comment]
除了固定路径，其他逻辑都有

1. Fairy提示可能时间较短，没捕捉到
2. 局内直接运行是识别不到，之后修复
3. 识别不了障碍物

**Comment by LittleDarkZero** [comment]
那关于图标大小的识别会有吗，我觉得这个是一个很好的托底判定（不一定适用所有情况，但绝大多数的问题应该能够识别），这个游戏里任何一种交互都有类似的存在。比如用来识别怪物是否在攻击范围内、人物有没有走到指定的交互地点等等。。。

**Comment by DoctorReid** [comment]
图标大小有的

**Comment by DoctorReid** [comment]
更新代码试试，有好建议再额外开一个issue
