### ISSUE TITLE
[问题反馈] [通用] 

### ISSUE THREAD

**Issue by pretentiously** [DoctorReid/ZenlessZoneZero-OneDragon#564]
### 代码版本

ea19489

### 问题描述

恶名狩猎功能在入口选择时发生错误，经询问群里小伙伴，该问题为部分使用者会出现的问题
在选择恶名狩猎功能后会错误跳转到冒险手册中的-训练界面；而非正确的冒险手册-作战界面，从而找不到正确恶名狩猎入口，本次问题发现是在今日更新（12.30）之后发现的

### 游戏截图

![_1735521918468](https://github.com/user-attachments/assets/a587c774-a0b1-433f-81e8-c903e463d295)

### 运行日志

[log.txt](https://github.com/user-attachments/files/18271450/log.txt)

### 你的建议

我猜是大概某个代码没修改

**Comment by DoctorReid** [comment]
#555 

config文件夹下，搜索删除 notorious_hunt.yml

例如 config/01/notorious_hunt.yml

**Comment by pretentiously** [comment]
替大佬补充两点，一是记得重启生效，二是记得检查一下计划设置
