### ISSUE TITLE
[问题反馈] [通用] 卡在快捷手册区域显示未识别画面

### ISSUE THREAD

**Issue by AnonCN** [DoctorReid/ZenlessZoneZero-OneDragon#566]
### 代码版本

ea19489

### 问题描述

如图
![_1735535239649](https://github.com/user-attachments/assets/187caaa1-3a56-418e-a037-0cf1d31e2beb)
脚本卡在此区域不动

游戏分辨率2560*1440

### 游戏截图

![_1735535239649](https://github.com/user-attachments/assets/4d26d0bc-f427-401b-8c38-3cd8d7d6bcbe)
![QQ_1735535398365](https://github.com/user-attachments/assets/f3805a4f-7fa2-4501-88a1-12ad05550a75)

### 运行日志

[log.txt](https://github.com/user-attachments/files/18272123/log.txt)

**Comment by DoctorReid** [comment]
F11 纯游戏画面上传一下

**Comment by AnonymousWMS** [comment]
> F11 纯游戏画面上传一下

纯游戏画面为第二张图

**Comment by AnonymousWMS** [comment]
> F11 纯游戏画面上传一下

第二张就是纯游戏画面[第一张F11，第二张纯游戏截图]
[我和AnoCN是同一个人]

**Comment by AnonymousWMS** [comment]
![image](https://github.com/user-attachments/assets/9df514a1-706b-42e1-be22-d3b3b4e2a597)

**Comment by AnonymousWMS** [comment]
https://github.com/user-attachments/assets/24e2f268-eba6-46be-a486-7f76c3a8bc05

视频复现

**Comment by DoctorReid** [comment]
F11 纯游戏截图，不要遮挡游戏画面，不要带窗口边框，手册上每个tab都截一张图吧

**Comment by AnonymousWMS** [comment]
> F11 纯游戏截图，不要遮挡游戏画面，不要带窗口边框，手册上每个tab都截一张图吧

稍后，我这里过完剧情后提交[能否在qq上聊？我这里上git需要翻墙有点麻烦，我已经通过qq群联系您了]

**Comment by AnonymousWMS** [comment]
已解决
