### ISSUE TITLE
[问题反馈] [通用] 

### ISSUE THREAD

**Issue by fymq** [DoctorReid/ZenlessZoneZero-OneDragon#568]
### 代码版本

e6ce1fe

### 问题描述

1运行一条龙的恶名狩猎，在快捷手册还是在识别挑战选项卡

### 游戏截图

<img width="679" alt="屏幕截图 2024-12-30 181243" src="https://github.com/user-attachments/assets/b7b08c5c-5d40-4a4f-8889-d8c422c546f4" />

**Comment by DoctorReid** [comment]
#555 

config文件夹下，搜索删除 notorious_hunt.yml

例如 config/01/notorious_hunt.yml

**Comment by fymq** [comment]
OK，解决了
