### ISSUE TITLE
[问题反馈] [零号空洞] 选择事件未识别导致空洞任务跳出

### ISSUE THREAD

**Issue by farhair** [DoctorReid/ZenlessZoneZero-OneDragon#569]
### 代码版本

ea19489

### 问题描述

未识别选择，程序跳出

### 问题副本

迷失之地

### 游戏截图

![_1735561969267](https://github.com/user-attachments/assets/a9c8be0f-77d3-4600-93ae-e805709592a1)
![_1735561996810](https://github.com/user-attachments/assets/fdb2fa13-57c0-45f6-b896-74c57566115d)

### 运行日志

[log.txt](https://github.com/user-attachments/files/18274634/log.txt)

**Comment by DoctorReid** [comment]
已知 等会修复
