### ISSUE TITLE
[问题反馈] [零号空洞] 

### ISSUE THREAD

**Issue by JzCherry** [DoctorReid/ZenlessZoneZero-OneDragon#570]
### 代码版本

ea19489

### 问题描述

开局选战备和角色buff的时候只选了战备，角色buff来来回回选不到

### 问题副本

迷失之地空洞

### 游戏截图

![_1735561953124](https://github.com/user-attachments/assets/aaeb7ce3-76ec-43a3-9226-e873f565a79f)

### 运行日志

[log.txt](https://github.com/user-attachments/files/18274643/log.txt)

**Comment by DoctorReid** [comment]
更新代码再试试，有问题再上传视频
