### ISSUE TITLE
[问题反馈] [零号空洞] 中场休息卡在桌子附近

### ISSUE THREAD

**Issue by farhair** [DoctorReid/ZenlessZoneZero-OneDragon#571]
### 代码版本

ea19489

### 问题描述

中场休息卡在桌子附近

### 问题副本

迷失之地

### 游戏截图

https://github.com/user-attachments/assets/954504bb-2b9a-4a75-95fb-1ffeaad2b164

**Comment by DoctorReid** [comment]
这种左右转动 识别不到的可以F11上传截图到群里 或者到这里，视频就不用传了，模型会慢慢优化
