### ISSUE TITLE
[问题反馈] [零号空洞] 选择战备和鸣徽的建议

### ISSUE THREAD

**Issue by JzCherry** [DoctorReid/ZenlessZoneZero-OneDragon#573]
### 代码版本

ea19489

### 问题描述

开局选战备的时候希望可以优先选左上角没有数字的战备，选鸣徽的时候可以先选有对应战备的鸣徽，这样方便刷任务

### 问题副本

空洞迷失之地

### 游戏截图

![_1735562605890](https://github.com/user-attachments/assets/f6c440f2-4cb6-4319-91d9-2e6ab4c94097)
![_1735562748467](https://github.com/user-attachments/assets/fe4a85d1-5b70-478d-9741-ed5494ff1865)

### 运行日志

[log.txt](https://github.com/user-attachments/files/18274693/log.txt)

**Comment by DoctorReid** [comment]
试了下 zzz的字体太疼了，对这个数字识别效果很差。

现在支持优先级配置了，多改改配置刷刷就都有了，不打算额外支持了
