### ISSUE TITLE
[问题反馈] [通用] 更新以后，恶名狩猎仍然选择“挑战“而非”作战“

### ISSUE THREAD

**Issue by f59375543** [DoctorReid/ZenlessZoneZero-OneDragon#576]
### 代码版本

ea19489

### 问题描述

已经更新到最新版本，确定更新了修改”作战“的更新，然而使用恶名狩猎的时候，仍然是在寻找“挑战“

### 游戏截图

![20241230235319](https://github.com/user-attachments/assets/e52b67c5-b47a-43e5-aa60-3167dfeec6d2)
![20241230235356](https://github.com/user-attachments/assets/111b21f1-7e3b-4a87-9e82-b33d7f6e656c)

### 运行日志

[log.txt](https://github.com/user-attachments/files/18276091/log.txt)

**Comment by meiszzz** [comment]
解决方法已有
https://github.com/DoctorReid/ZenlessZoneZero-OneDragon/issues/555
config文件夹下，搜索删除 notorious_hunt.yml
例如 config/01/notorious_hunt.yml
