### ISSUE TITLE
[问题反馈] [战斗助手] Ver2.1通配 雅蓄力普攻存在切换过快

### ISSUE THREAD

**Issue by YumChin4314** [DoctorReid/ZenlessZoneZero-OneDragon#578]
### 代码版本

e6ce1fe

### 使用配置

通用配对，队伍构成：雅-露西-苍角

### 问题描述

星见 雅6点能量蓄力普攻存在切换过快导致无法触发第二段伤害出现。

### 问题副本

施工废墟-内部

**Comment by DoctorReid** [comment]
更新再试试，有问题再附带视频到QQ群找遥酱看看
