### ISSUE TITLE
[问题反馈] [零号空洞] 

### ISSUE THREAD

**Issue by LittleDarkZero** [DoctorReid/ZenlessZoneZero-OneDragon#579]
### 代码版本

281f602

### 问题描述

无法识别布林格的战斗流程

### 问题副本

迷失之地

### 你的建议

先不考虑没及时击破，进入动画的情况：
整个布林格的战斗流程可分为三个部分：一阶段-手(若未及时击破会动画)-二阶段。
1.一阶段结束后怪物会离开场地，按下锁定键也不会出现圆圈/右上角血条消失，选一个作为一阶段结束的信号；
2.一阶段结束，停止自动战斗，让人物前往指定区域等待直到手的血条出现，开始自动战斗直到战斗结束。
![image](https://github.com/user-attachments/assets/9ec19a90-4b0c-48ab-814d-d48fa6f6eeea)

**Comment by LittleDarkZero** [comment]
如果暂时没有好的办法去识别手的血条，可以按照时间来触发第二次自动战斗的开启时间。
一阶段结束到手的血条出现当中间隔差不多是20s，考虑到可能没及时识别到一阶段结束可以把这个时间适当减少。

**Comment by LittleDarkZero** [comment]
所以最主要的问题就在于如何移动到图中所示的地方了，一阶段结束人物可能在地图的任何一个地方，而且这个地方也没有特别醒目的图标标识(难道是铁板上的那个圆吗)。

**Comment by DoctorReid** [comment]
这部分不打算做特殊兼容了，主要也是最后一点移动做不到。练度上去之后，也就是多等待大概半分钟的boss动画，反正都是自动
