### ISSUE TITLE
支持零号空洞

### ISSUE THREAD

**Issue by DoctorReid** [DoctorReid/ZenlessZoneZero-OneDragon#58]

**Comment by Small-Ku** [comment]
![switch_1724002558011](https://github.com/user-attachments/assets/3a6ab2b6-4ac2-42fc-b418-89c42c2b2b0e)
![switch_1724002399233](https://github.com/user-attachments/assets/dc49a677-d647-40f4-acd1-b2258365b0f2)
這兩個事件貌似還是卡住了

**Comment by DoctorReid** [comment]
换人的选项，后续是怎么样的，是地图上出现2个呼叫增援的格子吗

**Comment by DoctorReid** [comment]
后续可以Q群里同步哈，看到的话就立刻修复

**Comment by Small-Ku** [comment]
> 换人的选项，后续是怎么样的，是地图上出现2个呼叫增援的格子吗

是的

> 后续可以Q群里同步哈，看到的话就立刻修复

沒有 QQ，之前用 Icallingua++ 被封了，自助解鎖不能用回鄉證
