### ISSUE TITLE
[问题反馈] [通用] 刮刮卡 - 叫醒他

### ISSUE THREAD

**Issue by DabengBa** [DoctorReid/ZenlessZoneZero-OneDragon#61]
### 问题描述

![image](https://github.com/user-attachments/assets/a37e10ec-a52a-439a-bb62-9381d8299d17)

![image](https://github.com/user-attachments/assets/bdb5e215-b955-47cf-bb32-30d1b16ceb00)

![image](https://github.com/user-attachments/assets/9d77cec7-1964-4da5-844c-139c88ebce23)

**Comment by DoctorReid** [comment]
需要完整的截图才行。。

**Comment by DabengBa** [comment]
> 需要完整的截图才行。。

啊, 我还以为是文字识别知道文字就行了. 那我下次遇到再试试.

**Comment by XerxesLee** [comment]
好像是晚上深夜触发狗狗睡觉

**Comment by DoctorReid** [comment]
> 好像是晚上深夜触发狗狗睡觉

好，之后试试

**Comment by MomentDerek** [comment]
这里补充1080p下的截图
![_1724269906511](https://github.com/user-attachments/assets/62e6c6b0-41b4-4ce3-a5ff-c8f30f2760b1)
