### ISSUE TITLE
[问题反馈] 启动失败

### ISSUE THREAD

**Issue by ahahna** [DoctorReid/ZenlessZoneZero-OneDragon#65]
### 问题描述

启动失败，点击启动一条龙之后出现如图所示，我很抱歉，我不知道这是不是我的问题，但以我浅薄的经验不能完全理解搜索结果中的解决方案，请求帮助

1.初次启动
2.已经重复卸载安装几次，故障依旧

### 游戏截图

![屏幕截图 2024-08-11 233103](https://github.com/user-attachments/assets/62471fbb-e4bb-4692-8ea2-43cac2ee2669)
![屏幕截图 2024-08-11 233902](https://github.com/user-attachments/assets/2f3100b3-341f-4ba6-9b98-26135f179e51)

### 运行日志

[log.txt](https://github.com/user-attachments/files/16574230/log.txt)

**Comment by DoctorReid** [comment]
可以看看 env.bat 里是什么内容。
或者文件夹不要有空格试试

**Comment by ahahna** [comment]
是的，我把它放到没有空格的文件夹里面就可以运行了，非常感谢！
