### ISSUE TITLE
[问题反馈] [通用] 希望支持咖啡店

### ISSUE THREAD

**Issue by szyandzxy** [DoctorReid/ZenlessZoneZero-OneDragon#74]
### 问题描述

咖啡店作为每日内容的一环希望可以支持，60体力也很重要。
除特殊活动外，周一到周日每日咖啡固定顺序刷新。
不提供选项默认吃第一个咖啡也可以。

**Comment by szyandzxy** [comment]
OK -前面是咖啡原名包含括号 -后面是游戏内实际掉落100%的内容

周一、周四：
六杯咖啡
上面三杯从左至右：红茶拿提-强攻认证章，麦草拿提（淡）-引燃战术芯片，空泡魔咔（淡）-防护组件
下面三杯从左至右：果泡拿提（淡）-防护认证章，月壤魔咔-强攻组件，新艾利都特调-无额外掉落

周二、周五：
六杯咖啡
上面三杯从左至右：月壤魔咔（淡）-击破组件，麦草拿提（浓）-冰结战术芯片，月壤魔咔（浓）-异常组件
下面三杯从左至右：红茶拿提（浓）-异常认证章，月壤魔咔（淡）-击破组件，新艾利都特调-无额外掉落

周三、周六：
六杯咖啡
上面三杯从左至右：果泡拿提-支援认证章，胡椒拿提-电击战术芯片，空泡魔咔-支援组件
下面三杯从左至右：麦草拿提-物理战术芯片，胡椒拿提（淡）-以太战术芯片，新艾利都特调-无额外掉落

周日：全解锁
十六杯咖啡 第一页只能展示十杯咖啡（上五下五），注意需要向左滑动才能翻到第二页
上面八杯从左至右：红茶拿提-强攻认证章，红茶拿提（浓）-异常认证章，果泡拿提（淡）-防护认证章，麦草拿提（淡）-引燃战术芯片，胡椒拿提-电击战术芯片，月壤魔咔-强攻组件，月壤魔咔（淡）-击破组件，空泡魔咔（淡）-防护组件
下面八杯从左至右：红茶拿提（淡）-击破认证章，果泡拿提-支援认证章，麦草拿提-物理战术芯片，麦草拿提（浓）-冰结战术芯片，胡椒拿提（淡）-以太战术芯片，月壤魔咔（浓）-异常组件，空泡魔咔-支援组件，新艾利都特调-无额外掉落

**Comment by szyandzxy** [comment]
> OK -前面是咖啡原名包含括号 -后面是游戏内实际掉落100%的内容
> 
> 周一、周四： 六杯咖啡 上面三杯从左至右：红茶拿提-强攻认证章，麦草拿提（淡）-引燃战术芯片，空泡魔咔（淡）-防护组件 下面三杯从左至右：果泡拿提（淡）-防护认证章，月壤魔咔-强攻组件，新艾利都特调-无额外掉落
> 
> 周二、周五： 六杯咖啡 上面三杯从左至右：月壤魔咔（淡）-击破组件，麦草拿提（浓）-冰结战术芯片，月壤魔咔（浓）-异常组件 下面三杯从左至右：红茶拿提（浓）-异常认证章，月壤魔咔（淡）-击破组件，新艾利都特调-无额外掉落
> 
> 周三、周六： 六杯咖啡 上面三杯从左至右：果泡拿提-支援认证章，胡椒拿提-电击战术芯片，空泡魔咔-支援组件 下面三杯从左至右：麦草拿提-物理战术芯片，胡椒拿提（淡）-以太战术芯片，新艾利都特调-无额外掉落
> 
> 周日：全解锁 十六杯咖啡 第一页只能展示十杯咖啡（上五下五），注意需要向左滑动才能翻到第二页 上面八杯从左至右：红茶拿提-强攻认证章，红茶拿提（浓）-异常认证章，果泡拿提（淡）-防护认证章，麦草拿提（淡）-引燃战术芯片，胡椒拿提-电击战术芯片，月壤魔咔-强攻组件，月壤魔咔（淡）-击破组件，空泡魔咔（淡）-防护组件 下面八杯从左至右：红茶拿提（淡）-击破认证章，果泡拿提-支援认证章，麦草拿提-物理战术芯片，麦草拿提（浓）-冰结战术芯片，胡椒拿提（淡）-以太战术芯片，月壤魔咔（浓）-异常组件，空泡魔咔-支援组件，新艾利都特调-无额外掉落

**Comment by szyandzxy** [comment]
> 居然是默认的吗，能不能帮忙列举一下

OK -前面是咖啡原名包含括号 -后面是游戏内实际掉落100%的内容

周一、周四：
六杯咖啡
上面三杯从左至右：红茶拿提-强攻认证章，麦草拿提（淡）-引燃战术芯片，空泡魔咔（淡）-防护组件
下面三杯从左至右：果泡拿提（淡）-防护认证章，月壤魔咔-强攻组件，新艾利都特调-无额外掉落

周二、周五：
六杯咖啡
上面三杯从左至右：月壤魔咔（淡）-击破组件，麦草拿提（浓）-冰结战术芯片，月壤魔咔（浓）-异常组件
下面三杯从左至右：红茶拿提（浓）-异常认证章，月壤魔咔（淡）-击破组件，新艾利都特调-无额外掉落

周三、周六：
六杯咖啡
上面三杯从左至右：果泡拿提-支援认证章，胡椒拿提-电击战术芯片，空泡魔咔-支援组件
下面三杯从左至右：麦草拿提-物理战术芯片，胡椒拿提（淡）-以太战术芯片，新艾利都特调-无额外掉落

周日：全解锁
十六杯咖啡 第一页只能展示十杯咖啡（上五下五），注意需要向左滑动才能翻到第二页
上面八杯从左至右：红茶拿提-强攻认证章，红茶拿提（浓）-异常认证章，果泡拿提（淡）-防护认证章，麦草拿提（淡）-引燃战术芯片，胡椒拿提-电击战术芯片，月壤魔咔-强攻组件，月壤魔咔（淡）-击破组件，空泡魔咔（淡）-防护组件
下面八杯从左至右：红茶拿提（淡）-击破认证章，果泡拿提-支援认证章，麦草拿提-物理战术芯片，麦草拿提（浓）-冰结战术芯片，胡椒拿提（淡）-以太战术芯片，月壤魔咔（浓）-异常组件，空泡魔咔-支援组件，新艾利都特调-无额外掉落

**Comment by DoctorReid** [comment]
谢谢！

**Comment by DoctorReid** [comment]
功能已经加上了，不过咖啡列表似乎不对，下周还要校验一次
