### ISSUE TITLE
[问题反馈] [通用] 一条龙每天只能从头到尾正常运行一次，不支持换号

### ISSUE THREAD

**Issue by szyandzxy** [DoctorReid/ZenlessZoneZero-OneDragon#76]
### 问题描述

如题，即换号以后，再次运行一条龙时，仅能运行今日未能成功执行完毕的一项，其他已完成的项目如刮刮卡等只能手动执行，而不是按照本次一条龙开启的项目依次执行。

**Comment by DoctorReid** [comment]
目前是不支持的

**Comment by DoctorReid** [comment]
已支持
http://one-dragon.org/zzz/zh/docs/feat_one_dragon.html#_4-%E5%A4%9A%E8%B4%A6%E5%8F%B7
