### ISSUE TITLE
手柄也可以么？

### ISSUE THREAD

**Issue by JONREAN2** [DoctorReid/ZenlessZoneZero-OneDragon#8]
如题

**Comment by DoctorReid** [comment]
没试过，但估计是不行，后续再适配

**Comment by DoctorReid** [comment]
游戏设置里，键鼠的时候对于一个按键，是可以设置一个鼠标按和一个键盘按两种方式的。

不知道手柄时候有没有这种，你可以试试，设置一个键盘按键给脚本用就行

**Comment by scount7** [comment]
> 游戏设置里，键鼠的时候对于一个按键，是可以设置一个鼠标按和一个键盘按两种方式的。
> 
> 不知道手柄时候有没有这种，你可以试试，设置一个键盘按键给脚本用就行

把键盘闪避键换成手柄RB/LB 也不行吗 可以试一试（键盘没手柄舒服啊

**Comment by DoctorReid** [comment]
> 把键盘闪避键换成手柄RB/LB 也不行吗 可以试一试（键盘没手柄舒服啊

上班没法测试。但看代码，现在用的库应该是没法模拟手柄按键的。

我的意思是，游戏设置里，对于闪避，如果可以的话，设置一个手柄按键，同时设置一个键盘按键，脚本通过模拟键盘自动闪避，玩家的操作还是在手柄上完成。

**Comment by JONREAN2** [comment]
> > 把键盘闪避键换成手柄RB/LB 也不行吗 可以试一试（键盘没手柄舒服啊
> 
> 
> 
> 上班没法测试。但看代码，现在用的库应该是没法模拟手柄按键的。
> 
> 
> 
> 我的意思是，游戏设置里，对于闪避，如果可以的话，设置一个手柄按键，同时设置一个键盘按键，脚本通过模拟键盘自动闪避，玩家的操作还是在手柄上完成。

我试过了 只能设置一种操作方式 （希望大佬后续有专门的手柄闪避

**Comment by sspture** [comment]
> > > 把键盘闪避键换成手柄RB/LB 也不行吗 可以试一试（键盘没手柄舒服啊
> > 
> > 
> > 上班没法测试。但看代码，现在用的库应该是没法模拟手柄按键的。
> > 我的意思是，游戏设置里，对于闪避，如果可以的话，设置一个手柄按键，同时设置一个键盘按键，脚本通过模拟键盘自动闪避，玩家的操作还是在手柄上完成。
> 
> 我试过了 只能设置一种操作方式 （希望大佬后续有专门的手柄闪避

应该可以用steam映射来解决

**Comment by DoctorReid** [comment]
的确，目前自己做个映射应该就可以了

**Comment by scount7** [comment]
> > > > 把键盘闪避键换成手柄RB/LB 也不行吗 可以试一试（键盘没手柄舒服啊
> > > 
> > > 
> > > 上班没法测试。但看代码，现在用的库应该是没法模拟手柄按键的。
> > > 我的意思是，游戏设置里，对于闪避，如果可以的话，设置一个手柄按键，同时设置一个键盘按键，脚本通过模拟键盘自动闪避，玩家的操作还是在手柄上完成。
> > 
> > 
> > 我试过了 只能设置一种操作方式 （希望大佬后续有专门的手柄闪避
> 
> 应该可以用steam映射来解决

话说steam有上传好的映射文件吗

**Comment by scount7** [comment]
映射我感觉一直调试不成功啊 可能是我的原因？

**Comment by DoctorReid** [comment]
似乎没有合适的库可以让脚本直接模拟手柄，后续了解到怎么做键盘映射到手柄的话，再发出相关教程

**Comment by hongfeizhang** [comment]
非常棒的训练
期待手柄适配

**Comment by MomentDerek** [comment]
> 似乎没有合适的库可以让脚本直接模拟手柄，后续了解到怎么做键盘映射到手柄的话，再发出相关教程

https://github.com/yannbouteiller/vgamepad 这个库行不行？我这边还没测试，得等不忙了先，大佬需要参考一下么

**Comment by DoctorReid** [comment]
这个看过，只支持xbox和ps4的，依赖的框架也是去年停止维护了，所以暂时没有尝试

**Comment by MomentDerek** [comment]
> 这个看过，只支持xbox和ps4的，依赖的框架也是去年停止维护了，所以暂时没有尝试

刚刚测试过了，可以，只不过需要额外安装驱动（确实是archive了），而且绝区零对手柄是所有玩家（1p，2p）的操作都合并执行的，意思就是程序模拟的手柄和玩家的手柄互不干涉，都成功输入了

**Comment by DoctorReid** [comment]
那你试试这个 https://github.com/Zalafina/QKeyMapper

我目前想法是脚本先不集成手柄输入，怕后面做自动日常的时候手柄模式不好做。先让大家用现成的软件做映射就算了

**Comment by MomentDerek** [comment]
> 那你试试这个 https://github.com/Zalafina/QKeyMapper
> 
> 我目前想法是脚本先不集成手柄输入，怕后面做自动日常的时候手柄模式不好做。先让大家用现成的软件做映射就算了

这边进行了一下测试，似乎是有问题的，可能是没有成功拦截到，有成功过，但是好像切出去再切回来触发软件的映射取消-重新映射后，就再也拦截不到了，得重新开两个软件

**Comment by MomentDerek** [comment]
> 那你试试这个 https://github.com/Zalafina/QKeyMapper
> 
> 我目前想法是脚本先不集成手柄输入，怕后面做自动日常的时候手柄模式不好做。先让大家用现成的软件做映射就算了

大概就是这个配置，键盘能操控手柄按键，但是一条龙触发的键盘操作无法被映射到手柄上
![image](https://github.com/user-attachments/assets/841dbd37-35ab-456f-b57e-0be988f52ac8)

**Comment by DoctorReid** [comment]
知道了 感谢测试

**Comment by DoctorReid** [comment]
@MomentDerek 你的是什么手柄

**Comment by DoctorReid** [comment]
这样子，还不太了解手柄，那看来是可以适配国产手柄的，可以搞起来了

**Comment by ccc007ccc** [comment]
> 这样子，还不太了解手柄，那看来是可以适配国产手柄的，可以搞起来了
绝区零能同时接收多个不同品牌的手柄同时输入,我用vgamepad模拟xbox手柄和物理ps5手柄同时用没有冲突,只会在模拟手柄输入时切换成xbox按键图标

**Comment by DoctorReid** [comment]
> 绝区零能同时接收多个不同品牌的手柄同时输入,我用vgamepad模拟xbox手柄和物理ps5手柄同时用没有冲突,只会在模拟手柄输入时切换成xbox按键图标

@ccc007ccc 这部分懂了。

游戏连接PS5手柄，然后进行了改键。那模型xbox手柄的按键应该是默认的xbox按键还是对应改键后的？

**Comment by ccc007ccc** [comment]
> 
> @ccc007ccc 这部分懂了。
> 
> 游戏连接PS5手柄，然后进行了改键。那虚拟xbox手柄的按键应该是默认的xbox按键还是对应改键后的？

是改键后的,两个手柄都是同一套键位设置

**Comment by DoctorReid** [comment]
@ccc007ccc 方便发一下PS5的在游戏里的默认按键吗，我的是xbox的

**Comment by ccc007ccc** [comment]
> @ccc007ccc 方便发一下PS5的在游戏里的默认按键吗，我的是xbox的

![mmexport1721819887890.png](https://github.com/user-attachments/assets/5976762f-0256-44fb-ab82-6d18c2d78ea4)

![mmexport1721819898736.png](https://github.com/user-attachments/assets/51f9a27b-37fa-4755-ab72-23e11f907a99)

三角对应xbox的Y，方框对应X，圆圈对应B，叉对应A，r1对应rb，r2对应rt，按键在手柄上的的位置和用处都和xbox是一样的，只有图标不一样

**Comment by DoctorReid** [comment]
可以用了各位，快来测测

**Comment by wtjzjyh** [comment]
> 可以用了各位，快来测测
提示未安装虚拟手柄依赖，怎么安装，requirements-prod.txt貌似未更新

**Comment by DoctorReid** [comment]
看[这里](https://github.com/DoctorReid/ZenlessZoneZero-OneDragon/wiki/%E5%85%B6%E5%AE%83-%E6%89%8B%E6%9F%84%E6%94%AF%E6%8C%81)

**Comment by scount7** [comment]
> 看[这里](https://github.com/DoctorReid/ZenlessZoneZero-OneDragon/wiki/%E5%85%B6%E5%AE%83-%E6%89%8B%E6%9F%84%E6%94%AF%E6%8C%81)

牛的 下班回去看看（但说实话 这个游戏已经弃了

**Comment by JONREAN2** [comment]
以后会同步版本发吗

scount7 ***@***.***> 于2024年7月25日周四 14:23写道：

**Comment by scount7** [comment]
> 看[这里](https://github.com/DoctorReid/ZenlessZoneZero-OneDragon/wiki/%E5%85%B6%E5%AE%83-%E6%89%8B%E6%9F%84%E6%94%AF%E6%8C%81)

大佬 为啥我用自己的python安装好依赖 还是检测不到啊 可以在你的软件一个手柄的依赖安装啊

**Comment by DoctorReid** [comment]
这两天会加

**Comment by DoctorReid** [comment]
https://github.com/DoctorReid/ZenlessZoneZero-OneDragon/releases/tag/0.03

安装器更新了
