### ISSUE TITLE
[问题反馈] [通用] 影像厅营业没选完就开始营业

### ISSUE THREAD

**Issue by hahaha418** [DoctorReid/ZenlessZoneZero-OneDragon#83]
### 问题描述

影像厅营业没选完就开始营业

### 游戏截图

![屏幕截图 2024-08-16 202604](https://github.com/user-attachments/assets/0604ec1a-59ec-473b-84a9-15a65eb5fa4d)

**Comment by DoctorReid** [comment]
开启推荐上架之后就不会了

**Comment by hahaha418** [comment]
?具体要怎么操作呢？这个现象一直存在

**Comment by DoctorReid** [comment]
40级做了某个直线就能开启
