### ISSUE TITLE
[问题反馈] [通用] 

### ISSUE THREAD

**Issue by wterstp** [DoctorReid/ZenlessZoneZero-OneDragon#90]
### 问题描述

一条龙失败,但自动战斗以及闪避这些都可以

### 游戏截图

![截图：20240818220603](https://github.com/user-attachments/assets/7d873a3d-74a0-420a-8a5c-68bfa6657a3c)
![截图：20240818220603](https://github.com/user-attachments/assets/97b473bc-6729-46ea-afdc-55d98821963e)
![截图：20240818220716](https://github.com/user-attachments/assets/bb2d14dc-d8e2-4c83-bbcb-e22eb9c4b72d)

### 运行日志

[
[Uploading log.txt…]()
](url)

**Comment by DoctorReid** [comment]
估计画质问题吧

**Comment by DoctorReid** [comment]
之前可能是分辨率问题。现在可以再试试其它16:9分辨率了。

注意，如果是全屏模式，屏幕的分辨率（不是游戏的）也需要是16:9
