### ISSUE TITLE
[问题反馈] [通用]  获取远程代码失败

### ISSUE THREAD

**Issue by Evgracess** [DoctorReid/ZenlessZoneZero-OneDragon#93]
### 问题描述

纯新手完全不熟
实在不知道怎么解决  只好问了

### 游戏截图

![螢幕擷取畫面 2024-08-19 124216](https://github.com/user-attachments/assets/158e5da1-ed63-44bc-8433-387f194c6bd4)

### 运行日志

[log.txt](https://github.com/user-attachments/files/16655848/log.txt)

**Comment by DoctorReid** [comment]
等待今晚的新安装包吧
