### ISSUE TITLE
[问题反馈] [通用] 希望添加对刮刮卡老板睡觉事件的支持

### ISSUE THREAD

**Issue by Kakitoritay** [DoctorReid/ZenlessZoneZero-OneDragon#99]
### 问题描述

如题，遇到睡觉事件就暂停运行了

### 游戏截图

![QQ截图20240821073057](https://github.com/user-attachments/assets/a218da2a-5220-4be1-a8ab-dfe95f00a6c5)

**Comment by DoctorReid** [comment]
#61 预计周末处理
